### DISCUSSION TITLE
Permission denied in cypress/included:6.5.0

### DISCUSSION THREAD

**Discussion by louh** [cypress-io/cypress#15225] [CI setup]
I'm getting this error message when running cypress/included in GitHub Actions:

```
/usr/local/bin/npx cypress verify
25l[17:28:04]  Verifying Cypress can run /root/.cache/Cypress/6.5.0/Cypress [started]
[17:28:04]  Verifying Cypress can run /root/.cache/Cypress/6.5.0/Cypress [failed]
25hAn unexpected error occurred while verifying the Cypress executable.

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Error: EACCES: permission denied, unlink '/root/.cache/Cypress/6.5.0/binary_state.json'
```

The workflow configuration that resulted in this error can be inspected here: https://github.com/streetmix/streetmix/blob/louh/gh-actions-cypress2/.github/workflows/ci.yml#L61-L82

```
  cypress:
    name: End-to-end (E2E) tests
    runs-on: ubuntu-latest
    container:
      image: cypress/included:6.5.0
    env:
      # We need placeholder API keys to mock some third party integrations
      PELIAS_API_KEY: ge-iampelias
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: 'http://localhost:8000'
          browser: firefox
```

**Comment by akoskm** [comment]
@louh have you found a solution to this issue? I followed basically what's on this page: https://docs.cypress.io/guides/continuous-integration/github-actions#Cypress-GitHub-Action

and receiving the same error.

**Reply by louh** [reply]
@akoskm It's been a while but we must have, since Cypress has worked on Actions for us now. Here is our latest config.

https://github.com/streetmix/streetmix/blob/main/.github/workflows/ci.yml#L71-L96

**Reply by akoskm** [reply]
Hey, thanks for getting back to me @louh. We also fixed this but I'm not 100% sure how exactly.
We're not using the `container` prop and I think it was the `install` flag that worked:

```
      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v2
        with:
          install: false
```
