### DISCUSSION TITLE
My circleci config isn't working to open a chrome browser and run the tests

### DISCUSSION THREAD

**Discussion by pedrohyvo** [cypress-io/cypress#15656] [Questions and Help] [answered]
I want to know why my `config.yml` isn't working to run my cypress tests on chrome browser. Anyone could help me on this?

`config.yml`
```
version: 2

jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/included:3.2.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    parallelism: 1
    context: smoke-test-staging
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Running smoke tests on chrome browser
          command: npm run smoketest:staging
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
```

`output from circleci`
```
It looks like this is your first time using Cypress: 6.8.0

[22:37:22]  Verifying Cypress can run /root/.cache/Cypress/6.8.0/Cypress [started]
[22:37:24]  Verifying Cypress can run /root/.cache/Cypress/6.8.0/Cypress [completed]

Opening Cypress...
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
Can't run because you've entered an invalid browser name.

Browser: 'chrome' was not found on your system or is not supported by Cypress.

Cypress supports the following browsers:
- chrome
- chromium
- edge
- electron
- firefox

You can also use a custom browser: https://on.cypress.io/customize-browsers

Available browsers found on your system are:
- electron
```

And my `package.json` has the following script:
```
"smoketest:staging": "npx cypress run --browser chrome --env configFile=staging,grep='smoke'"
```
