### DISCUSSION TITLE
cypress open + docker on remote VM - Unable to open X display. undefined: 0 illegal access

### DISCUSSION THREAD

**Discussion by mayteio** [cypress-io/cypress#15733] [Docker]
I'm trying to get the interactive test runner from Docker container -> remote GCP VM (Ubuntu) -> mac host and get the same error, no matter what I try:

```
[20:0401/014738.060326:ERROR:browser_main_loop.cc(1434)] Unable to open X display.

undefined:0

illegal access
```

References:
- https://stackoverflow.com/questions/59514234/viewing-the-interactive-cypress-test-runner-in-docker-on-linux
- https://github.com/cypress-io/cypress-docker-images/issues/395
- https://github.com/cypress-io/cypress-docker-images/issues/29
- https://gist.github.com/Yasushi/d4c719aacd79310777293ce024c33bcd

My understanding is that cypress, when running from docker, needs an X11 server to forward requests to. This server runs on my *host* and cypress connects to it via the `DISPLAY` env variable. To accept these requests, you have to add the requesting IP to `xhost` with `xhost +$IP` where IP is the machine making the request. I've done this.

Next, you need to make sure the DISPLAY env is set correctly. I have been working from a remote box (Ubuntu), so I have set the DISPLAY env to my host mac's IP with port 0: `xxx.xxx.xxx.xxx:0`. I have tried passing in the DISPLAY variable both via docker run and docker-compose: 

```
docker run -it --rm \
    --network host \
    -v ~/.Xauthority:/root/.Xauthority:ro \
    -e DISPLAY \
    -v $PWD/e2e:/e2e \
    -w /e2e \
    --entrypoint '' \
    cypress/included:6.8.0 \
    npx cypress open
```

```
version: '3'
services:
  e2e:
    image: cypress/included:6.8.0
    network_mode: host
    working_dir: /e2e
    volumes:
      - ./e2e:/e2e
      - ~/.Xauthority:/root/.Xauthority:rw
    entrypoint: cypress open --project /e2e
    environment:
      - DISPLAY
```

I have verified that DISPLAY is being passed through to the docker image by adding `echo $DISPLAY` to the entrypoint command - it correctly echo's my host's IP address. **No matter what I do, I always get `Unable to open X display undefined:0`**.`. I've tried multiple versions of `cypress/included`, I have ensured XQuartz is set up with the correct security setting (Allow connections from network clients). At a loss here!
