### DISCUSSION TITLE
Wait-on timeout on CI using orbs

### DISCUSSION THREAD

**Discussion by jaugustodafranca** [cypress-io/cypress#16209] [CI setup]
Hi folks, 

Recently I update my project to node 12 with cypress 6.5.0, and after the update, I noticed that tests begin to fail.  I'm using the orbs to run the test on CI, before the update the terminal that was running the `yarn start` still up and the wait-on worked fine: 

![image](https://user-images.githubusercontent.com/38357905/116143671-cd606180-a6b1-11eb-9de1-e54d019c0381.png)

Now for the same configuration, the terminal is being stoped so the wait-on gets a time out: 

![image](https://user-images.githubusercontent.com/38357905/116143810-fb45a600-a6b1-11eb-8061-b0057c600442.png)

the config that I'm using is: 

```
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.16.1

version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
executors:
  chrome85-ff81:
    docker:
      - image: cypress/browsers:node12.14.1-chrome85-ff81
jobs: 
 #other jobs
workflows:
  version: 2.1
  main_workflow:
    jobs:
      - cypress/run:
          yarn: true
          start:  yarn start
          store_artifacts: true
          wait-on: 'http://localhost:3000'
          record: true
          executor: chrome85-ff81
          browser: chrome
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
          requires:
              - main-job
```

I'm not sure if is something related to the orbs or with the node version, could you help me please?
