### DISCUSSION TITLE
Cypress v8 - How can I force now to run headed on CircleCi?

### DISCUSSION THREAD

**Discussion by melibe23** [cypress-io/cypress#17465] [CI setup]
This is my `config.yml`

I cannot find a way to force this to run headed on CircleCi, what should I do?

```
version: 2.1
orbs:
  node: circleci/node@4.2.1
  cypress: cypress-io/cypress@1.27.0
workflows:
  ga-components:
    jobs:
      - cypress/install:
          filters:
            branches:
              only:
                - master
      - cypress/run:
          name: components/app-bar/ga-chrome
          spec: cypress/integration/components/app-bar/ga.js
          executor: with-chrome-and-firefox
          browser: chrome
          config-file: cypress.ci.json
          requires: &ref_0
            - cypress/install
          attach-workspace: true
          filters: &ref_1
            branches:
              only:
                - master
          post-steps: &ref_2
            - store_artifacts:
                path: cypress/videos
```
