### DISCUSSION TITLE
Cucumber tags not working on github actions?

### DISCUSSION THREAD

**Discussion by MatiDiez** [cypress-io/cypress#17560] [CI setup]
I'm using cucumber-preprocessor and have tags for all my scenarios.
If I execute my tests from the terminal it runs correctly using `npx cypress-tags run --env TAGS=@Rewrite`

Following the docs here, I got to this configuration, but it is not working. It is running all specs (features) Even though it does recognize it. │ Params: `Tag: @Rewrite, Group: false, Parallel: false`

```
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          tag: "@Rewrite"
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Am I missing something or it doesn't support cucumber-proprocessor tags?
