### DISCUSSION TITLE
Unsolvable issues with the containerized approach

### DISCUSSION THREAD

**Discussion by mp-83** [cypress-io/cypress#17964] [Docker]
I am running into the notorious `localhost` problem. My `docker-compose.yml` (trimmed) looks like this:

```
version: "3.5"
services:
  server:
    .....
    ports:
      - "8000:8000"
    networks:
      - "frontend"
      - "backend"

  cypress:
    image: cypress/included:8.3.0
    depends_on:
      - server
    volumes:
      - ./e2e:/e2e
    working_dir: /e2e
    networks:
      - "frontend"
      - "backend"

networks:
  frontend:
    name: "frontend"
    driver: "bridge"
  backend:
    name: "backend"
    driver: "bridge"
``` 

and this is my `cypress.json` file
```
{
  "baseUrl": "http://host.docker.internal:8000",
  "pluginsFile": false,
  "supportFile": false,
  "reporter": "junit",
  "reporterOptions": {
    "mochaFile": "cypress/results/output.xml"
  }
}
```

The `website` is already up and running _hours before_ I start the `cypress` container and if I visit the address `http://localhost:8000/home` I get the homepage being displayed.
My `cypress/integration/spec.js` is this one

```

describe('My first test', () => {
  it('loads page', () => {
    cy.visit('/home')
    cy.contains('Home page')
  })
})
```

If I change my `baseUrl` inside the .json config file to `http://localhost:8000`, cypress container won't even bootstrap the test, returning the following error.

```
cypress_1      | Cypress could not verify that this server is running:
cypress_1      | 
cypress_1      |   > http://localhost:8000
cypress_1      | 
cypress_1      | We are verifying this server because it has been configured as your `baseUrl`.
cypress_1      | 
cypress_1      | Cypress automatically waits until your server is accessible before running tests.
cypress_1      | 
cypress_1      | We will try connecting to it 3 more times...
cypress_1      | We will try connecting to it 2 more times...
cypress_1      | We will try connecting to it 1 more time...
```

I have tens of blog article/StackOverflow answers and everyone seems to propose a different solution and no one works. 

Does anybody has an ultimate, stable solution to this problem? 
Is it to difficult to document the containerized approach once for all?
