### DISCUSSION TITLE
gitlab-cy.yml executes ony one command

### DISCUSSION THREAD

**Discussion by ppp3** [cypress-io/cypress#18841] [CI setup]
Hello,
I have gitlab-ci.yml file:
```
...
test-bla:
  stage: test
  script:
    - cypress run --config-file false --project %cd% --headless --spec='blabla\a.spec.js'
    - cypress run --config-file false --project %cd% --headless
    - whoami
  tags:
    - blatag
...
```

The problem is that this stages executes the first command. It doesn't execute the second and the third command. Does anybody know why and what is the solution?
