### DISCUSSION TITLE
gitlab integration

### DISCUSSION THREAD

**Discussion by ericyuri** [cypress-io/cypress#19010] [CI setup] [answered]
Hi guys, 

Can you help me with this issue? I want to integrate cypress with gitlab but I am getting this error. Do you know what I am doing wrong?

![image](https://user-images.githubusercontent.com/13050062/142686028-7b50e524-9485-434b-993c-e4cb46bd97dc.png)

Error Message
![image](https://user-images.githubusercontent.com/13050062/142686372-7af2dec5-e097-4950-bc6c-524cf222e0cb.png)

My .gitlab-ci.yml

```yml
# Install Cypress, then run all tests (in parallel)
stages:
  - build
  - test

# Set environment variables for folders in "cache" job settings for npm modules and Cypress binary
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# Cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/*
    - cache/Cypress
    - node_modules
    - build

# Install NPM dependencies and Cypress
install:
  image: cypress/browsers:node14.17.0-chrome88-ff89
  stage: build

  script:
    - yarn install --frozen-lockfile
    # check Cypress binary path and cached versions
    - npx cypress cache path
    - npx cypress cache list
    #- yarn types
    #- yarn lint
    - yarn test:unit:ci
    - yarn build:ci

ui-chrome:
  image: cypress/browsers:node14.17.0-chrome88-ff89
  stage: test
  parallel: 2
  script:
    - yarn start:ci & npx wait-on http://localhost:3000
    - npx cypress run --record --parallel --browser chrome --group "UI - Chrome" --spec `"cypress/tests/*"
    
```
Thank you.
