### DISCUSSION TITLE
Github actions: Conditionally record test results to cypress.io while using on: deployment_status trigger

### DISCUSSION THREAD

**Discussion by bscaspar** [cypress-io/cypress#21321] [CI setup] [answered]
We have a `nextjs` project deployed to Vercel. Currently we use a simple GitHub action for our testing pipeline which so far has worked great. It looks like this:

```yml
name: e2e-ci
on: deployment_status

jobs:
  e2e:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          CYPRESS_RECORD_KEY: [our key here]
```

The action runs on `deployment_status` and grabs the deployed Vercel URL after a successful deployment and runs the tests against this environment.

Each time we check code in, a new deployment happens, and a new test run (if the deployment was successful). Here’s the issue: 

**Recording the test results to [cypress.io](http://cypress.io/) on every single deployment is a waste of resources since a lot of these dev deployments are for basic UI testing purposes. I want to upload the test results for the `preview` and `master` branch only.** 

Unfortunately, I can’t use the `on: branch` command with the `deployment_status` action to specify the branch. Nor do I have access to the `GITHUB_REF` env var which would also determine the branch since that’s only accessible to actions that are triggered by the `pull_request` or `pull_request_target` triggers.

I'm looking for recommendations for conditionally setting the `record` flag with this type of action. Or other recs on how folks using nextjs + Vercel + Cypress use Github actions. Thank you!

**Comment by muratkeremozcan** [comment, marked as answer]
You have to have some scripting logic before the `Cypress run`step, which gives you a boolean result. After that, you pass that result instead of `record: true`

```yml
name: e2e-ci
on: deployment_status

jobs:
  e2e:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      
      # some CI logic that gives you a result, assigned to a variavble named thatResult
      
      
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: $(thatResult)
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          CYPRESS_RECORD_KEY: [our key here]
```

Here is a more complex example where instead of boolean value, the environment is figured out with a script and passed to the config file. It should give some ideas. https://dev.to/muratkeremozcan/the-32-ways-of-selective-testing-with-cypress-a-unified-concise-approach-to-selective-testing-in-ci-and-local-machines-1c19

**Reply by bscaspar** [reply]
Thanks for the help! With those docs and [this blog](https://glebbahmutov.com/blog/develop-preview-test/) I was able to come up with the following: 
```yml
name: e2e-ci
on: deployment_status

jobs:
  e2e:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # fetch all commits so we can find the branch
          fetch-depth: 0
      - name: Assign branch to env var 🌳
        run: |
          echo "deployment_branch_name=$(git name-rev --name-only $GITHUB_SHA)" >> $GITHUB_ENV
      - name: Assign cypress_record var based on branch
        run: |
          echo "${{ env.deployment_branch_name }}"
          echo "cypress_record=${{ contains('remotes/origin/dev refs/heads/preview refs/heads/master', env.deployment_branch_name) }}" >> $GITHUB_ENV
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: ${{ env.cypress_record }}
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          CYPRESS_RECORD_KEY: 50cb67fb-c0c1-45a5-a759-f73ac49eeb0c

```

The updates I made from the documentation you sent, which was really helpful, are:
- running tests agains deployed Vercel URL with `CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}`
- getting the branch name using
```yml
with:
     # fetch all commits so we can find the branch
     fetch-depth: 0
```
- determining whether or not to record using `echo "cypress_record=${{ contains('remotes/origin/dev refs/heads/preview refs/heads/master', env.deployment_branch_name) }}" >> $GITHUB_ENV`

It's not perfect but it works! Only recording test to cypress.io when the merging branch is `dev` (so `dev -> preview`) or `preview` for `preview -> master`
