### DISCUSSION TITLE
Bitbucket Pipelines hangs when testing a Nuxt app with Cypress

### DISCUSSION THREAD

**Discussion by theolavaux** [cypress-io/cypress#21367] [CI setup]
I have a Nuxt app that I want to test with Cypress in CI.
I've seen in the [Cypress documentation](https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server) that you have to install some third-party package to wait for the server to start and then run your tests.
I then installed the [wait-on](https://github.com/jeffbski/wait-on) package and created these scripts in package.json.

 *package.json*

```json
{
 "scripts": {
    "start:wait": "yarn start & wait-on http://localhost:3000",
    "run:cypress": "cypress run"  
  },
}
```
For the CI, I install the dependencies, run `nuxt generate` to bundle the app and then test using the step below.

*bitbucket-pipelines.yml*

```yml
- step: &e2e-test
  image: cypress/included:9.4.1
  name: Run application E2E tests
  caches:
    - cypress
  script:
    - yarn start:wait
    - yarn record:cypress -- --config video=true --parallel --ci-build-id $BITBUCKET_BUILD_NUMBER
  artifacts:
    # store any generates images and videos as artifacts
    - cypress/screenshots/**
    - cypress/videos/**

# A little bit below
- parallel:
  - step: *e2e-test
  - step: *e2e-test
  - step: *e2e-test
```

It works when I test it locally but in CI, Bitbucket hangs and nothing happens.

[![enter image description here][1]][1]

I've also seen the [start-server-and-test](https://github.com/bahmutov/start-server-and-test#readme) package but I don't know how to pass extra arguments like (`--config video=true --parallel --ci-build-id $BITBUCKET_BUILD_NUMBER`) to `run:cypress` from the CI.

`"ci": "start-server-and-test 'yarn start' http://localhost:3000 'run-cypress <extra-arguments-here?>'"`

Like this but with arguments from the CI to retrieve `$BITBUCKET_BUILD_NUMBER`

[1]: https://i.stack.imgur.com/nCUfD.png
