### DISCUSSION TITLE
Is there a way to cache Cypress?

### DISCUSSION THREAD

**Discussion by kary-ajrj** [cypress-io/cypress#22218] [CI setup]
Is there a way to enable caching on Github Actions.
It takes roughly 10-16 seconds for the tests to actually start.
It always says `It looks like this is your first time using Cypress: <Version>`

<img width="1021" alt="Screenshot 2022-06-09 at 16 37 52" src="https://user-images.githubusercontent.com/7961532/172833419-54c640ad-1c1f-4ccc-a3a4-82592c8e0999.png">

Example :
```
- uses: actions/setup-node@v3
   with:
      node-version: '16.15.1'
      cache: 'yarn'
```
