### DISCUSSION TITLE
In Github Actions NODE_ENV env variable should be set to "test" or "ci"?

### DISCUSSION THREAD

**Discussion by vkostunica** [cypress-io/cypress#22313] [Questions and Help]
I have Next.js app that loads environment variables form `.env.test` (public vars) and `.env.test.local` (private vars) for running tests in my local dev environment. Those same vars for Github Actions are hardcoded in `tests.yml` configuration.

In that project I have unit, api integration (with test database) and e2e (with database and built app for production) tests. In local environment I use Postgres inside Docker container, in Github Actions I define test db inside `yml`.

Currently inside yarn script I have `NODE_ENV=test` that sets this in both local and Github Actions environments. I can see that in GA both `.env.*` files are loaded and that variables are merged with variables defined in `yml` and I see that vars from `yml` take precedence.

Everything works fine like this but I have feeling this is not optimal solution because those two are indeed different environments. What if I at some future point change local environment and break GA. Also there can be multiple developers with different local environments plus GA environment. All this leads me to conclusion that in Github Action 
`NODE_ENV` should be `ci` and not `test`, so: `NODE_ENV=ci`. And I keep those vars independent and without random merging.

Do you know how this should be, did you implement this already and you have some existing example that I can look at?

```yml
jobs:
  tests:
    name: Run all tests locally on Ubuntu
    timeout-minutes: 15
    runs-on: ubuntu-22.04

    env:
      # --------------- private vars - .env.local ---------------
      # next-auth jwt
      SECRET: CI_SECRET

      # Google
      GOOGLE_CLIENT_ID: blank
      GOOGLE_CLIENT_SECRET: blank

      # database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ci-db
      POSTGRES_HOSTNAME: localhost
      POSTGRES_PORT: 5432


      # --------------- public vars - .env.test ---------------
      PROTOCOL: http
      HOSTNAME: localhost
      PORT: 3001

    services:
      postgres:
        image: postgres:14.3-bullseye
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
```
