### DISCUSSION TITLE
Component testing, wait for webpack to finish

### DISCUSSION THREAD

**Discussion by AlexandreGaubert** [cypress-io/cypress#24204] [CI setup]
We have a `create-react-app` project, and when we hit `cypress run --component`, Cypress doesn't seems to wait until webpack has finished the build.
It seems to be the cause of a bug we have in the CI. Here you can see that we get a `Timed out waiting for the browser to connect.`, probably because webpack is not done yet.

```
Running:  Timeline.cy.tsx                                                                 (1 of 6)

Timed out waiting for the browser to connect. Retrying...

Timed out waiting for the browser to connect. Retrying again...
webpack compiled successfully
No issues found.


Timeline

  
Timeline

  
    Timeline
      ✓ Should render big events (1743ms)
      ✓ Should render big events (1[64](https://github.com/Mergifyio/dashboard/actions/runs/3227988317/jobs/5283500022#step:4:65)5ms)


  2 passing (2s)
```

When we have this message, the first test suite is reported with duplicated tests. In logs above, the `Timeline` test file contains only one suite with one test.

Most of the time the job pass, but sometimes we get the error below:

```
Invalid array length
RangeError: Invalid array length
    at Runner.runner._events.pass.<computed> (/home/runner/.cache/Cypress/10.8.0/Cypress/resources/app/packages/server/lib/reporter.js:314:11)
    at Runner.emit (node:events:538:35)
    at Runner.emit (node:domain:4[75](https://github.com/Mergifyio/dashboard/actions/runs/3227988317/jobs/5283500022#step:4:76):12)
    at Reporter.emit (/home/runner/.cache/Cypress/10.8.0/Cypress/resources/app/packages/server/lib/reporter.js:362:46)
    at Object.onMocha (/home/runner/.cache/Cypress/10.8.0/Cypress/resources/app/packages/server/lib/project-base.js:272:34)
    at Socket.<anonymous> (/home/runner/.cache/Cypress/10.8.0/Cypress/resources/app/packages/server/lib/socket-base.js:260:40)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at Socket.emitUntyped (/home/runner/.cache/Cypress/10.8.0/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/runner/.cache/Cypress/10.8.0/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/socket.js:428:39
    at processTicksAndRejections (node:internal/process/task_queues:[78](https://github.com/Mergifyio/dashboard/actions/runs/3227988317/jobs/5283500022#step:4:79):11)

Error: Process completed with exit code 1.
```
After looking in the `/resources/app/packages/server/lib/reporter.js`, cypress seems to listen to `suite end` and `suite start` event, but the first event occurs more than the second and the Array is initialized with a negative length.

This bug never occurs on our MacOS laptops.

Here's the github action Yaml for the related job:
```yaml
  front:
    strategy:
      matrix:
        target: [eslint, test, "cy:comp"]
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 16
      - run: |
          npm ci
          npm run ${{ matrix.target }}
```

**Comment by apdrsn** [comment]
@AlexandreGaubert did you figure out how to fix this? We are struggling with the same issue. It's driving me crazy 🤯

**Comment by craigbehnke** [comment]
@apdrsn I was running into this problem as well, and while I could not _solve_ the issue, I was able to mitigate it somewhat. I am also using a CRA app (ejected), so my workaround was simply to make the build faster so that it would complete within the time alotted.

For me, that included setting a pair of environment variables for my cypress CICD job to eliminate features and artifacts I didn't need:

```yaml
cypress-components:
    variables:
        GENERATE_SOURCEMAP: "false"
        DISABLE_ESLINT_PLUGIN: "true"
```

Hopefully this gives you and/or someone else who finds this issue in the future on Google a place to start.
