### DISCUSSION TITLE
Cypress cannot see virtual host domain

### DISCUSSION THREAD

**Discussion by ezekel** [cypress-io/cypress#24268] [Docker]
Hi when I spin my container cypress container will exited

(Run Finished)

       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  spec.cy.js                               00:04        1        -        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     00:04        1        -        1        -        -

When I check the screenshot, I thought the url will be http://myapp.local

![image](https://user-images.githubusercontent.com/6830057/195988789-3797f6cd-565d-40e5-abc6-5d1188d97586.png)

 C:\Windows\System32\drivers\etc  I add

127.0.0.1 myapp.local

C:\myproject\myapp\e2e\cypress.config.js

```
module.exports = defineConfig({
    reporter: 'junit',
    reporterOptions: {
        mochaFile: 'cypress/results/output.xml',
    },
    e2e: {
        // We've imported your old cypress plugins here.
        // You may want to clean this up later by importing these.
        setupNodeEvents(on, config) {
            return require('./cypress/plugins/index.js')(on, config)
        },
        baseUrl: 'http://myapp.local',
        video: false,
        supportFile: "cypress/support/e2e.js",
    },
})

```

// docker-compose

```
services:
   web:
    build: .
        ports:
      - "80:80"

  e2e:
    image: cypress
    build: ./e2e
    container_name: cypress
    depends_on:
      - web
   
    environment:
      - CYPRESS_baseUrl=http://web

    command: npx cypress run
   
    volumes:
      - ./e2e/cypress:/var/www/myapp/e2e/cypress
      - ./e2e/cypress.config.js:/var/www/myapp/e2e/cypress.config.js

```

How can I tell to cypress the open the url  http://myapp.local ?

Thank you in advance
