### DISCUSSION TITLE
Help with a small issue on Cypress Github Action?

### DISCUSSION THREAD

**Discussion by garmeeh** [cypress-io/cypress#24296] [Questions and Help]
Hi 👋 

Currently trying to get Cypress up and running with parallel builds but hitting some issues. I have a feeling I am doing something dumb and missing something simple (hopefully) 😅 

If anyone had any ideas or could point me in the right direction it would be much appreciated.

The error I'm getting is:

```
Run cypress-io/github-action@v4.2.0
  with:
    install: false
    start: yarn e[2](https://github.com/garmeeh/next-seo/actions/runs/3276152429/jobs/5391902554#step:5:2)e:start
    wait-on: http://localhost:[3](https://github.com/garmeeh/next-seo/actions/runs/3276152429/jobs/5391902554#step:5:3)000
    wait-on-timeout: 120
    browser: chrome
    record: true
    parallel: true
    group: UI - Chrome
    component: false
  env:
    CYPRESS_RECORD_KEY: ***
    GITHUB_TOKEN: ***
/usr/bin/docker exec  7d106b25[4](https://github.com/garmeeh/next-seo/actions/runs/3276152429/jobs/5391902554#step:5:4)3f6cd24da0[5](https://github.com/garmeeh/next-seo/actions/runs/3276152429/jobs/5391902554#step:5:5)88f3fe47d1ae585845e943583eb[6](https://github.com/garmeeh/next-seo/actions/runs/3276152429/jobs/5391902554#step:5:6)929dddb8aeacd03f sh -c "cat /etc/*release | grep ^ID"
Skipping install because install parameter is false
start server "yarn e2e:start command "yarn e2e:start"
current working directory "/__w/next-seo/next-seo"
waiting on "http://localhost:3000" with timeout of 120 seconds
/usr/local/bin/yarn e2e:start
yarn run v1.22.1[7](https://github.com/garmeeh/next-seo/actions/runs/3276152429/jobs/5391902554#step:5:7)
$ next start e2e
/bin/sh: 1: next: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
/__w/_actions/cypress-io/github-action/v4.2.0/dist/index.js:35[8](https://github.com/garmeeh/next-seo/actions/runs/3276152429/jobs/5391902554#step:5:8)2
                error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
                        ^

Error: The process '/usr/local/bin/yarn' failed with exit code 127
    at ExecState._setResult (/__w/_actions/cypress-io/github-action/v4.2.0/dist/index.js:3582:25)
    at ExecState.CheckComplete (/__w/_actions/cypress-io/github-action/v4.2.0/dist/index.js:3565:18)
    at ChildProcess.<anonymous> (/__w/_actions/cypress-io/github-action/v4.2.0/dist/index.js:345[9](https://github.com/garmeeh/next-seo/actions/runs/3276152429/jobs/5391902554#step:5:9):27)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:[10](https://github.com/garmeeh/next-seo/actions/runs/3276152429/jobs/5391902554#step:5:10)64:[16](https://github.com/garmeeh/next-seo/actions/runs/3276152429/jobs/5391902554#step:5:17))
    at Process.ChildProcess._handle.onexit (node:internal/child_process:[30](https://github.com/garmeeh/next-seo/actions/runs/3276152429/jobs/5391902554#step:5:31)1:5)
```

See here for [action run](https://github.com/garmeeh/next-seo/actions/runs/3276152429/jobs/5391902554)

Here is my action file:

```
name: Cypress Tests

on: [pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v4.2.0
        with:
          # Disable running of tests within install job
          runTests: false
          build: yarn build:test

      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: |
            lib
            e2e/.next
  ui-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge
    needs: install
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v4.2.0
        with:
          # we have already installed all dependencies above
          install: false
          start: yarn e2e:start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: 'UI - Chrome'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
[View on GitHub](https://github.com/garmeeh/next-seo/blob/2ba1fba7b77c415fe9a0025c729e8ada154356aa/.github/workflows/cypress.yml)
