### DISCUSSION TITLE
cy.getCookie() returning null in CI environment

### DISCUSSION THREAD

**Discussion by xtatanx** [cypress-io/cypress#24402] [CI setup]
I am running Cypress tests through Jenkins and docker-compose using docker/included:10.10.0 image. Locally all tests work, but on the CI environment, specifically the `cy.getCookie()` command is not retrieving the cookies. I was wondering if there is any consideration when working with tests and cookies through the cypress container. Please find below my docker-compose configuration.

```
services:
  website:
    build: .
    command: npm run cy:build-and-start
    environment:
      - PORT=8080
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m
      timeout: 10s
      retries: 5
  cypress:
    image: 'cypress/included:10.10.0'
    environment:
      - CYPRESS_baseUrl=http://website:8080
    depends_on:
      website:
        condition: service_healthy
    working_dir: /e2e
    volumes:
      - ./:/e2e
```
