### DISCUSSION TITLE
Failed parallelisation in GitHub actions due to different runner image versions

### DISCUSSION THREAD

**Discussion by carbonid1** [cypress-io/cypress#24505] [CI setup]
We have a job that runs e2e test suites in parallel:
```
  run:
    name: Run
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8]
    steps:
      ...
```

But strangely enough, it started to fail recently due to different runner image versions in parallel jobs. The runner version always is `2.298.2` but the runner image version is either `20221024.1` or `20221027.1`. I tried to find a way to set the runner image version but it doesn't seem that GitHub allows doing that.

I'm curious if anyone else encountered such an issue.

![CleanShot 2022-11-02 at 17 36 29@2x](https://user-images.githubusercontent.com/36999873/199534464-c025bb70-65b1-425c-9b58-4bb06b548545.png)
![CleanShot 2022-11-02 at 17 42 14@2x](https://user-images.githubusercontent.com/36999873/199534826-6b1862b8-9596-474a-ba3b-274f6728e467.png)
