### DISCUSSION TITLE
How can we save snapshots/screenshots Artifacts from Azure pipeline to Azure blob?

### DISCUSSION THREAD

**Discussion by 787681277** [cypress-io/cypress#24672] [Questions and Help]
When using cypress doing visual regressions tests,how can we save snapshots/screenshots Artifacts from Azure pipeline to Azure blob?

**Comment by portyu9** [comment]
Hi @787681277 

Cypress does not need to upload these files itself. Let Cypress generate the screenshots/snapshots, then add a separate Azure Pipeline step that uploads the directory to Blob Storage.

For example:

```yaml
- task: AzureCLI@2
  condition: succeededOrFailed()
  inputs:
    azureSubscription: 'your-service-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az storage blob upload-batch \
        --account-name "yourstorageaccount" \
        --destination "cypress-artifacts" \
        --source "cypress/screenshots" \
        --auth-mode login
```

Using `succeededOrFailed()` is important if you want failure screenshots uploaded when Cypress fails.

Your Azure service connection identity also needs permission to write Blob data, such as the appropriate **Storage Blob Data Contributor** role.

For visual-regression snapshots, upload the snapshot/baseline/diff directory used by your particular visual-regression plugin as another batch, since that directory is plugin-specific rather than a Cypress standard.

Please mark this answer as accepted if it helped, thank you.
