### DISCUSSION TITLE
How to run Cypress e2e tests with parallelization in Azure CI CD

### DISCUSSION THREAD

**Discussion by ShanikaWickramasinghe** [cypress-io/cypress#24787] [Questions and Help]
I'm using azure CI CD pipelines to run my cypress end to end (e2e) tests, As our test suite has now grown with spec count, need to integrate test parallelization to decrease test suite execution time.

My test suite structure has a grouping mechanism where we have few test groups. Each spec is under a specific group and we maintain a resource shared architecture inside the groups to create and delete test data.

eg :-

app-mgt-test-group1 >> create-common-test-data-for-app-mgt-test-group1.spec.ts, app-mgt-spec1.ts, app-mgt-spec2.ts, delete-common-test-data-for-app-mgt-test-group1.spec.ts

user-mgt-test-group2 >> create-common-test-data-for-user-mgt-test-group2.spec.ts, user-mgt-spec1.ts, user-mgt-spec2.ts, delete-common-test-data-for-user-mgt-test-group2.spec.ts

We are using this resource shared structure to stop recreating the same resources again and again. As per my research on Cypress parallelization [1] which is supported from cypress framework level it do not support running the tests in parallel by preassigned a test group to a agent. As cypress dashboard will randomly assign a spec to agent and as our specs are not independent within a group this is causing a problem.

Is there a way that we can predefine and assign a test groups to multiple agents running in parallel. So all the specs in group 1 will get execute against agent 1 sequentially and all the specs in group 2 will get execute against agent 2 sequentially, and agent 1 and agent 2 will run in parallel. If cypress framework doesn't support running tests in parallel with group wise can this requirement be achieved through azure pipeline level parallelization. Using a approach like matrix or parallel [2]. If we integrate this from azure pipeline level do we need to do any modification for the cypress test suite execution against azure. Do we need to change the commands or configs in cypress level. Currently we are using npm run test to run the whole test suite in 1 agent in azure.

Appreciate your inputs and some examples how this can be achieved.

[1]. https://docs.cypress.io/guides/guides/parallelization

[2]. https://learn.microsoft.com/en-us/azure/devops/pipelines/test/parallel-testing-any-test-runner?view=azure-devops&viewFallbackFrom=vsts

I have tried to use cypress parallelization with

cypress run --record --group 4x-electron --parallel

But -- group option seems not doing what I expected. It is used to display the test run results in cypress dashboard under one group name.

**Comment by adrian-bartos** [comment]
This is a bit late to the party, but hopefully it helps someone else in the future.
I managed to do this in the following way:

my package.json has this command: "cy:run:record": "cypress run --browser chrome --record --key 123123 --parallel"

```
`jobs:
- job: CypressTests
  strategy:
    parallel: 5  # Use 5 agents from the pool
  pool:
    name: 'CypressAgents'  # You will need to create a pool of agents dedicated to running autotests
  steps:
  - script: npm ci
    displayName: 'Install dependencies'
    
  - script: npm run cy:run:record
    displayName: 'Run Cypress Tests'
    env:
      CYPRESS_RECORD_KEY: $(CypressRecordKey) # you will need to use the same cypress record key` 
```

When Azure DevOps spins up 5 parallel jobs:

All 5 agents will call npm run cy:run:record
Cypress Cloud sees 5 machines connected with --parallel flag
Cypress distributes your tests across all 5

What You Need:
 Cypress Cloud subscription (Team plan $75/mo or higher)

This provides the orchestration service
Records test results, videos, screenshots
Smart load balancing based on test duration history


Currently running with 3 agents, and the Azure UI will look something like this: 
<img width="279" height="270" alt="image" src="https://github.com/user-attachments/assets/7d739904-93c6-4195-8e3c-99b096f87c10" />
