### DISCUSSION TITLE
Video of failed tests in GitHub Actions?

### DISCUSSION THREAD

**Discussion by ftzi** [cypress-io/cypress#25037] [CI setup]
We have some flaky tests that are very hard to debug. They are not common to happen but as we run the tests many times in our CI (GitHub Actions), it's not rare to have different errors.

We can have the recording of the Cy runs if we run locally, but that isn't really helpful as the errors don't always happen as I said. The best would be a way to get recordings of the failed CI runs so we can better investigate the underlying issues when they happen.

I am probably missing something there. Is there a recommended way to have a recording of the failed tests?

**Comment by stavares843** [comment]
hello! 👋 

you can use something like

```
 - name: Upload videos of tests failed 
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
```

that way will only add videos for the failed tests 🔨
