### DISCUSSION TITLE
Github Actions + Nuxt + Cypress

### DISCUSSION THREAD

**Discussion by hslee2008** [cypress-io/cypress#25589] [Questions and Help] [answered]
I have been trying Nuxt with Cypress.

But almost everything is fine but running `yarn dev` actually returns error 503.

```
1) pages
       Index Page:
     CypressError: `cy.visit()` failed trying to load:

http://localhost:3000/

The response we received from your web server was:

  > 503: Service Unavailable

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
      at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:138203:84)
      at visitFailedByErr (http://localhost:3000/__cypress/runner/cypress_runner.js:137611:12)
      at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:138186:13)
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:8914:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:[684](https://github.com/HyunseungLee-Travis/littlechildwriter/actions/runs/4014732921/jobs/6895612743#step:3:685)9:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:[690](https://github.com/HyunseungLee-Travis/littlechildwriter/actions/runs/4014732921/jobs/6895612743#step:3:691)6:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:6951:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:7027:18)
      at _drainQueueStep (http://localhost:3000/__cypress/runner/cypress_runner.js:3621:12)
      at _drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:3614:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:3630:5)
      at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:3500:14)
  From Your Spec Code:
      at Context.eval (webpack:///./cypress/e2e/index.cy.ts:3:7)
```

This is my GitHub yml file

```
name: Cypress Test

on: push

jobs:
  chrome:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Chrome
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        with:
          build: yarn generate
          start: yarn dev
          browser: chrome
```

Please help!

**Comment by hslee2008** [comment, marked as answer]
Oh well.

```
name: Cypress Test

on: push

jobs:
  chrome:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Chrome
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        with:
          build: yarn generate
          start: yarn dev
          browser: chrome
          wait-on: 'http://localhost:3000'
```

using the `wait-on` works now.
