### DISCUSSION TITLE
Introducing in-app test results: A streamlined, local workflow for debugging CI failures

### DISCUSSION THREAD

**Discussion by pstakoun** [cypress-io/cypress#25649] [General]
Today, with the release of Cypress 12.5.0, we are excited to introduce a game-changing Cloud workflow to Cypress, that allows you to easily debug failed CI test runs right from your local app. With the new Debug page, you can review, rerun, and debug failed CI test runs that are recorded to Cypress Cloud – all without leaving the comfort of your local Cypress app.

We encourage you to provide any feedback that you may have, as we are actively iterating on and improving this feature. Please use this thread to provide feedback, request features, or just comment on the new Debug page in general.

If you have a larger bug to report, please file a dedicated issue.

**Comment by lucasdonato** [comment]
Hi, I loved the new debug functionality, however in the local Cypres App only the last execution of the Cypress Cloud is displayed, in my case I run the tests in parallel and I cannot see all the errors in the debug page.

![image](https://user-images.githubusercontent.com/12953400/216611400-629eb69c-b1b7-42d0-bf84-d6af44c82976.png)

![image](https://user-images.githubusercontent.com/12953400/216611450-f9e2a447-589c-42d2-8abd-2e19de89bba9.png)

**Reply by tbiethman** [reply]
Hi @lucasdonato, thank you for your feedback. Can you confirm that you are setting unique `--group` flags for your parallel recordings? Doing so will allow Cypress to combine both of your recordings into a single run and ensure that all your test results are present in the run shown in Debug page. More info about grouping can be found in in our [docs](https://docs.cypress.io/guides/guides/parallelization#Grouping-test-runs).

Or is there a reason why you would prefer to continue generating separate runs for these workflows?

**Reply by lucasdonato** [reply]
@tbiethman I used --group and it worked perfectly, thank you very much ;)

**Comment by spyglass24** [comment]
Hi @pstakoun , I have just added tag "--group daily" and it's failing on the bibucket run, only one rundom command is executing without teardown error. Rest of the runs have the following error message:
**_Searching for test report files in directories named [test-results, failsafe-reports, test-reports, TestResults, surefire-reports] down to a depth of 4
Finished scanning for test reports. Found 0 test report files.
Merged test suites, total number tests is 0, with 0 failures and 0 errors._**

![image](https://user-images.githubusercontent.com/66968202/217218475-ccb4c251-fe7c-485d-813b-0bc2db22398a.png)
Here is the .yml file
![image](https://user-images.githubusercontent.com/66968202/217218661-493b9997-1dcd-4cce-93c3-61783d6cd37e.png)

screen from bitbucket pipe
![image](https://user-images.githubusercontent.com/66968202/217218940-72d759c6-7e3c-4459-9c4a-a73a2e134bfc.png)

Any idea ?

**Reply by tbiethman** [reply]
Hi @spyglass24, thank you for reaching out. Do you see any warnings/errors in the collapsed `npm run cypress:pip-smk || true` step above your `Build teardown` step? I see that step only took 6s, which leads me to believe it errored for some reason.

**Reply by spyglass24** [reply]
Hi @tbiethman, Here is the error. 

![image](https://user-images.githubusercontent.com/66968202/217457642-5c071bb4-3c12-44f7-a55d-13e5e3028183.png)

**Reply by tbiethman** [reply]
Thanks @spyglass24, the error indicates that you're using the same group name ('Daily') for your multiple jobs here. The groups need to be unique across the different `cypress run --record` executions in within the same bitbucket pipeline. Your first screenshot of your various run commands doesn't show which `--group` values you're using, though, so let me know if my assumption here is incorrect.

Based on your tag usage, it could make sense to duplicate the tag as the group name to guarantee this uniqueness. For reference, [here are our docs](https://docs.cypress.io/guides/guides/parallelization#Grouping-test-runs) around run grouping, which includes some typical grouping strategies.

**Comment by nicooprat** [comment]
In case it helps someone else: I had to disable the Brave browser shield protection to be able to login into Cypress Cloud & link it to the local app:

![Brave shield disabled (in french)](https://user-images.githubusercontent.com/645641/217758185-1a58a4a4-b978-4dfa-8727-d851d524b5fa.png)

Without this, I could login but it never went back to the app.

**Comment by Deop** [comment]
Agreed with what @lucasdonato mentioned, I'd like to have an option to debug previous run. We do run multiple different suites from single branch during the day, so I would like to be able to choose specific run to debug.

**Reply by pstakoun** [reply]
@Deop thanks for your feedback! We're actively working on supporting this workflow. Out of curiosity, can you elaborate a bit on the workflow that involves multiple runs at different times? Is the reason you must have separate runs because they happen too far apart and therefore cannot be grouped via the `--group` parameter?

**Reply by Deop** [reply]
Yeah we have different runs during the day. We utilize --group for runs that supposed to be the part of one suite. But we could do full regression and couple of smoke suites runs (for example), so would be nice to be able to switch between them in the in-app debugger

**Reply by lucasdonato** [reply]
It would be nice :)

**Reply by spyglass24** [reply]
+++

**Comment by masomaananna** [comment]
If login process in google is possible by script like->  

describe('Login to Gmail', () => {
    it('Should be able to login', () => {
        cy.visit('https://gmail.com')
        cy.get('input[type="email"]').type('cypress@gmail.com')
        cy.get('#identifierNext').click()
        cy.get('input[type="password"]').type('Cypress@Cy#')
        cy.get('#passwordNext').click()
        cy.contains('Inbox').should('be.visible')
    }) 

Will be helpful for us. In selenium it is easy to login in google through the script. But in cypress it is difficult to do google authentication, which is difficult to understand.

**Reply by pstakoun** [reply]
@masomaananna we recommend logging in with Google programmatically, due to their heavy use of automation detection. Those docs can be found here: https://docs.cypress.io/guides/end-to-end-testing/google-authentication. You can also find patterns for logging in via the UI here: https://docs.cypress.io/guides/end-to-end-testing/social-authentication, but we do not recommend this approach for use in CI.

**Comment by Phonesis** [comment]
Keen to use this feature but it doesn't appear to work with the Cypress CircleCI Orb where you have multiple parallel stages with unique group names. For example, circleCI config using the official Cypress Orb:

```
   - cypress/run:
          name: cypress-tests-chrome
          executor: with-chrome-firefox-edge
          browser: chrome
          spec: cypress/e2e/specs/ui/**/*
          command-prefix: npx @percy/cli@latest exec --
          start: npm run start:test
          wait-on: '-c .circleci/wait-on-config.json http://localhost:3000'
          record: true
          parallel: true
          parallelism: 9
          group: 'Chrome tests'

   - cypress/run:
          name: cypress-tests-firefox
          executor: with-chrome-firefox-edge
          browser: firefox
          spec: cypress/e2e/specs/ui/**/*
          command-prefix: npx @percy/cli@latest exec --
          start: npm run start:test
          wait-on: '-c .circleci/wait-on-config.json http://localhost:3000'
          record: true
          parallel: true
          parallelism: 9
          group: 'Firefox tests'
```

Say 1 test fails for Chrome, but Firefox all passes and finishes last, you will only see the last result in the debug tab and it will show that all tests passed (because it will be the firefox group)

Is this a known issue? Any fix?
