### DISCUSSION TITLE
The cypress npm package is installed, but the Cypress binary is missing.

### DISCUSSION THREAD

**Discussion by sidarthakumar** [cypress-io/cypress#25652] [Questions and Help]
image: node:16
variables:
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'
stages:
  - Installing Dependencies
  - Code Quality
  - E2E(cypress) Tests

Installing Dependencies:
  stage: Installing Dependencies
  cache:
    key: '$CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR'
    paths:
      - node_modules/
      - cache/Cypress
  script:
    - npm ci --legacy-peer-deps

End to End (e2e cypress) Tests:
  stage: E2E(cypress) Tests
  parallel: 5
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"' #should never change.
  image: cypress/browsers:node16.16.0-chrome105-ff99-edge
  cache:
    key: '$CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR'
    paths:
      - node_modules/
      - cache/Cypress
  script:
    - apt-get update
    - apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4
      libnss3 libxss1 libasound2 libxtst6 xauth xvfb
    - npm run e2e
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day

**Comment by portyu9** [comment]
Hi @sidarthakumar 

This error means the worker can see the Cypress **npm package** in `node_modules`, but it cannot find the matching Cypress **binary** in its binary cache.

Those are separate things.

Your install job sets:

```yaml
CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'
```

so after `npm ci`, the binary should be under that directory. The E2E jobs must restore that same directory successfully.

I would first make the problem explicit in both jobs:

```yaml
script:
  - npx cypress cache path
  - npx cypress cache list
  - ls -la "$CYPRESS_CACHE_FOLDER" || true
```

If the install job lists the binary and the E2E job does not, the issue is the GitLab cache transfer rather than Cypress itself.

A robust alternative is to install dependencies in the E2E job as well and cache the npm download cache plus Cypress binary cache:

```yaml
variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - cache/Cypress/

End to End:
  image: cypress/browsers:node16.16.0-chrome105-ff99-edge
  script:
    - npm ci --legacy-peer-deps
    - npx cypress verify
    - npm run e2e
```

The `cypress/browsers` Docker image supplies browsers and their OS dependencies; it does not replace the Cypress package/binary installed for your project.

So I would concentrate on whether `cache/Cypress` is actually populated by the install job and restored into every parallel worker. The error by itself does not indicate that `node_modules/cypress` is missing.

Please mark this answer as accepted if it helped, thank you.
