### DISCUSSION TITLE
"Unknown Branch" when recording github action cypress runs

### DISCUSSION THREAD

**Discussion by shannonjarcher** [cypress-io/cypress#25854] [Cypress Cloud]
I can't find any reference to this, I'm consistently seeing all runs recorded under "Unknown Branch" and I don't know what I need to pass as an env var to cypress dashboard for it to recognize the branch.

**Comment by shannonjarcher** [comment]
Discovered its because I am running Cypress on the deployment status step which doesn't have a reference to the branch name. I can get that as part of the action, does anyone know how to pass on that information as part of the recording?

**Comment by bencao** [comment]
For people found this thread, the root cause of the difficulty is that in github deployment_status event, there's no information about the git branch which triggered the deployment initially.

In order to solve this issue, we can manage to save github branch status in the deployed application (for the application build step, it is pretty easy to get current github branch information). For example, in your build script save github branch to a public accessible file that contains the branch information.

Here's my solution for a Next.js application deployed to Vercel.

1. In package.json, add an additional command to the `build` script, so it looks like this `echo $VERCEL_GIT_COMMIT_REF > public/commit-ref && next build`. Notice here the branch information is saved to a public file, which can later become accessible from your application `https://your-app/commit-ref`
2. In github action, add a step to save commit ref to the step output, using curl to get the file content from the deployed application

```
 - name: Pull commit ref
    id: commit-ref
    run: |
      echo "COMMIT_INFO_BRANCH=$(curl -s ${{ github.event.deployment_status.environment_url }}/commit-ref)" >> $GITHUB_OUTPUT
```

3. In cypress run step, refer to the output from previous step

```
- name: 🌲 Cypress run
  uses: cypress-io/github-action@v6
  env:
    CYPRESS_BASE_URL: ${{ github.event.deployment_status.environment_url }}
    COMMIT_INFO_BRANCH: ${{ steps.commit-ref.outputs.COMMIT_INFO_BRANCH }}
```

Hope this helps.
