### DISCUSSION TITLE
Cypress Parallel run using Git Hub Action

### DISCUSSION THREAD

**Discussion by rameshGounder** [cypress-io/cypress#25948] [Questions and Help]
Hi last few days I am trying to set up Parallel run using Cypress Dashboard.
I am getting this error message:
un actions/upload-artifact@v3
/usr/bin/docker exec  37b9ec9a38f9073a2f5f910c725ede654ba80722ebc0a2358f0209474482277d sh -c "cat /etc/*release | grep ^ID"
Warning: No files were found with the provided path: .build. No artifacts will be uploaded.

My workflow like below:
name: Cypress Parallel Run Test
on:
  push:
    branches: [cypressDashboard]

jobs:
  install-job:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: .build

      - name: Cypress install
        uses: cypress-io/github-action@v5
        with:
          runTests: false
          build : npm run clean_dir
          command: npm ci

      - name: Save built folders 
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: .build
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          
  ui-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    needs: install-job
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: .build
      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          # we have already installed all dependencies above
          install: false
          command: npm run regression
          browser: chrome
          record: true
          parallel: true
          group: 'UI - Chrome'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

**Comment by portyu9** [comment]
Hi @rameshGounder 

The first failure is caused by the ordering of your steps.

You upload `.build` here:

```yaml
- name: Save build folder
  uses: actions/upload-artifact@v3
  with:
    path: .build
```

**before** the Cypress/install/build step that could create `.build`.

Build first, then upload the resulting directory:

```yaml
- name: Install and build
  uses: cypress-io/github-action@v7
  with:
    runTests: false
    build: npm run build # use the command that actually creates .build

- name: Save build folder
  uses: actions/upload-artifact@v7
  with:
    name: build
    path: .build
    if-no-files-found: error
    include-hidden-files: true
```

Replace `npm run build` with whatever command in your project actually creates `.build`. Your posted workflow uses `npm run clean_dir`, so verify that it really produces that directory before trying to upload it.

The `include-hidden-files: true` part is important with current versions of `upload-artifact`, because `.build` is a hidden directory and hidden files/directories are excluded by default.

Then your parallel jobs can download that artifact before starting their Cypress runs.

Please mark this answer as accepted if it helped, thank you.
