### DISCUSSION TITLE
Github Actions tests are keep failing because no results are found

### DISCUSSION THREAD

**Discussion by Areso** [cypress-io/cypress#25977] [Questions and Help]
```
  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: 2 seconds                                                  

  -  Video output: /home/runner/work/1255-burgomaster/1255-burgomaster/tests/tests_cypress/E2E/cypress/videos/buttonBuilding.cy.js.mp4


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  buttonCity.cy.js                                                                (3 of 5)
  -  Finished processing: 3 seconds                                                  

  -  Video output: /home/runner/work/1255-burgomaster/1255-burgomaster/tests/tests_cypress/E2E/cypress/videos/buttonBuilding.cy.js.mp4

ENOENT: no such file or directory, stat '/home/runner/work/1255-burgomaster/1255-burgomaster/tests/tests_cypress/E2E/cypress/videos/buttonBuilding.cy.js-compressed.mp4'
Error: ENOENT: no such file or directory, stat '/home/runner/work/1255-burgomaster/1255-burgomaster/tests/tests_cypress/E2E/cypress/videos/buttonBuilding.cy.js-compressed.mp4'
Test run failed, code 1
More information might be available above
Cypress module has returned the following error message:
Could not find Cypress test run results
Error: Could not find Cypress test run results
```

here my config for the GithubActions:
```
name: "E2E tests"

on:
  pull_request:
  push:
  workflow_call:
  workflow_dispatch:

jobs:
  smoke_job:
    name: Cypress E2E tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: run server with the front of the game
        run: python3 -m http.server 8080 &

      - name: check whether game is UP
        run: |
          curl -X GET "http://localhost:8080/"
      
      - name: cypress run
        uses: cypress-io/github-action@v5      
        with:
          working-directory: tests/tests_cypress/E2E
          start: npm run start
```

**Comment by portyu9** [comment]
Hi @Areso 

`Could not find Cypress test run results` is a **secondary error** here. The first actual failure is:

```text
ENOENT: no such file or directory, stat '...buttonBuilding.cy.js-compressed.mp4'
```

So Cypress is failing while handling the compressed video, and the GitHub Action subsequently has no normal run result to process.

If you are pinned to the old Cypress version from this 2023 setup and need videos, disable compression:

```js
const { defineConfig } = require('cypress')

module.exports = defineConfig({
  video: true,
  videoCompression: false,
})
```

If you do not need videos, simply use:

```js
module.exports = defineConfig({
  video: false,
})
```

On current Cypress, both video recording and video compression default to `false`, so this specific compression path is normally avoided unless you opt back into it.

I would also update the workflow from the old unsupported `cypress-io/github-action@v5` to the current major:

```yaml
- name: Cypress run
  uses: cypress-io/github-action@v7
  with:
    working-directory: tests/tests_cypress/E2E
    start: npm run start
```

If it still fails after upgrading, enable Cypress video/debug logging and investigate the first error above rather than the later “no test run results” message.

Please mark this answer as accepted if it helped, thank you.
