### DISCUSSION TITLE
Can Not read a Json with github actions

### DISCUSSION THREAD

**Discussion by JoaqPareja** [cypress-io/cypress#26127] [CI setup]
When running the script from the github actions, it does not read the json file.

 Running:  Geant/reConstrucProduct/reConstrucProduct.cy.ts                                 (5 of 5)

  Re convert products
    1) "before each" hook: Bring products for "Convert array"

  0 passing (5s)
  1 failing

  1) Re convert products
       "before each" hook: Bring products for "Convert array":
     AssertionError: Timed out retrying after 4000ms: `cy.readFile("../fixtures/datatest.json")` failed because the file does not exist at the following path:

`/home/runner/work/Scapping/fixtures/datatest.json`

https://on.cypress.io/readfile

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Re convert products`
      at Context.eval (webpack:///./cypress/e2e/Geant/reConstrucProduct/reConstrucProduct.cy.ts:12:11)

File:
```
/// <reference types="cypress" />


describe('Re convert products',()=>{
const jsonProduct:string = '../fixtures/datatest.json'
let productBrand:Array<string> =[];
let titleProduct:Array<string> =[]; 
let priceProduct:Array<string> =[]; 
let arrayCoffeeListArray:Array<string> =[];
let elements:unknown; 
    beforeEach('Bring products',()=>{
        cy.readFile(jsonProduct).then((str)=>{
            productBrand = str[0];
            titleProduct = str[1];
            priceProduct = str[2]
        })
    })
    it('Convert array',()=>{   
            cy.reCreateProduct(productBrand, elements, titleProduct, priceProduct, arrayCoffeeListArray)
    })
    it('Check positions of Array', ()=>{
        cy.wrap(arrayCoffeeListArray)
        cy.log('checking especific positions')
        cy.wrap(arrayCoffeeListArray[0])
        cy.wrap(arrayCoffeeListArray[1])
        cy.wrap(arrayCoffeeListArray[2])
        cy.wrap(arrayCoffeeListArray[3])
    })
})
```
Yaml:
```
name: Cypress NewTests

on: 
  schedule:
    - cron: '50 20 * * 1,5'
    - cron: '00 21 * * 1,5'
    - cron: '00 22 * * 1,5'
jobs:
   cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
```
