### DISCUSSION TITLE
Is there a way to remove the "What's new in Cypress" message?

### DISCUSSION THREAD

**Discussion by troccoli** [cypress-io/cypress#26134] [Questions and Help]
I'm running Cypress using a docker-compose with the following configuration

```yaml
cypress:
  image: 'cypress/included:12.8.0'
  profiles:
    - on-demand-only
  volumes:
    - '.:/e2e'
    - '/tmp/.X11-unix:/tmp/.X11-unix'
  working_dir: /e2e
  environment:
    - CYPRESS_baseUrl=http://laravel.test
    - CYPRESS_VIDEO=false
    - DISPLAY=host.docker.internal:0
  networks:
    - sail
  depends_on:
    - laravel.test
  entrypoint: cypress
```
and with the following command
```shell
docker run -it -rm cypress open --project .
```
The first thing I see is the "What's new in Cypress" message and I have to click on the button to go on.

![Screenshot 2023-03-15 at 19 10 22](https://user-images.githubusercontent.com/11234160/225715811-dae4e572-b620-41ca-8555-126c4585f047.png)

Is there any way I can disable it?
