### DISCUSSION TITLE
Running Cypress against multiple sites in GitHub Actions

### DISCUSSION THREAD

**Discussion by nagendrakumar02** [cypress-io/cypress#26220] [Questions and Help]
I want to run my cypress tests against different sites as part of CI in github actions. Ideally I am looking to see if there is a way to read a SITEURLS="https://example1.com https://example2.com" and loop through a for loop. Inside the for loop to call npm run cypress:run -- --env URL=${siteUrl}

Each site has its own configuration values, that we use to check. 

Is this possible? If there is a better way to test this, please let me know.

**Comment by portyu9** [comment]
Hi @nagendrakumar02 

Yes, you can loop over the URLs in a shell script, but for GitHub Actions I would use a **matrix** instead. Each site then gets its own job and failure result.

For example:

```yaml
jobs:
  cypress:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        baseUrl:
          - https://example1.com
          - https://example2.com

    steps:
      - uses: actions/checkout@v7

      - run: npm ci

      - run: npx cypress run
        env:
          CYPRESS_BASE_URL: ${{ matrix.baseUrl }}
```

Then configure your tests using relative URLs:

```js
cy.visit('/')
```

Cypress will prefix `cy.visit()` and `cy.request()` with the configured `baseUrl`.

This is preferable to inventing a custom `URL` environment variable if what you are changing really is the application's base URL.

If each site also needs additional settings, put those into matrix objects using `include:` and pass each setting separately.

For current Cypress, also distinguish between configuration and secrets: public test configuration can use the current configuration/expose APIs, while credentials and tokens should remain CI secrets rather than being bundled into browser-accessible configuration.

Please mark this answer as accepted if it helped, thank you.
