### DISCUSSION TITLE
Cypress Parallel Run - in Github Actions

### DISCUSSION THREAD

**Discussion by jkesineni-incomm** [cypress-io/cypress#26639] [Questions and Help]
Hi All ,
I am working on Cypress GitHub Actions to run selected test suite in pipeline. and planning to run parallel so that we can reduce the regression time. 
I followed the sample code and able to trigger the flow and its creating 3 containers, but not running parallel, its running all one after other. 

I have enabled parallel flag.  here is the config used. 

 - name: Cypress Parallel Run
        uses: cypress-io/github-action@v5.0.5
        id: parse1
        # uses: tgamauf/cypress-parallel@v2
        with:
          browser: electron
          group: "UI - Chrome"
          parallel: true
          count-runners: 3
          record: true
          server: ${{ github.event.inputs.environment }}
          env: SUITE=${{ github.event.inputs.suitename }}
          #spec: cypress/integration/test_flows/regular-cases/happy-path.spec.js
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

please help me if anything i am missing here.

**Comment by portyu9** [comment]
Hi @jkesineni-incomm 

`parallel: true` does not create parallel GitHub Actions runners. It only tells Cypress Cloud that **multiple already-running CI machines** belong to the same parallel run.

So this:

```yaml
with:
  parallel: true
  count-runners: 3
```

still runs in a single GitHub Actions job. `count-runners` is not an input that makes the Cypress GitHub Action create three runners.

Create the three jobs with a GitHub Actions matrix instead:

```yaml
jobs:
  test:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]

    steps:
      - uses: actions/checkout@v7

      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          browser: electron
          record: true
          parallel: true
          group: "UI - Electron"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

GitHub Actions now starts three copies of the `test` job concurrently. Since all three use `record: true` and `parallel: true`, Cypress Cloud coordinates them and distributes the spec files between them.

Also note that your original group was called `"UI - Chrome"` while `browser: electron` was configured. The group name is only a label, but renaming it avoids confusion.

For current setups, `cypress-io/github-action@v7` is the supported version; the old v5 action used in the question is no longer supported.

Please mark this answer as accepted if it helped, thank you.
