### DISCUSSION TITLE
Running parallel test on gitlab ci with retry - can't make it happen

### DISCUSSION THREAD

**Discussion by efiShtain** [cypress-io/cypress#27029] [CI setup]
# The Problem
Running in gitlab-ci, using parallel, trying to allow re running only the failed jobs.

I have the following (reduced) pipeline
```yaml
Run Cypress:
  stage: verify
  image: cypress/browsers:node16.16.0-chrome107-ff107-edge
  script:
    - npx cypress run --config baseUrl=<MY_FRONTEND_URL>,projectId=$CYPRESS_PROJECT_ID --parallel --record --browser chrome --group "TESTSt" --ci-build-id=$CI_PIPELINE_ID-$CI_JOB_ID
    expire_in: 5 day
  parallel: 5
```

It spawns 5 parallel jobs that should split the specs based on cypress cloud orchestrator. The --ci-build-id flag is here to support retry failed job based on the workaround described here issue https://github.com/cypress-io/cypress/issues/8451

The workaround works well if I set the parallel to 1

But when trying to run tests in parallel > 1 it does not work 

Each job gets a unique ci-build-id so cypress cloud does not split the specs between the jobs

If I stick to the inferred ci-build-id (which is CI_PIPELINE_ID in gitlab), the parallel execution works, but I can't retry any failed job

Any ideas ?
