### DISCUSSION TITLE
Cypress cannot connect to edge browser if I run tests in gitlab runner

### DISCUSSION THREAD

**Discussion by Cinamo-Vento** [cypress-io/cypress#27391] [CI setup]
Hi!

I use Cypress to run autotests on three different browsers.
When I run "npx cypress run --browser edge" locally on my laptop, Cypress launches Edge successfully.
But I need to run tests in Gitlab Runner (this is also installed on my laptop). 
For some reason Cypress is unable to connect to Edge if tests are run in Gitlab CI. There are no problems connecting to Chrome and Firefox.

I tried to specify the path to the msedge.exe file, but it does not help. I also tried updating Edge, that didn't help either.
Trying to change the image to an image from the Edge browser didn't help either, Cypress still couldn't connect to Edge.

My pipeline log:

```
$ npm ci
added 420 packages, and audited 421 packages in 5s
59 packages are looking for funding
  run npm fund for details

$ npx cypress run --browser edge
DevTools listening on ws://127.0.0.1:65337/devtools/browser/7843c549-1df9-4b1c-93fb-82dbe7e25596

Running:  NegativeSecretTest.cy.js                                                        (1 of 4)
Still waiting to connect to Edge, retrying in 1 second (attempt 18/62)
Still waiting to connect to Edge, retrying in 1 second (attempt 19/62)

...

Still waiting to connect to Edge, retrying in 1 second (attempt 61/62)
Still waiting to connect to Edge, retrying in 1 second (attempt 62/62)
All promises were rejected
AggregateError: All promises were rejected
```

If I specified the path to Edge:

```
$ npm ci
added 420 packages, and audited 421 packages in 14s
59 packages are looking for funding
  run `npm fund` for details

$ npx cypress info
DevTools listening on ws://127.0.0.1:52572/devtools/browser/e0690623-d9a4-404d-a4e9-2a2682e33ee5
Displaying Cypress info...
Detected 3 browsers installed:
1. Chrome
  - Name: chrome
  - Channel: stable
  - Version: 114.0.5735.199
  - Executable: C:\Program Files\Google\Chrome\Application\chrome.exe
  - Profile: C:\windows\system32\config\systemprofile\AppData\Roaming\Cypress\cy\production\browsers\chrome-stable
2. Edge
  - Name: edge
  - Channel: stable
  - Version: 115.0.1901.183
  - Executable: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
  - Profile: C:\windows\system32\config\systemprofile\AppData\Roaming\Cypress\cy\production\browsers\edge-stable
  
...

$ npx cypress run --browser $EDGE_PATH
DevTools listening on ws://127.0.0.1:52585/devtools/browser/81e44e52-f28e-413f-b4a0-8a97a5a0e904

  Running:  NegativeSecretTest.cy.js                                                        (1 of 4)
Still waiting to connect to Custom edge, retrying in 1 second (attempt 18/62)
Still waiting to connect to Custom edge, retrying in 1 second (attempt 19/62)
Still waiting to connect to Custom edge, retrying in 1 second (attempt 20/62)

...

Still waiting to connect to Custom edge, retrying in 1 second (attempt 61/62)
Still waiting to connect to Custom edge, retrying in 1 second (attempt 62/62)
All promises were rejected
AggregateError: All promises were rejected
```

My gitlab-ci.yml file:

```yaml

image: cypress/base:18.16.0
# image: cypress/browsers:node16.18.0-chrome107-ff106-edge

test_on_edge:
  stage: test
  allow_failure: true  
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - npm ci
    - echo "The grepTag is '$GREP_TAG'"
    - npx cypress info
    # - npm run cy:run:edge
    - npx cypress run --browser $EDGE_PATH
  artifacts:
    when: always
    name: $CI_PIPELINE_ID
    paths:
      - reports
      - screenshots      
    expire_in: 1 day

```

Please tell me why he can't connect to Edge even though he sees it?
