### DISCUSSION TITLE
Cypress syntax .its can not run on github Action

### DISCUSSION THREAD

**Discussion by pepqymumpuni** [cypress-io/cypress#28232] [CI setup]
Hello Team,

My name is Pepqy, and I've encountered an issue with running Cypress tests on GitHub Actions. Specifically, the `.its` command seems to fail when executed in the GitHub Actions environment, although the same tests pass without any problems on my local machine

Cypress v : 13.2.0
OS : MacOS

here my code preview
test.js

```
 Then(`Step 1`, () => {
 cy.intercept('POST', '**/yy/xx').as('assignmentId');
  maintainPage.submitBtn().click();
});

Then(`Step 2`, () => {
  cy.wait('@assignmentId')
    .its('response.body.data.0')
    .then((maintainResponse) => {
      cy.createMaintainSchedule(param1,param2).as(
        'maintainScheduleResponse'
      );
    });
});

```
main.yaml

```
E2ETestSPVCockpit:
    needs: [FormatingStandart]
    if: github.event.inputs.squad == 'spvcockpit'
    name: E2E test for squad spvcockpit
    environment: SIT
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Set up cypress.env.json from secret
        run: echo '${{ secrets.CYPRESS_ENV }}' > cypress.env.json
      - name: Cypress run for squad spvcockpit
        uses: cypress-io/github-action@v6
        with:
          command: npm run run:e2e:spvcockpit
```
