### DISCUSSION TITLE
Cannot run cypress/browsers Docker image in GitLab CI (Failed to connect to socket /run/dbus/system_bus_socket)

### DISCUSSION THREAD

**Discussion by MaxAtoms** [cypress-io/cypress#29538] [CI setup]
Hey 👋🏽 I am currently trying to get component tests running in GitLab CI.
Unfortunately, even when running the official Cypress Docker image, I receive the following error:

```
Cypress failed to start.
This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies
Please refer to the error below for more details.
----------
[77:0518/093157.817760:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[77:0518/093158.682828:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[77:0518/093158.682848:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
----------
Platform: linux-x64 (Debian - 11.9)
Cypress Version: 13.8.1
```

Minimal GitLab CI reproduction:

```
stages:
  - test

component-test:
  image: cypress/browsers:node-20.13.0-chrome-124.0.6367.155-1-ff-125.0.3-edge-124.0.2478.80-1
  stage: test
  script:
    - npm ci
    - npx cypress run --component --headless
```

The answers here did not really help: https://github.com/cypress-io/cypress/issues/4925. It also feels like two failure modes get mixed up here (not running vs. running with warnings).

The troubleshooting part of the documentation suggests using the Docker image in case of this error (which I already do): https://docs.cypress.io/guides/references/troubleshooting#Run-Cypress-by-itself

Any ideas? Could this be an issue with the host system/runner?
