### DISCUSSION TITLE
How to overwrite the e2e baseUrl in cypress.config.ts?

### DISCUSSION THREAD

**Discussion by Baluditor** [cypress-io/cypress#29579] [Questions and Help]
I'm running into an issue that our testing env's has a dynamic url which is unknown ahead of time. 
I have the following `cypress.config.ts`:
```ts
import { defineConfig } from 'cypress';

export default defineConfig({
  defaultCommandTimeout: 20000,
  e2e: {
    experimentalModifyObstructiveThirdPartyCode: true,
    // I want to overwrite this one
    baseUrl: 'http://localhost:3000',
  },

  component: {
    devServer: {
      framework: 'react',
      bundler: 'vite',
    },
  },

  env: {
    baseUrl: 'http://localhost:3000',
    authUrl: 'https://localhost:4013',
    products_url: '/products',
  },

  video: false,
  screenshotOnRunFailure: false,

  viewportHeight: 800,
  viewportWidth: 1200,
});
```

I have to use a different `env` var, `hostUrl` instead of just the baseUrl as it's won't get overwritten by the following config:
```yml
name: Run tests
on: [pull_request]

jobs:
  cypress-e2e-run:
    name: Cypress E2E tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: add deployment configuration for main branch
        run: |
          cat testing.env.conf >> $GITHUB_ENV

      - name: Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          config:
          browser: chrome
          wait-on: ${{ env.swa_preview_hostname_first_part }}-${{ github.event.pull_request.number }}.${{ env.swa_preview_hostname_second_part }}
          # Wait for the app to be deployed
          wait-on-timeout: 360
        env:
          CYPRESS_userName: ${{ secrets.CYPRESS_USER_NAME_TESTING }}
          CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD_TESTING }}
          CYPRESS_authUrl: ${{ env.VITE_APP_AZURE_B2C_AUTHORITY }}
          # Base URL overwrite is somewhat working. Withouth it, the test would run agains the localhost. Setting it solves that issue, but accessing it with cypress.env('baseUrl') will still returns 'localhost'.
          CYPRESS_baseUrl: ${{ env.swa_preview_hostname_first_part }}-${{ github.event.pull_request.number }}.${{ env.swa_preview_hostname_second_part }}
          # But baseUrl still can't be used in the tests, thus setting a hostUrl variable which will have the correct value.
          CYPRESS_hostUrl: ${{ env.swa_preview_hostname_first_part }}-${{ github.event.pull_request.number }}.${{ env.swa_preview_hostname_second_part }}

  component-tests:
    name: Cypress Component tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress Component tests
        uses: cypress-io/github-action@v6
        with:
          component: true
```
