### DISCUSSION TITLE
> my-server -p 3030 --https  sh: 1: my-server: not found /home/runner/work/_actions/cypress-io/github-action/v6/dist/index.js:3900                 error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);                         ^

### DISCUSSION THREAD

**Discussion by HIIMMERCADO** [cypress-io/cypress#29761] [Questions and Help]
Im encountering this issue can you please help me? 

Here is my workflow:

```
name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # Runs tests in parallel with matrix strategy https://docs.cypress.io/guides/guides/parallelization
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    # Also see warning here https://github.com/cypress-io/github-action#parallel
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1, 2] # Uses 2 parallel instances
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          # Starts web server for E2E tests - replace with your own server invocation
          # https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server
          start: npm start
          wait-on: 'https://easyfis-ui-next.hiro-test.net/' # Waits for above
          # Records to Cypress Cloud 
          # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
          record: true
          parallel: true # Runs test in parallel using settings above
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```
```
> my-server -p 3030 --https

sh: 1: my-server: not found
/home/runner/work/_actions/cypress-io/github-action/v6/dist/index.js:3900
                error = new Error
sh: 1: my-server: not found
/home/runner/work/_actions/cypress-io/github-action/v6/dist/index.js:3900
                error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
                        ^
```

![Screenshot_5](https://github.com/cypress-io/cypress/assets/166775610/d9cfb60d-abf3-4ef9-be57-3506d541d7a8)

**Comment by portyu9** [comment]
Hi @HIIMMERCADO 

The failure happens **before Cypress tests start**:

```text
> my-server -p 3030 --https
sh: 1: my-server: not found
```

Your `npm start` script is trying to execute a binary named:

```text
my-server
```

but that executable does not exist in the GitHub Actions environment.

This is not a Cypress test failure. Check the `start` script in `package.json`, for example:

```json
{
  "scripts": {
    "start": "my-server -p 3030 --https"
  }
}
```

If `my-server` is a real npm package/tool your project requires, make sure it is declared in `dependencies` or `devDependencies` so that `npm install`/`npm ci` installs its binary.

If `my-server` was only a placeholder or a command installed globally on your development machine, replace it with the actual project server command, for example whatever your framework provides:

```json
{
  "scripts": {
    "start": "..."
  }
}
```

There is also a configuration mismatch worth checking in the workflow.

You currently have something equivalent to:

```yaml
with:
  start: npm start
  wait-on: 'https://easyfis-ui-next.hiro-test.net/'
```

If Cypress is meant to test the **already deployed** `easyfis-ui-next.hiro-test.net` environment, you probably do not need to start a local server at all:

```yaml
with:
  wait-on: 'https://easyfis-ui-next.hiro-test.net/'
```

If Cypress is supposed to test the **local server on port 3030**, then `wait-on` should point to that local server instead, for example:

```yaml
with:
  start: npm start
  wait-on: 'http://localhost:3030'
```

using the actual protocol your development server provides.

So first decide whether the test target is the deployed URL or the locally started application. In either case, the immediate error is simply that `npm start` invokes a command that is not installed on the runner.

Please mark this answer as accepted if it helped, thank you.
