### DISCUSSION TITLE
Error when there are test failures

### DISCUSSION THREAD

**Discussion by jayakannanj** [cypress-io/cypress#30035] [CI setup]
Hello All,

Wanted to check if anyone has come across this before. I have cypress cloud configured to run in  CI. Whenever there are test failures I get the following error at the end of the test run hence I am unable to extract the dashboard URL to output in our internal report channel. Would appreciate your help. Thanks

`DevTools listening on ws://127.0.0.1:39763/devtools/browser/952626e9-232d-4c2a-94d7-31e7d9450489
[1912:0814/082611.971048:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: unknown error type: 
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
node:child_process:965
    throw err;
    ^

Error: Command failed: cypress run --record --key *** --browser chrome
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at Object.<anonymous> (/home/runner/work/ve3-platform-automation-tests/ve3-platform-automation-tests/cypress-cloud-exec.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49 {
  status: 10,
  signal: null,
  output: [ null, null, null ],
  pid: [17](https://github.com/mirriad/ve3-platform-automation-tests/actions/runs/10384071161/job/28750277533#step:5:18)19,
  stdout: null,
  stderr: null
}

Node.js v[18](https://github.com/mirriad/ve3-platform-automation-tests/actions/runs/10384071161/job/28750277533#step:5:19).20.4
Error: Process completed with exit code 1.`

**Comment by MikeMcC399** [comment]
- See issue https://github.com/cypress-io/cypress/issues/28061

You may get better results if you update Cypress.

**Reply by jayakannanj** [reply]
Thanks @MikeMcC399 , was already there and nothing helped so far.

**Reply by MikeMcC399** [reply]
It looks like you are running your tests in GitHub Actions. Is that correct? If so, could you post your workflow?

Is the file `cypress-cloud-exec.js` something you have supplied? What does it contain?

**Reply by jayakannanj** [reply]
Thanks for getting back @MikeMcC399, yes I do use github workflow. The js file contains the command to run Cypress tests. Please find both the files attached. Thanks
[CypressFiles.zip](https://github.com/user-attachments/files/16652067/CypressFiles.zip)

**Reply by MikeMcC399** [reply]
@jayakannanj

`build.yml` contains

```yml
      - name: Run Regression Tests
        id: cypress
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ vars.CYPRESS_CLOUD_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTOMATION_USER_PWD: ${{ secrets.AUTOMATION_USER_PWD }}
          https_proxy: "http://github:${{ secrets.TEST_MIRRIAD_PROXY_PASSWORD }}@${{ vars.TEST_MIRRIAD_PROXY_URL }}"
          http_proxy: "http://github:${{ secrets.TEST_MIRRIAD_PROXY_PASSWORD }}@${{ vars.TEST_MIRRIAD_PROXY_URL }}"
        run: |
          OUTPUT=$(CYPRESS_azureAsperaStorageKey=${{ secrets.AZURE_STORAGE_ASPERA_KEY_T03 }} CYPRESS_password=${{ secrets.AUTOMATION_USER_PWD }} CYPRESS_testEnv=t03 CYPRESS_tags=@new npm run cypress:execution-cloud)
          echo "Cypress output: $OUTPUT"
          URL=$(echo "$OUTPUT" | grep -o 'https://cloud.cypress.io/projects/[a-zA-Z0-9]*/runs/[0-9]*')
          echo "::set-output name=CYPRESS_DASHBOARD_URL::$URL"
```

`cypress-cloud-exec.js` contains:

```js
const execSync = require('child_process').execSync;
const key = process.env.CYPRESS_RECORD_KEY;
execSync(`cypress run --record --key ${key} --browser chrome`, { stdio: 'inherit' });
```

I don't see the definition of `cypress:execution-cloud` in your posted files, and I assume it is calling the JavaScript program. If so, this seems like a convoluted way of calling Cypress when there are simpler standard ways to do this. Of course I may not have fully understood your needs, but I suggest you consider standard alternatives:

## Alternatives

[cypress-io/github-action](https://github.com/cypress-io/github-action) runs Cypress from GitHub Actions. It returns `resultsUrl` from Cypress Cloud whether the run is successful or not. See https://github.com/cypress-io/github-action/blob/master/README.md#outputs.

If you prefer an API method to call Cypress from JavaScript, then you can use the [Cypress Module API](https://docs.cypress.io/guides/guides/module-api).
