### DISCUSSION TITLE
GitHub Action with Cypress Not Recognizing When to Start Tests

### DISCUSSION THREAD

**Discussion by br-schneider** [cypress-io/cypress#30385] [CI setup]
I'm working with a **Turborepo** setup that includes a **Next.js** application. We've successfully got our tests running locally by adding the following command to our `package.json`:

```json
"cypress:open": "cypress open"
```

Along with the default config file `cypress.config.ts`:

```typescript
import { defineConfig } from "cypress";

export default defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },
});
```

However, we're encountering an issue when trying to run Cypress tests in our GitHub Actions workflow. The server starts up in the action but then stalls out without Cypress knowing it needs to start running. We're unsure where to edit the action to have it know when to run or when the build is done.

Here's are two GitHub Action configuration variations we have tried:

```yaml
name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --workspaces

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install: false # Dependencies are already installed
          build: npm run build
          start: npm run start
          wait-on: http://0.0.0.0:3000
          record: true
          parallel: true
          working-directory: ./apps/web
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
```

```yaml
name: E2E on Chrome

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          project: .monorepo/apps/web
          browser: chrome
          node-version: "22"
          build: npm install
          start: npm run dev --workspace=web
          wait-on: "http://127.0.0.1:3000"
          wait-on-timeout: 300
        env:
          CLERK_SECRET_KEY: ${{secrets.CLERK_SECRET_KEY}}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}
```

**Issue:** The server starts up during the GitHub Action, but Cypress doesn't seem to recognize when it should start running the tests. It seems to stall, waiting indefinitely (we have tried localhost and 0.0.0.0:3000).

**Question:** Does anyone have ideas on how to modify the GitHub Action so that Cypress knows when to start running, or when the build is completed? Any guidance or suggestions would be greatly appreciated!

Thank you in advance for your help!
