### DISCUSSION TITLE
Tailwind classes not applied in Angular 19.2, Tailwind 4.0, Cypress 14

### DISCUSSION THREAD

**Discussion by denious** [cypress-io/cypress#31444] [Questions and Help] [answered]
Hi all,

Any ideas on what's missing to get Tailwind 4.0 classes working with Component Testing?
Styles are compiled and pulled, see screenshot below, and all **non-Tailwind** classes seem to work as expected.

### Tailwind classes not applied
![image](https://github.com/user-attachments/assets/958e5cb2-a739-47dd-946c-85b1899136fe)

### Stack
- Angular 19.2 w/ SCSS
- Tailwind 4.0 via PostCSS
- Cypress 14.2

### styles.scss
```css
@use "tailwindcss";
@use "primeicons/primeicons.css";

html {
  font-size: 14px;
  font-family: 'Inter', sans-serif;
  font-optical-sizing: auto;
  font-style: normal;
  background-color: var(--p-surface-50);
}

h1 {
  font-size: 2.286rem;
}

h2 {
  font-size: 1.714rem;
  font-weight: 700;
  margin: 1.5rem 0;
}

h3 {
  font-size: 1.429rem;
}
```
