### DISCUSSION TITLE
Cypress parallel runs without Dashboard service

### DISCUSSION THREAD

**Discussion by IrfanSyed-PSC** [cypress-io/cypress#9129] [Questions and Help]
Hello,

Just want to understand Cypress approach for executing tests in parallel. From the documentation it looks like dashboard is the only way to run Cypress in parallel, this beats the purpose of people using Cypress in production if they do not want to buy dashboard service. Considering that in fact, if one has to run Cypress in parallel across multiple machines or nodes then they have to build their own solution. Is that correct ? 

Also, just to clarify is Cypress never going to allow executing tests on multiple browsers in the same machine at the given time ?

**Comment by kinthaiofficial** [comment]
Running Cypress in parallel without the Dashboard is definitely doable — a few approaches depending on your CI setup:

**Option 1: Split by file count** (simple, works in any CI):
```yaml
# GitHub Actions matrix strategy
strategy:
  matrix:
    container: [1, 2, 3, 4]

steps:
  - name: Run Cypress
    run: |
      # Get all spec files, split into N chunks
      SPECS=$(find cypress/e2e -name "*.cy.ts" | sort)
      TOTAL=$(echo "$SPECS" | wc -l)
      CHUNK_SIZE=$(( ($TOTAL + ${{ matrix.container }} - 1) / 4 ))
      START=$(( (${{ matrix.container }} - 1) * $CHUNK_SIZE ))
      
      MY_SPECS=$(echo "$SPECS" | tail -n +$((START + 1)) | head -n $CHUNK_SIZE | tr '\n' ',')
      npx cypress run --spec "$MY_SPECS"
```

**Option 2: cypress-split plugin** (handles balancing automatically):
```bash
npm install -D cypress-split
```

```javascript
// cypress.config.ts
import { defineConfig } from 'cypress';
import cypressSplit from 'cypress-split';

export default defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      cypressSplit(on, config);
      return config;
    },
  },
});
```

```yaml
# Then in CI:
- run: npx cypress run
  env:
    SPLIT: 4
    SPLIT_INDEX: ${{ matrix.container }}
```

**Option 3: Currents.dev** (open-source Cypress dashboard alternative):
Drop-in replacement for Cypress Cloud with orchestration, historical data, flake detection.

For larger test suites (200+ specs), the balancing quality matters a lot — Option 2 or 3 is worth it. For smaller suites, simple file splitting works fine.

Are you splitting purely for speed, or also for isolation (preventing test interference)?
