### DISCUSSION TITLE
Tests succeed locally but fail in github-actions

### DISCUSSION THREAD

**Discussion by briansmith-fr** [cypress-io/cypress#9578] [Questions and Help]
I'm new to Cypress. I have tests that succeed locally (via npm cypress run); But in github-actions, they fail. Here's a snippet from the github-action log: 

>   2 failing
> 
>   1) Lists of assessments
>        Should have assessments:
>      AssertionError: Timed out retrying: Expected to find element: `.content-margin`, but never found it.
>       at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/integration/list_assessments.spec.js:1188:31)
> 

Here's my .github/workflows yml:
```
# This is a basic workflow to help you get started with Actions

name: Cypress Tests

on:
  push:
    branches:
      - "*"

  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          PORT: 3001
        with:
          start: npm start
          wait-on: http://localhost:3001/
          browser: chrome
          headless: true
```

I have an "always succeeds" test that does succeed in actions; the ones that actually do something, fail.

I've tried things like omitting browser, omitting headless, etc. No dice. Is there a checklist of things I should be looking for? Any guidance is much appreciated.

Regards,
Brian
