### ISSUE TITLE
Consistently unreliable Cypress runs in Gitlab CD/CI pipeline

### ISSUE THREAD

**Issue by ChaseBig** [cypress-io/cypress#14736]
How can I make cypress runs more consistently reliable? No matter what I do, I get random errors or flakes for no reason. No matter what I do, I can't get cypress test run jobs to consistently pass even though they pass consistantly on my local machine. This is absolutely killing my productivity and it's causing me to miss deadlines and hold the entire project up because Cypress is too volatile to run consistently. 

This is the latest error I keep getting. I run parallel jobs and every. single. time. at least one of the 5 cypress parallel jobs fails due to some stupid error. 

```
We detected that the Chromium Renderer process just crashed.
This is the equivalent to seeing the 'sad face' when Chrome dies.
This can happen for a number of different reasons:
- You wrote an endless loop and you must fix your own code
- There is a memory leak in Cypress (unlikely but possible)
- You are running Docker (there is an easy fix for this: see link below)
- You are running lots of tests on a memory intense application
- You are running in a memory starved VM environment
- There are problems with your GPU / GPU drivers
- There are browser bugs in Chromium
You can learn more including how to fix Docker here:
https://on.cypress.io/renderer-process-crashed
We detected that the Chromium Renderer process just crashed.
This is the equivalent to seeing the 'sad face' when Chrome dies.
This can happen for a number of different reasons:
- You wrote an endless loop and you must fix your own code
- There is a memory leak in Cypress (unlikely but possible)
- You are running Docker (there is an easy fix for this: see link below)
- You are running lots of tests on a memory intense application
- You are running in a memory starved VM environment
- There are problems with your GPU / GPU drivers
- There are browser bugs in Chromium
You can learn more including how to fix Docker here:
https://on.cypress.io/renderer-process-crashed
```

I have the CPU and Memory limits set to the highest possible settings in Gitlab, I have tried caching everything and nothing, I have literally tried everything I can think of but still cypress decides to be unreliable. I had this same issue two years ago when building out a cypress framework in CircleCi. Can you please work on making cypress more reliable? 

- Cypress: 6.3.0
- Latest Chrome and Electron versions
- cypress/included:6.3.0 image

Here is my `.gitlab-ci.yml` file:
```
stages:
  - test
  - deploy

image: cypress/included:6.3.0

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/.cache/Cypress"
  KUBERNETES_MEMORY_REQUEST: 2G
  KUBERNETES_MEMORY_LIMIT: 4G
  KUBERNETES_CPU_REQUEST: 2000m
  KUBERNETES_CPU_LIMIT: 2000m


cache: &global_cache
  key: "build-$CI_COMMIT_REF_SLUG"
  paths:
    - .npm
    - .cache/Cypress
    - node_modules
  policy: pull-push

build:
  stage: test
  cache:
    <<: *global_cache
    policy: push
  script:
    - npm ci
    - npm run build

lint and test:
  stage: test
  script:
    - npm ci
    - npm run lint
    - npm run test:unit

cypress-e2e:
  stage: test
  image: 
    name: cypress/included:6.3.0
    entrypoint: [""]
  parallel: 5
  script:
    - node --version
    - npm run cypress:cache-clear
    - npm install cypress
    - npm install
    - npm run cypress:cache-path
    - npm run cypress:verify
    - npm run test:e2e-ci
  allow_failure: true
```
