### ISSUE TITLE
GitHub Action exits unexpectedly with a SIGSEGV

### ISSUE THREAD

**Issue by tsposato** [cypress-io/cypress#15508]
### Current behavior

Randomly, our cypress tests run and exit due to a SIGSEGV without completing. The error does not occur on any specific test nor am I able to reproduce it locally or within the GitHub Action all the time. I haven't been able to pinpoint exactly what is occurring. I have enabled DEBUG logs within the github action and will update this ticket with logs when I have another failure.

```
Error: The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux (Ubuntu - 20.04)
Cypress Version: 6.6.0
    at /home/runner/work/harbour/harbour/frontend/node_modules/cypress/lib/errors.js:261:17
    at tryCatcher (/home/runner/work/harbour/harbour/frontend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/runner/work/harbour/harbour/frontend/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/runner/work/harbour/harbour/frontend/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/runner/work/harbour/harbour/frontend/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/runner/work/harbour/harbour/frontend/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/runner/work/harbour/harbour/frontend/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/home/runner/work/harbour/harbour/frontend/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/home/runner/work/harbour/harbour/frontend/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/home/runner/work/harbour/harbour/frontend/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/runner/work/harbour/harbour/frontend/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/runner/work/harbour/harbour/frontend/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/runner/work/harbour/harbour/frontend/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/home/runner/work/harbour/harbour/frontend/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/home/runner/work/harbour/harbour/frontend/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/home/runner/work/harbour/harbour/frontend/node_modules/bluebird/js/release/promise.js:604:18) {
  known: true
}
```

### Desired behavior

All the cypress tests run and pass or fail accordingly.

### Test code to reproduce

It doesn't fail due to any specific test so I'm not sure how much help this would be. The cypress action used is:
```
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ env.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          # We are testing locally here
          VUE_APP_API_URL: http://localhost:8080
        with:
          record: true
          working-directory: frontend
          start: npm run cy:serve
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 120
```

### Versions

I am using Cypress 6.6.0 and using ubuntu-latest image in GitHub actions.
