### ISSUE TITLE
A command line option to have `cypress run` exit with code 0 if it can find no specs

### ISSUE THREAD

**Issue by ebdrup** [cypress-io/cypress#15545]
### What would you like?

A command line option to have `cypress run` exit with code 0 if it can find no specs

### Why is this needed?

We are running a lot of specs from 3 different test runners (mocha, jest, cypress). 
On circleCI the easiest way to parallelise the tests on many servers is to have circleCI split all the tests from all test runners and just temporarily move the specs not supposed to be run on the individual server temporarily out of the test folder.
Unfortunately this results in cypress exiting with an error code of 1 if there by chance are no cypress tests left on one of the nodes (we're running 10 nodes in parallel), causing the whole build to fail when it shouldn't.
It would be great if you pass a parameter to cypress so that that no tests would just result in a normal exit code of 0.

**Comment by bahmutov** [comment]
Hi @ebdrup 

I think the simplest way to parallelize execution across N machines on CircleCI is to use our https://on.cypress.io/parallelization service via Cypress CircleCI Orb https://github.com/cypress-io/circleci-orb#parallel

```yml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      # first get the source code and install npm dependencies
      - cypress/install:
          # run a custom app build step
          build: 'npm run build'
      - cypress/run:
          # make sure app has been installed and built
          # before running tests across multiple machines
          # this avoids installing same dependencies 10 times
          requires:
            - cypress/install
          record: true # record results on Cypress Dashboard
          parallel: true # split all specs across machines
          parallelism: 4 # use 4 CircleCI machines to finish quickly
```

But if you want to do it yourself, you can certainly wrap Cypress with your logic by using its [NPM module API](), for examples see https://glebbahmutov.com/blog/wrap-cypress-using-npm/. I believe then you would get back the error "no specs found" and can ignore it.
