### ISSUE TITLE
Re-running failed workflow in GitHub Actions does not generate new Dashboard run

### ISSUE THREAD

**Issue by roberto-sobachi-cko** [cypress-io/cypress#15594]
Same issue as this one https://github.com/cypress-io/cypress/issues/6450#issue-564843575

After I re-run the workflow, the tests don't run and the job pass.

Config:

```
    - name: Cypress
        uses: cypress-io/github-action@v2.9.2
        with:
          install: true
          record: true
          browser: chrome
          headless: true
          wait-on: 'http://localhost:3000'
          config-file: cypress.json
          parallel: true
          group: E2E
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
```

<img width="1273" alt="Screenshot 2021-03-20 at 09 40 20" src="https://user-images.githubusercontent.com/73107709/111865682-4efcfb00-8960-11eb-925d-9bda5f732ca0.png">

### Versions

Cypress 6.8.0
Cypress Github Action v2.9.2

**Comment by jennifer-shehane** [comment]
There is a warning in the parallel section of the GH action docs explaining how to rerun GH action tests. https://github.com/cypress-io/github-action#parallel

>Warning ⚠️: Cypress actions use GITHUB_TOKEN to get the correct branch and the number of jobs run, making it possible to re-run without the need of pushing an empty commit. If you don't want to use the GITHUB_TOKEN you can still run your tests without problem with the only note that Cypress Dashboard API connects parallel jobs into a single logical run using GitHub commit SHA plus workflow name. If you attempt to re-run GitHub checks, the Dashboard thinks the run has already ended. In order to truly rerun parallel jobs, push an empty commit with git commit --allow-empty -m "re-run checks" && git push. As another work around you can generate and cache a custom build id, read Adding a unique build number to GitHub Actions

**Comment by roberto-sobachi-cko** [comment]
Thanks! I am still experiencing the same problem now even if I pass the Github token.
Just want to know if anything changed recently on Cypress or if having SSO auth for Github accounts might actually have an impact on this. 

```
    - name: Cypress
        uses: cypress-io/github-action@v2.9.2
        with:
          install: true
          record: true
          browser: chrome
          headless: true
          wait-on: 'http://localhost:3000'
          config-file: cypress.json
          parallel: true
          group: E2E
        env:
		  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
```
