### ISSUE TITLE
ssl- handshake error while doing https (api's) calls using cypress latest or lower versions

### ISSUE THREAD

**Issue by cypressAutomation07** [cypress-io/cypress#16016]
@jennifer-shehane 
While doing https api's calls  i am getting the below error
Error: write EPROTO 140507198243512:error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE:../../third_party/boringssl/src/ssl/tls_record.cc:594:SSL alert number 40

Please help how we can pass certificates in cypress to make apis call @

<img width="919" alt="Screen Shot 2021-04-15 at 10 57 08 AM" src="https://user-images.githubusercontent.com/82600205/114901038-06f3bb80-9dda-11eb-9356-30efc3656130.png">

if this is still an issues in cypress ,can we reopen below link
https://github.com/cypress-io/cypress/issues/2472

**Comment by sculpt0r** [comment]
I'm not sure if it is related, but I have a similar issue:
> Error: write EPROTO 1404[55](https://github.com/tbbg/engine/runs/7479245829?check_suite_focus=true#step:4:56)929026496:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

Could someone(@ explain where I should look what is wrong? This is only happening in GHA. Locally cypress works fine.
My setup GHA (`pnpm` with `cypress`):
```yml
name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        version: 7
        run_install: |
          - recursive: true
            args: [--frozen-lockfile]
    - name: Run Cypress tests
      uses: cypress-io/github-action@v4
      with:
        # we have already installed all dependencies above
        install: false
        build: |
          pnpm install --no-frozen-lockfile
        start: |
         pnpm --dir src/backend run run-dev
        command: pnpm run test:e2e
        wait-on: 'https://localhost:3000'
        wait-on-timeout: 220

```
`pnpm run test:e2e` in `package.json` is:
```
"test:e2e": "cypress run"
```
Cypress cfg:
```ts
import { defineConfig } from 'cypress';

export default defineConfig( {
	'fixturesFolder': 'tests/cypress/fixtures',
	'screenshotsFolder': 'tests/cypress/screenshots',
	'videosFolder': 'tests/cypress/videos',
	'downloadsFolder': 'tests/cypress/downloads',
	'supportFolder': 'tests/cypress/support',
	e2e: {
		'specPattern': 'tests/cypress/e2e/*.cy.{js,jsx,ts,tsx}',
		'supportFile':'tests/cypress/support/e2e.{js,jsx,ts,tsx}',
		setupNodeEvents( on, config ) {
			// implement node event listeners here
		},
		baseUrl: 'https://localhost:3000'
	},
} );
```

Additionally in GHA logs I get logs that my dev server is working, but somehow it is incorrect for cypress:
```
App started at port: 3000
App is using origin: { origin: [ 'http://127.0.0.1:8080', 'http://localhost:8080' ] }
https://localhost:3000 timed out on retry 38 of 5, elapsed 153214ms, limit 150000ms
Error: write EPROTO 1404[55](https://github.com/tbbg/engine/runs/7479245829?check_suite_focus=true#step:4:56)929026496:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```

If any additional information is needed - let me know.
