### ISSUE TITLE
Build Cypress docker image for simple CI

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#165]
Most CI allow using custom Docker image as base. It would be really cool to have official public Cypress docker image. We have built one, here is our docker file

```
FROM node:6
RUN apt-get update
RUN apt-get install libgtk2.0-0 libnotify4 libgconf2-4 libnss3 xvfb --yes
RUN npm set progress=false
RUN npm i -g cypress-cli
ARG CYPRESS_VERSION
ENV CYPRESS_VERSION ${CYPRESS_VERSION:-0.16.2}
RUN echo Cypress version to install $CYPRESS_VERSION
RUN cypress install
RUN cypress verify
```

One could use specific `cypress-cli` version inside if needed.

To build and tag the image, we use this script

``` sh
set e+x

# build image with everything needed to run Cypress
VERSION=0.16.2
LOCAL_NAME=front-end/cypress-ci
docker build --build-arg CYPRESS_VERSION=${VERSION} -t $LOCAL_NAME .

# tag and push the build to the registry
# https://docs.docker.com/mac/step_six/
IMAGE_ID=$(docker images -q $LOCAL_NAME)
NAME=<docker hub>/$LOCAL_NAME:$VERSION
docker tag $IMAGE_ID $NAME
docker push $NAME
```

We are pushing to internal Docker hub, but public is obviously the goal here.
Then a Gitlab CI runner just uses that image as the base

``` yaml
image: <docker hub>/front-end/cypress-ci:0.16.2
# caching node_modules folder
# https://about.gitlab.com/2016/03/01/gitlab-runner-with-docker/
cache:
  paths:
  - node_modules/
before_script:
  - cypress verify
stages:
  - test
e2e_test:
  stage: test
  script:
    - npm install
    - npm test
    - npm run build
    - cypress ci
```

We have spec file bundle build step, otherwise we could just do

``` yaml
e2e_test:
  stage: test
  script:
    - cypress ci
```
