### ISSUE TITLE
Importing Global CSS in Next.js with Webpack

### ISSUE THREAD

**Issue by smhmd** [cypress-io/cypress#16879]
### Current behavior

Following this [migration guide](https://docs.cypress.io/guides/references/migration-guide#Expanded-stylesheet-support), it is recommended to add (global) stylesheets to your tests. Nextjs's webpack wouldn't allow you to add them to your components anyway. But, when you add styles to a test, all tests (in `cypress open-ct`) hang on `Your tests are loading...`.

```javascript
import 'tailwindcss/tailwind.css' // or '../styles/index.css'

import { mount } from '@cypress/react'
import Button from '.'

describe('<Button />', () => {
  it('should mount', () => {
    mount(<Button />)
    cy.contains('click me')
  })
})
```

### Desired behavior

For the global styles to get applied.

### Test code to reproduce

```javascript
// cypress/plugins/index.ts
const injectNextDevServer = require('@cypress/react/plugins/next')

const pluginConfig: Cypress.PluginConfig = (on, config) => {
  if (config.testingType === 'component') {
    injectNextDevServer(on, config)
  }

  return config
}

module.exports = pluginConfig
```

### Versions

```yml
Cypress package version: 7.5.0
Cypress binary version: 7.5.0
Electron version: 12.0.0-beta.14
Bundled Node version: 14.15.1
OS: (Linux) 5.10.36-2-MANJARO
```
