### ISSUE TITLE
The Test Runner unexpectedly exited via a exit event with signal SIGTRAP

### ISSUE THREAD

**Issue by Osvaldo111** [cypress-io/cypress#17161]
### Current behavior

I used to run this container with Cypress on a different computer (Windows 10), now I change to a Mac Mini (chip M1), and I see the tests runner unexpectedly exits with the signal SIGTRAP. For this project, docker-compose is being used to build the service

Error: The Test Runner unexpectedly exited via a exit event with signal SIGTRAP
![image](https://user-images.githubusercontent.com/23143448/124001785-9866d880-d99a-11eb-9f87-84db6693d44b.png)

### Test code to reproduce

This is the setup used for the docker-compose file

```
  cypress:
    image: 'cypress/included:5.6.0'
    depends_on:
      - web
      - webpack
    environment:
      - CYPRESS_baseUrl=http://web:8000
    working_dir: /e2e
    volumes:
      - ./src/tests/e2e:/e2e
```

### Versions

Platform: linux (Debian - 10.2)
Cypress Version: 5.6.0
OS: macOS Big Sur. Chip Apple M1
