### ISSUE TITLE
--config-file flag isn't working when used in CI with docker:stable image

### ISSUE THREAD

**Issue by codinghedgehog-python** [cypress-io/cypress#17334]
### Current behavior

I'm running Cypress in GitLab CI with docker:stable as a base image and the `--config-file` throws an error when trying to specify alternative cypress.json file.
The flag works fine locally but error occurs within the CI.

pipeline I'm using:
```
image: docker:stable

services:
  - docker:19.03.5-dind

stages:
  - build

before_script:
  - export CRYPTOGRAPHY_DONT_BUILD_RUST=1
  - export REACT_APP_USERS_SERVICE_URL=http://127.0.0.1
  - export CYPRESS_VIDEO=false

compile:
  stage: build
  script:
    - apk add --no-cache py-pip python3-dev python3 bash libffi-dev openssl-dev gcc libc-dev make curl git npm
    - pip install docker-compose
    - bash test.sh

after_script:
  - docker-compose down
```
in `test.sh` I've got among other things:
```
docker pull cypress/included@7.7.0
docker run -v $PWD:/cypress -w /e2e --network tdd_default --config-file cypress-prod.json cypress/included:7.7.0
```

in the log output:
`unknown flag: --config-file`

Is there any solution to this ?

### Test code to reproduce

info provided above

### Cypress Version

7.7.0
