### ISSUE TITLE
Cucumber-Preprocessor tags are not working from the github actions integration

### ISSUE THREAD

**Issue by MatiDiez** [cypress-io/cypress#17736]
### Current behavior

I'm using cucumber preprocessor to write my tests in BDD and I have them all clasified with tags @Tag1 @Tag2 etc. 

I have cypress dashboard integrated, so I'm running all my tests like this: 
`npx cypress-tags run --env TAGS=@Regression --record --key <key>`
And it works perfectly fine, it only runs the scenarios that are tagged with regression. 

My Issue is that if I configure the same tags on my yaml file, all tests are executed without filtering the tags. 
Here how I added the tags:

```
 - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          tag: "@Regression"
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This is the log file from the job start. As you can see the tags are actually being recognized, but are just not filtering my .feature files: 
```
┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    7.7.0                                                                              │
  │ Browser:    Electron 89 (headless)                                                             │
  │ Specs:      25 found (automations/automation.feature, campaigns/ab_campaign.feature, campaigns │
  │             /regular_campaign.feature, campaigns/resend_campaign.feature, campaigns/rss_campai │
  │             gn.feature, dashboard/dashboard-stats.feature, emails/emails.feature, forms/embedd │
  │             ed.feature,...)                                                                    │
  │ Params:     Tag: @Regression, Group: false, Parallel: false                                       │
  │ Run URL:    https://dashboard.cypress.io/projects/<id>/runs/59                               │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

### Desired behavior

Only run the cucumber Scenarios that have the provided tags. 

### Test code to reproduce

```
 - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          tag: "@Regression"
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Cypress Version

7.7.0
