### ISSUE TITLE
ECONNREFUSED during boilerplate GitHub Action

### ISSUE THREAD

**Issue by alexmkio** [cypress-io/cypress#17755]
### Current behavior

I have 40 tests [here](https://github.com/alexmkio/can-i/tree/refactor/testing) that pass locally, but when I create a GitHub Action using boilerplate Cypress actions found [here](https://github.com/cypress-io/github-action#basic) (can confirm [here](https://github.com/alexmkio/can-i/blob/refactor/testing/.github/workflows/node.js.yml)) I get [the following errors](https://github.com/alexmkio/can-i/pull/36/checks?check_run_id=3344056715#step:3:103):

```
CypressError: `cy.visit()` failed trying to load:

http://localhost:3000/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:3000
```

What's going on here? I've tried troubleshooting by setting a base url with and without timeouts, but to no avail.

### Desired behavior

I would hope that the boilerplate code found in the Cypress documentation would sufficiently run passing tests, but I'm guessing my cy.visit('http://localhost:3000') is problematic in the GH actions workflow/server.

### Test code to reproduce

https://github.com/alexmkio/can-i/pull/36

### Cypress Version

8.3.0

**Comment by bahmutov** [comment]
You have never started the local server

**Comment by alexmkio** [comment]
@bahmutov do you have a suggestion on how to do that?

I have tried:
```
steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Cypress run
      uses: cypress-io/github-action@v2
```

and 
```
steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Start server
      uses: npm start

    - name: Cypress run
      uses: cypress-io/github-action@v2
```

and
```
steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      uses: npm install

    - name: Start server
      uses: npm start
      
    - name: Cypress run
      uses: cypress-io/github-action@v2
```

I'm kind of lost and any suggestions or documentation would help. Thank you.
