### ISSUE TITLE
Dashboard duplicate Tags

### ISSUE THREAD

**Issue by Griizz** [cypress-io/cypress#18016]
### Current behavior

While restructuring my GitLab-ci file, I encountered a Bug in the Cypress Dashboard. It shows duplicate tags for each run, when before they were merged together. I found a similar Ticket (#9375), but this is already closed.
![grafik](https://user-images.githubusercontent.com/31661551/132475111-c5db0a01-521e-4c6c-9ea4-fdd5dbe13184.png)
I think using Variables as tags triggered it.

### Desired behavior

Duplicate Tags should only be shown once. (Image: Run 10 and 11)

### Test code to reproduce

I'll embed most of my GitLab-ci file, but had to remove the build and publish job for customer privacy reasons. They should have no impact tho.

- CYPRESS_ENVIRONMENT = local
- CYPRESS_COUNTRY = de

```
image: ${NEXUS_REGISTRY}/eventim-light/docker-node:12

before_script:
  - npm ci

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
    - .cache/*
    - cache/Cypress
    - .npm
    - build

stages:
  - build
  - test
  - publish

.cypress:artifacts:
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
      - cypress/downloads/**/*.*
    expire_in: 1 day

test-desktop:
  stage: test
  parallel: 3
  script:
    - npm run dev & npx wait-on http://localhost:8080/status/
    - npx cypress run --env environment=${CYPRESS_ENVIRONMENT},country=${CYPRESS_COUNTRY} --spec "cypress/integration/UI/*" --record --parallel --tag "desktop,${CYPRESS_ENVIRONMENT},${CYPRESS_COUNTRY}" --group Desktop
  extends: .cypress:artifacts

test-mobile:
  stage: test
  parallel: 3
  script:
    - npm run dev & npx wait-on http://localhost:8080/status/
    - npx cypress run --env environment=${CYPRESS_ENVIRONMENT},country=${CYPRESS_COUNTRY},viewMode=mobile --spec "cypress/integration/UI/*" --record --parallel --tag "mobile,${CYPRESS_ENVIRONMENT},${CYPRESS_COUNTRY}" --group Mobile
  extends: .cypress:artifacts

test-backend:
  stage: test
  script:
    - npm run dev & npx wait-on http://localhost:8080/status/
    - npx cypress run --env environment=${CYPRESS_ENVIRONMENT},country=${CYPRESS_COUNTRY} --spec "cypress/integration/Backend/*" --record --tag "backend,${CYPRESS_ENVIRONMENT},${CYPRESS_COUNTRY}" --group Backend
  extends: .cypress:artifacts

```

### Cypress Version

8.2.0
