### ISSUE TITLE
Dashboard grouped runs only show tags of one.

### ISSUE THREAD

**Issue by Griizz** [cypress-io/cypress#18040]
### Current behavior

After #18016 being closed the Behaviour still does not fit what I would expect. I'm Starting three runs that are Grouped together. They have the following tags:
- local,at,mobile
- local,at,desktop
- local,at,backend

The Dashboard only shows the tags of one run. I guess it depends on which ran first.

![grafik](https://user-images.githubusercontent.com/31661551/132678302-770e0669-5368-46fc-a39d-46d22f2fd2bf.png)

I did verify that all 3 Jobs ran.

Based on the duplicate Tags Bug #18016 it must be possible to add tags when a new run starts. Is this a Bug or a missing Feature?

### Desired behavior

I would expect the Dashboard to show the tags.
- local
- at
- mobile
- desktop
- backend

### Test code to reproduce

I'll embed most of my GitLab-ci file, but had to remove the build and publish job for customer privacy reasons. They should have no impact tho.

- CYPRESS_ENVIRONMENT = local
- CYPRESS_COUNTRY = at

```
image: ${NEXUS_REGISTRY}/eventim-light/docker-node:12

before_script:
  - npm ci

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
    - .cache/*
    - cache/Cypress
    - .npm
    - build

stages:
  - build
  - test
  - publish

.cypress:artifacts:
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
      - cypress/downloads/**/*.*
    expire_in: 1 day

test-desktop:
  stage: test
  parallel: 3
  script:
    - npm run dev & npx wait-on http://localhost:8080/status/
    - npx cypress run --env environment=${CYPRESS_ENVIRONMENT},country=${CYPRESS_COUNTRY} --spec "cypress/integration/UI/*" --record --parallel --tag "desktop,${CYPRESS_ENVIRONMENT},${CYPRESS_COUNTRY}" --group Desktop
  extends: .cypress:artifacts

test-mobile:
  stage: test
  parallel: 3
  script:
    - npm run dev & npx wait-on http://localhost:8080/status/
    - npx cypress run --env environment=${CYPRESS_ENVIRONMENT},country=${CYPRESS_COUNTRY},viewMode=mobile --spec "cypress/integration/UI/*" --record --parallel --tag "mobile,${CYPRESS_ENVIRONMENT},${CYPRESS_COUNTRY}" --group Mobile
  extends: .cypress:artifacts

test-backend:
  stage: test
  script:
    - npm run dev & npx wait-on http://localhost:8080/status/
    - npx cypress run --env environment=${CYPRESS_ENVIRONMENT},country=${CYPRESS_COUNTRY} --spec "cypress/integration/Backend/*" --record --tag "backend,${CYPRESS_ENVIRONMENT},${CYPRESS_COUNTRY}" --group Backend
  extends: .cypress:artifacts

```

### Cypress Version

8.2.0
