### ISSUE TITLE
CI shows as "Not available" when running tests from Azure Devops

### ISSUE THREAD

**Issue by ivan-xue-prospa** [cypress-io/cypress#18056]
### Current behavior

We are using docker-compose to run tests from Azure Devops pipeline, but CI in Cypress Dashboard always showns as "Not available"

![Screenshot at Sep 10 14-45-57](https://user-images.githubusercontent.com/54783155/132801112-51c63363-dc47-4360-ba15-85292cb9abf0.png)

### Test code to reproduce

docker-compose.yml

```
version: '3'
services:
  e2e:
    image: "cypress/included:8.2.0"
    entrypoint: [""]
    working_dir: /app
    command: bash -c "export COMMIT_INFO_BRANCH='${COMMIT_INFO_BRANCH}' && export COMMIT_INFO_AUTHOR='${COMMIT_INFO_AUTHOR}' && export COMMIT_INFO_MESSAGE='${COMMIT_INFO_MESSAGE}' && npm run cy:install && npm run cy:run -- --browser ${BROWSER} --record --key ${RECORDKEY} --parallel --ci-build-id ${BUILDID} --tag ${TAG} --group ${GROUP}"
    volumes:
      - .:/app
```

### Cypress Version

8.3.0
