### ISSUE TITLE
`viewport` not getting recognized in CI

### ISSUE THREAD

**Issue by silasjoisten** [cypress-io/cypress#18230]
### Current behavior

packages:
```
"cypress": "^8.4.1",
"@cypress/vite-dev-server": "^2.1.0",
"@cypress/vue": "^2.2.3",
"@testing-library/cypress": "^8.0.1",
```

node version: 14.17.6

We setup Cypress Testing for e2e. Locally the `viewportHeight` and `viewportWidth` in the cypress.json is getting recognized and it works like a charm. => Tests are passing. 

When we push to Github our GithubAction will execute `yarn test:e2e` which is described in the `package.json` as the following:
```bash
yarn build && concurrently --success=first -k "yarn serve" "cypress run --headless --config-file=cypress.json"
```

The weird behavior is that sometimes the tests are passing (probably the viewport option is getting recognized) and sometimes not. The test actually logs in a user and clicks a logout button in the sidebar navigation which is not visible in Mobile. (collapsed sidebar)

We tried a lot and also the solutions described in: https://github.com/cypress-io/cypress/issues/2102 but it did not work as well.

The behavior is flacky sometimes it fails sometimes it works.

<img width="1408" alt="CleanShot 2021-09-24 at 10 32 12@2x" src="https://user-images.githubusercontent.com/10114981/134643892-7c640aa3-e966-4159-a282-f85c6e238685.png">

First commit (passing) from screenshot above:
<img width="1783" alt="CleanShot 2021-09-24 at 10 33 20@2x" src="https://user-images.githubusercontent.com/10114981/134644009-ede1b402-7788-4bf7-bc0c-b25af99d1635.png">

Second commit (failing) from screenshot above:
<img width="1773" alt="CleanShot 2021-09-24 at 10 34 04@2x" src="https://user-images.githubusercontent.com/10114981/134644147-e192338d-17e0-482f-a433-4952e00ee9d5.png">

The Test which is failing caused by the invisible Logout Button collapsed in the sidebar.
<img width="1395" alt="CleanShot 2021-09-24 at 10 34 40@2x" src="https://user-images.githubusercontent.com/10114981/134644291-354bc271-80c1-4e77-8a1c-71f4cb0421b2.png">

The code from the test which fails:
```js
  it('User can log out', () => {
    cy.login()

    cy.get('button')
      .contains('Ausloggen')
      .click()

    cy.location().should((loc) => {
      expect(loc.pathname).to.eq('/login')
    })
  })

```

### Test code to reproduce

Create a Github Action with the following:

```yaml
# ...
    tests:
        name: "Tests"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                node-version:
                    - "14.17.6"

        steps:
            -   if: github.actor != 'dependabot[bot]'
                name: "Checkout"
                uses: "actions/checkout@v2.3.4"
                with:
                  ref: "${{ github.head_ref }}"
                  token: "${{ secrets.DATANA_BOT_TOKEN }}"

            -   if: github.actor == 'dependabot[bot]'
                name: "Checkout"
                uses: "actions/checkout@v2.3.4"
                with:
                    ref: "${{ github.head_ref }}"

            -
                name: "Install Node.js"
                uses: "actions/setup-node@v2.4.0"
                with:
                    node-version: "${{ matrix.node-version }}"

            -
                name: "Determine yarn cache directory"
                id: "determine-yarn-cache-directory"
                run: "echo \"::set-output name=directory::$(yarn cache dir)\""

            -
                name: "Cache dependencies installed with yarn"
                uses: "actions/cache@v2.1.6"
                with:
                    path: "${{ steps.determine-yarn-cache-directory.outputs.directory }}"
                    key: "node-${{ matrix.node-version }}-yarn-${{ hashFiles('frontend/yarn.lock') }}"
                    restore-keys: "node-${{ matrix.node-version }}-yarn-"

            -
                name: "Install dependencies with yarn"
                run: "yarn install"

            -
                name: "Cypress End to end tests"
                run: "yarn test:e2e"

```

package.json
```json
{
  "name": "frontend-datapool",
  "license": "UNLICENSED",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite --mode dev",
    "build": "vite build",
    "serve": "vite preview",
    "api": "json-server --watch db.json --port 3004 --delay 450",
    "lint:script": "eslint \"src/**/*.{ts,vue}\"",
    "lint:tsc": "vue-tsc --noEmit",
    "lint": "concurrently 'yarn lint:tsc' 'yarn lint:script'",
    "test:e2e": "yarn build && concurrently --success=first -k \"yarn serve\" \"cypress run --headless --config-file=cypress.json\"",
    "cypress:open": "./node_modules/.bin/cypress open"
  },
  "dependencies": {
    "@headlessui/vue": "^1.4.0",
    "@heroicons/vue": "^1.0.4",
    "@intlify/vite-plugin-vue-i18n": "^2.4.0",
    "@tailwindcss/forms": "^0.3.3",
    "axios": "^0.21.1",
    "vue": "^3.2.6",
    "vue-debounce": "^3.0.1",
    "vue-i18n": "^9.1.7",
    "vue-router": "4",
    "vuex": "^4.0.2"
  },
  "devDependencies": {
    "@cypress/vite-dev-server": "^2.1.0",
    "@cypress/vue": "^2.2.3",
    "@testing-library/cypress": "^8.0.1",
    "@types/node": "^16.7.6",
    "@typescript-eslint/eslint-plugin": "^4.31.1",
    "@typescript-eslint/parser": "^4.31.1",
    "@vitejs/plugin-vue": "^1.6.1",
    "@vue/compiler-sfc": "^3.2.6",
    "autoprefixer": "^10.3.1",
    "concurrently": "^6.2.1",
    "cypress": "^8.4.1",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-config-standard-with-typescript": "^20.0.0",
    "eslint-plugin-cypress": "^2.12.1",
    "eslint-plugin-import": "^2.24.0",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.3.1",
    "eslint-plugin-vue": "^7.16.0",
    "json-server": "^0.16.3",
    "postcss": "^8.3.6",
    "tailwindcss": "^2.2.7",
    "typescript": "^4.3.2",
    "vite": "^2.5.4",
    "vue-tsc": "^0.2.2"
  }
}
```

cypress.json
```json
{
  "testFiles": "**/*.spec.ts",
  "componentFolder": "src",
  "video":false,
  "baseUrl": "http://127.0.0.1:5000",
  "viewportWidth": 1440,
  "viewportHeight": 900
}
```

### Cypress Version

8.4.1
