### ISSUE TITLE
Cypress open doesn't work on docker image

### ISSUE THREAD

**Issue by casahugo** [cypress-io/cypress#18449]
### Current behavior

Hello, I am not the only one having this problem.
Unable to launch the open command from the docker image provided by your services.

### Test code to reproduce

docker-compose.yml
```
version: '3.7'
services:
    nodejs:
        working_dir: /app
        image: cypress/browsers:node12.18.3-chrome87-ff82
        volumes:
            - ./:/app/
            - ~/.cache:/root/.cache
        command: bash -c "npm install"
```
Run this command `docker-compose run nodejs node_modules/.bin/cypress open`
Results:
```
[18:1012/092745.043905:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[18:1012/092745.045103:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
[18:1012/092745.045149:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
[197:1012/092745.095382:ERROR:gl_implementation.cc(403)] Failed to load /root/.cache/Cypress/8.6.0/Cypress/swiftshader/libGLESv2.so: /root/.cache/Cypress/8.6.0/Cypress/swiftshader/libGLESv2.so: cannot open shared object file: Permission denied
[197:1012/092745.096202:ERROR:viz_main_impl.cc(162)] Exiting GPU process due to errors during initialization
[204:1012/092745.101843:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled
[18:1012/092745.214067:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
[18:1012/092745.226874:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon

```

### Cypress Version

8.6.0
