### ISSUE TITLE
cy.visit() failed trying to load

### ISSUE THREAD

**Issue by benmotif** [cypress-io/cypress#18657]
### Current behavior

I am running an integration test for Cypress which works fine locally but fails when I run it in Gitlab. The error I am receiving is while using the cy.visit() command that results in the following error:

```
CypressError: `cy.visit()` failed trying to load:
http://localhost:3000/ The response we received from your web server
was:
  404: Not Found
Configuration
```
I launch the test with the following commands:

```
tests:
  image: cypress/browsers:node14.15.0-chrome86-ff82
  stage: tests
  script:
    - npm ci
    - npm run test:ci
```
The commands look like this in my package.json:
```
  "scripts": {
    "start:ci": "serve dist --no-clipboard --listen ${PORT:-3000}",
    "build": "webpack --config webpack.prod.js",
    "test": "cross-env NODE_ENV=test && npm run test:jest && npm run test:cypress",
    "test:ci": "start-server-and-test start:ci http://localhost:3000 test",
    "test:cypress": "cypress run --headless",
    "test:jest": "jest",
  },
```

I have looked into the error and found [this](https://github.com/cypress-io/cypress/issues/3245) thread which helped me understand the issue a little bit. I then tried adding the following config to my cypress.json file:

```
{
  "baseUrl": "http://localhost:3000"
}
```

along with the following plugins index file:

```
require('dotenv').config();

module.exports = (on, config) => {
  const cypressEnvVars = Object.keys(process.env).filter((key) => key.startsWith('CYPRESS_') && key !== 'CYPRESS_INTERNAL_ENV');

  cypressEnvVars.forEach((v) => {
    config.env[v] = process.env[v];
  });

  on('before:browser:launch', (browser, launchOptions) => {
    if (browser.name === 'chrome') {
      launchOptions.args.push('--proxy-bypass-list=<-loopback>');
      return launchOptions;
    }
  });

  on('task', {
    log(message) {
      console.log(message);
      return null;
    },
  });

  return config;
};
```
the  `on('before:browser:launch'...` part of the plugins index file was recommended as a potential fix to someone else having this issue but it has not helped me. 

Finally here is my gitlab-ci.yml config file:

```
variables:
  API_BASE_URL: https://myapp.local.mysite.io/api
  CYPRESS_API_BASE_URL: https://myapp.local.mysite.io/api
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

cache:
  paths:
    - node_modules/
    - cache/Cypress

stages:
  - install
  - build
  - tests

install:
  image: cypress/browsers:node14.15.0-chrome86-ff82
  stage: install
  cache:
    key: 'e2eDeps'
    paths:
      - node_modules/
      - cache/Cypress/
  script:
    - npm ci

build:
  stage: build
  dependencies:
    - install
  script:
    - npm run build
  artifacts:
    expire_in: 1 days
    when: on_success

tests:
  image: cypress/browsers:node14.15.0-chrome86-ff82
  stage: tests
  script:
    - npm ci
    - npm run test:ci

```

### Desired behavior

I would expect that it does not return a 404

### Test code to reproduce

gitlab-ci.yml:

```
variables:
  API_BASE_URL: https://myapp.local.mysite.io/api
  CYPRESS_API_BASE_URL: https://myapp.local.mysite.io/api
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

cache:
  paths:
    - node_modules/
    - cache/Cypress

stages:
  - install
  - build
  - tests

install:
  image: cypress/browsers:node14.15.0-chrome86-ff82
  stage: install
  cache:
    key: 'e2eDeps'
    paths:
      - node_modules/
      - cache/Cypress/
  script:
    - npm ci

build:
  stage: build
  dependencies:
    - install
  script:
    - npm run build
  artifacts:
    expire_in: 1 days
    when: on_success

tests:
  image: cypress/browsers:node14.15.0-chrome86-ff82
  stage: tests
  script:
    - npm ci
    - npm run test:ci

```

package.json:

```
  "scripts": {
    "start:ci": "serve dist --no-clipboard --listen ${PORT:-3000}",
    "build": "webpack --config webpack.prod.js",
    "test": "cross-env NODE_ENV=test && npm run test:jest && npm run test:cypress",
    "test:ci": "start-server-and-test start:ci http://localhost:3000 test",
    "test:cypress": "cypress run --headless",
    "test:jest": "jest",
  },
```

plugins index file:

```
require('dotenv').config();

module.exports = (on, config) => {
  const cypressEnvVars = Object.keys(process.env).filter((key) => key.startsWith('CYPRESS_') && key !== 'CYPRESS_INTERNAL_ENV');

  cypressEnvVars.forEach((v) => {
    config.env[v] = process.env[v];
  });

  on('before:browser:launch', (browser, launchOptions) => {
    if (browser.name === 'chrome') {
      launchOptions.args.push('--proxy-bypass-list=<-loopback>');
      return launchOptions;
    }
  });

  on('task', {
    log(message) {
      console.log(message);
      return null;
    },
  });

  return config;
};
```

test:

```
describe('Code entry page - API responses are managed correctly', () => {
  beforeEach(() => {
    cy.visit('/');
  });
  it('Gets a valid response when unused code and redirects accordingly', () => {
    expect(true).equal(true)
  })
})
```

### Cypress Version

8.6.0
