### ISSUE TITLE
Azure DevOps Error: Cannot find module 'cypress-mochawesome-reporter/lib' 

### ISSUE THREAD

**Issue by msdcanderson** [cypress-io/cypress#18982]
### Current behavior

Hi all,

I would appreciate any help you can provide

Error message: Error: Cannot find module 'cypress-mochawesome-reporter/lib'

I have a problem when I deploy Cypress to an Azure DevOps pipeline (the tests and code work fine locally), I am following these instructions to create the build pipeline: [https://dzone.com/articles/cypress-azuredevops-pipeline](https://dzone.com/articles/cypress-azuredevops-pipeline)

When I run it, I get the error:

![image](https://user-images.githubusercontent.com/20575321/142463348-27d4e93b-165f-42a0-96f2-663d56018d1a.png)

I have tried reinstalling Cypress and the reporter modules, but this error persists.

Many thanks for any help

### Desired behavior

In this situation, Cypress should install completely then run the tests

### Test code to reproduce

Below is the failed DevOps task:

![image](https://user-images.githubusercontent.com/20575321/142463406-cc91ec9c-e47b-4c98-a3da-bb00e91279db.png)

Below is my plugin file, it requires the 'cypress-mochawesome-reporter/lib' module

![image](https://user-images.githubusercontent.com/20575321/142463524-e44823bd-6ba7-4b7e-ab30-453bf159b467.png)

The module is in the Git repository:

![image](https://user-images.githubusercontent.com/20575321/142463661-c1454da6-37b9-465b-bb0e-c0057dca6a8a.png)

Below is my cypress version info:

![image](https://user-images.githubusercontent.com/20575321/142463720-2b9143ab-571f-4a0d-936e-f65631903093.png)

### Cypress Version

9.0.0

**Comment by chrisbreiding** [comment]
It seems that, on Azure, `cypress-mochawesome-reporter` is either not installed or not installed where Node expects it to be. So then the question, of course, is why?

- The screenshot of the file system: is that your local system or the Azure system?
- Is `cypress-mochawesome-reporter` in your package.json? Or do you have `node_modules` committed to the repo?

**Comment by edinc** [comment]
Hi,

I am having a similar issue, although when trying to run cypress tests using the official Docker image inside an Azure DevOps Pipeline. On my local machine everything works fine, but on Azure DevOps I'm getting `Error: Cannot find module 'cypress-mochawesome-reporter/lib'`.

Pipeline error log:
```
The plugins file is missing or invalid.

Your `pluginsFile` is set to `/e2e/cypress/plugins/index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.

 Error: Cannot find module 'cypress-mochawesome-reporter/lib'
Require stack:
- /e2e/cypress/plugins/index.js
- /root/.cache/Cypress/9.3.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js
- /root/.cache/Cypress/9.3.1/Cypress/resources/app/packages/server/lib/plugins/child/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/e2e/cypress/plugins/index.js:24:41)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at runPlugins (/root/.cache/Cypress/9.3.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:182:15)
    at Object.<anonymous> (/root/.cache/Cypress/9.3.1/Cypress/resources/app/packages/server/lib/plugins/child/index.js:8:25)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
##[error]The process '/usr/bin/bash' failed with exit code 1
##[error]Bash failed with error: The process '/usr/bin/bash' failed with exit code 1
Finishing: Run cypress tests inside Docker
```
Here is my `package.json`:
```
{
  "name": "cypressDemo",
  "version": "1.0.0",
  "description": "cypress demo code",
  "main": "index.js",
  "author": "Edin Cenanovic",
  "license": "MIT",
  "devDependencies": {
    "cypress": "^9.2.1"
  },
  "dependencies": {
    "cypress-mochawesome-reporter": "^2.3.0",
    "cypress-multi-reporters": "^1.5.0",
    "junit-report-merger": "^3.0.5",
    "mocha": "^9.1.4",
    "mocha-junit-reporter": "^2.0.2"
  }
}
```
Here is the `/cypress/plugins/index.js` file:
```
/// <reference types="cypress" />
// ***********************************************************
// This example plugins/index.js can be used to load plugins
//
// You can change the location of this file or turn off loading
// the plugins file with the 'pluginsFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/plugins-guide
// ***********************************************************

// This function is called when a project is opened or re-opened (e.g. due to
// the project's config changing)

/**
 * @type {Cypress.PluginConfig}
 */
// eslint-disable-next-line no-unused-vars
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
}

const { beforeRunHook, afterRunHook } = require('cypress-mochawesome-reporter/lib');
const exec = require('child_process').execSync;
module.exports = (on) => {
  on('before:run', async (details) => {
    console.log('override before:run');
    await beforeRunHook(details);
  });
  on('after:run', async () => {
    console.log('override after:run');
    await afterRunHook();
  });
};
```
My `azure-pipelines.yaml` file:
```
jobs:
  # Example job that runs end-to-end tests using Cypress test runner
  #   https://www.cypress.io/

  # Job names can contain alphanumeric characters and '_', cannot start with a number
  - job: Cypress_e2e_tests
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: ShellScript@2
        displayName: 'Run cypress tests inside Docker'
        inputs:
          scriptPath: ./cy-run.sh

      - task: PublishTestResults@2
        displayName: 'Publish test results'
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '*.xml'
          searchFolder: '$(System.DefaultWorkingDirectory)/cypress/reports/junit'
          mergeTestResults: true
          testRunTitle: 'Cypress tests'
```
The content of the `cy-run.sh` file:
```
#!/usr/bin/env bash
echo "Running Cypress e2e tests headlessly without copying files"

# explanation of the "docker run" command line arguments
#
#  -it          = interactive terminal
#  -v $PWD:/e2e = map current folder to /e2e inside the container
#  -w /e2e      = set working directy to /e2e
#  $@           = pass any arguments to this script to the Cypress command
#                 like "./cy-run.sh --record"
#
# Docker image "cypress/included:3.2.0" has its entrypoint
# set to "cypress run" by default
docker run -v $PWD:/e2e -w /e2e cypress/included:9.2.1 $@

# if you need to restrict amount of memory or CPU power the
# container can use, see
# https://docs.docker.com/config/containers/resource_constraints/
# restrict total memory
# --memory=600m --memory-swap=600m
# restrict CPU share
# --cpus=0.3
```

On a side note, running this without Docker on a different Pipeline works without any issues. For example:
```
jobs:
  # Example job that runs end-to-end tests using Cypress test runner
  #   https://www.cypress.io/

  # Job names can contain alphanumeric characters and '_', cannot start with a number
  - job: Cypress_e2e_tests
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
          displayName: 'Install Node.js'

      - script: |
            yarn install --verbose
        displayName: 'Install dependencies'

      - script: |
          ./node_modules/.bin/cypress run --browser chrome
        displayName: 'Run cypress tests'
        continueOnError: true

      - task: PublishTestResults@2
        displayName: 'Publish test results'
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '*.xml'
          searchFolder: '$(System.DefaultWorkingDirectory)/cypress/reports/junit'
          mergeTestResults: true
          testRunTitle: 'Cypress tests'
```

**Cypress Version**
9.2.1

Any hints why this is happening only inside a Docker container on Azure DevOps?
Thanks!
