### ISSUE TITLE
Can I run my CI project pipeline multiple times in cypress dashboard?

### ISSUE THREAD

**Issue by Furong-Huang** [cypress-io/cypress#19253]
### What would you like?

I have run one time and finished my CI project running in Auzre Devops as below screenshot. Everytime I need to create a new project with a new project ID, then I can trigger CI project pipeline running again. It is not convenient by using Cypress Dashboard.
When CI project pipeline has finished first time running in Azure Devops, then if triggering the second time, it will show below screenshot as Run finished. Actually I would like to run all test cases again in pipeline and new build in Cypress dashboard.

![144510463-c6a79fdf-6ae6-4c9d-b80d-976ae9af7179](https://user-images.githubusercontent.com/9040308/144725976-869b026f-e1f9-448f-b30d-eb3a8ec4f368.png)

And my yml file as below 
```
# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none
pool:
    vmImage: 'windows-2019'
stages:
- stage: A
  jobs:
   - job: Restore_Database
     steps:
         - script: "npm install"
         - powershell: ./testrunner.ps1 -restore $true -password $(PASSWORD)
- stage: B
  dependsOn: A
  jobs:
  - job: Run_Tests_In_Parallel
    steps:
      - script: "npm install"
      - script: "npx cypress run --headless --record --key $CY_KEY --browser chrome --spec ./integration/* --parallel --ci-build-id $Build.BuildNumber"
    strategy:
     parallel: 2
```
When I run locally for the project, it will always see the new build running on Cypress Dashboard.
![image](https://user-images.githubusercontent.com/9040308/144725965-fce3b2c3-313c-4744-a1bc-e21e0bb8a6f7.png)

### Why is this needed?

Can I run my CI project pipeline multiple times in cypress dashboard?
I am not sure the APIs between Azure devops and Cypress Dashboard.
