### ISSUE TITLE
Cypress verify fails with permission error for Github Actions on Linux

### ISSUE THREAD

**Issue by mel-OR** [cypress-io/cypress#19981]
### Current behavior

When running our Github action, the job fails on the cypress verify step:
```
/usr/local/bin/npx cypress cache list
┌─────────┬──────────────┐
│ version │ last used    │
├─────────┼──────────────┤
│ 8.7.0   │ 3 months ago │
└─────────┴──────────────┘
/usr/local/bin/npx cypress verify
[STARTED] Task without title.
[FAILED] EACCES: permission denied, open '/github/home/.cache/Cypress/8.7.0/binary_state.json'
An unexpected error occurred while verifying the Cypress executable.
```

### Desired behavior

Complete the verification within an accessible folder and update the cache as necessary.

### Test code to reproduce

Snippet of the action:
```
jobs:
  ui-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.5.0-chrome94-ff93
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v2
        with:
          # we have already installed all dependencies above
          install: true
          browser: chrome
```

### Cypress Version

8.7.0, 9.3.1
