### ISSUE TITLE
Testing via Github Actions -- Cypress runner takes 20x longer to run than local and Videos aren't watchable

### ISSUE THREAD

**Issue by josh803316** [cypress-io/cypress#20468]
### Current behavior

**Description:** 
We are trying to run Cypress and Percy together via Github actions to test our app during development for ([Sketchy](https://sketchy.com))

The test runs are taking a really long time (~20 mins) when our expectations are that they should be done in less than 4 and perhaps 1 if we ran in parallel. We are also noticing that the video recordings are not watchable (they don't show the recorded flow of the test they just show a couple snapshot states).  We have experimented with changing the compression levels of the videos to no avail.

Here is a link to one of the test runs where it was slow:
https://dashboard.cypress.io/projects/pfwmze/runs/111/specs

I also commented [here](https://github.com/cypress-io/cypress/issues/16884#issuecomment-1045210849):
and
[here](https://github.com/cypress-io/cypress/issues/16884#issuecomment-1045937281)

The major issue, outside of build time, is that Github actions only offers a certain amount of mins per month in non-enterprise scenarios and these tests are massively eating into those mins and our build times even though they finish locally in under a min.

I've attached a photo showing how the specs themselves are running quickly but the total test run is very long.

![Cypress_Test_Run_Long_Time](https://user-images.githubusercontent.com/206909/156627177-7647d384-918c-4879-9cad-89c85d0d0fe3.png)

### Desired behavior

The tests run as fast in CI (headless) as they do locally and perhaps even faster if we run them in parallel.

### Test code to reproduce

Link to part of my config is [here](https://github.com/cypress-io/cypress/issues/16884#issuecomment-1045210849):

This shows what my memory/cpu looks like during test run:
https://github.com/cypress-io/cypress/issues/16884#issuecomment-1045937281

Here is my config file setting:
```javascript
{
  "projectId": "xxxxx",
  "defaultCommandTimeout": 10000,
  "chromeWebSecurity": false,
  "videoCompression": false,
  "viewportWidth": 1440,
  "viewportHeight": 900,
  "baseUrl": "http://dashboard.sketchy-premerge.com",
  "supportFile": "cypress/support/index.js",
  "experimentalSessionSupport": true
}
```

Here is how it's being run in CI:
```yaml
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          install: false
          config-file: 'cypress/cypress.${{ needs.deploy.outputs.env_check_env_name }}.json'
          wait-on: 'https://${{ needs.deploy.outputs.env_check_sanitized_url }}.sketchy-${{ needs.deploy.outputs.env_check_env_name }}.com'
          record: true
          headless: true
          parallel: false
          command-prefix: 'percy exec -- npx'
          tag: ${{ github.event_name }}
```

### Cypress Version

9.5.1
