### ISSUE TITLE
cypress open and cypress run result is not same

### ISSUE THREAD

**Issue by shijiatongxue** [cypress-io/cypress#20878]
### Current behavior

When i use `cypress open` and run all test cases, all cases passed.

![image](https://user-images.githubusercontent.com/26477537/161192397-826d55af-7b91-4878-be73-78e4f94bd572.png)

But if i use `cypress run`, some of it will not pass.

![image](https://user-images.githubusercontent.com/26477537/161193141-6b5a0708-0d8e-488a-aa57-a8f9cba3e014.png)

test with `cypress open`, everything is ok

![image](https://user-images.githubusercontent.com/26477537/161193293-71aaa2e3-525d-432d-8cd3-01ce0df81898.png)

![image](https://user-images.githubusercontent.com/26477537/161193327-546ae376-4d14-4dfb-9760-ddb976eb386e.png)

### Desired behavior

`cypress open` and `cypress run` command get the same test result.

### Test code to reproduce

# Clone code
```bash
git clone https://github.com/DouyinFE/semi-design
yarn bootstrap
yarn start
```

# Cypress open

```bash
yarn test:cy
```

# Cypress run

```bash
./node_modules/.bin/cypress run
```

### Cypress Version

9.5.2

**Comment by CaiqueCoelho** [comment]
@shijiatongxue I think this is not necessarily a problem. Because with Cypress open I saw you are running the tests with Chrome browser, but with Cypress run the default is Electron. Can you send us what is the error message you are getting in these failed tests using cypress run?

**Comment by shijiatongxue** [comment]
> @shijiatongxue I think this is not necessarily a problem. Because with Cypress open I saw you are running the tests with Chrome browser, but with Cypress run the default is Electron. Can you send us what is the error message you are getting in these failed tests using cypress run?

Thanks, I will add more information later.

**Comment by shijiatongxue** [comment]
> @shijiatongxue I think this is not necessarily a problem. Because with Cypress open I saw you are running the tests with Chrome browser, but with Cypress run the default is Electron. Can you send us what is the error message you are getting in these failed tests using cypress run?

I used `cypress open` and selected `electron` and all test cases also passed.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/26477537/161889544-c017b8f0-f74c-4401-a8bf-d6ebfe2d1755.png">

But when i used `./node_modules/.bin/cypress run`, some cases failed again!

Error message is here:

![image](https://user-images.githubusercontent.com/26477537/161889877-3326a9f4-dd38-46a9-8dc0-a6f057b24653.png)

**Comment by shijiatongxue** [comment]
Another thing is, some test cases also failed in github workflow. 

I use github action and config as cypress document. I think cypress will run in Chrome or Firefox?

here is the github action configration or directly click [here](https://github.com/DouyinFE/semi-design/blob/release/.github/workflows/cypress.yml):

```yml
name: 'test:cypress'

on:
  pull_request:
    branches: [ main, release, milestone**, test-cypress ]
    paths:
      - 'cypress/**'
      - 'packages/**'
      - '!packages/**/__test__/**'
      - '!packages/**/*.test.[tj]sx?'
      - '!packages/**/*.md'
  push:
    branches: [ main, release, milestone**, test-cypress ]
    paths:
      - 'cypress/**'
      - 'packages/**'
      - '!packages/**/__test__/**'
      - '!packages/**/*.test.[tj]sx?'
      - '!packages/**/*.md'

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.5.0-chrome94-ff93
    if: ${{ github.repository_owner == 'DouyinFE' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install global packages
        run: npm i -g lerna yarn
      - name: Build storybook
        run: |
          yarn bootstrap
          yarn build:lib
          yarn build-storybook
      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: storybook-static
          if-no-files-found: error
          path: storybook-static
      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          # Disable running of tests within install job
          runTests: false
  chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.5.0-chrome94-ff93
    needs: install
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: storybook-static
          path: storybook-static
      - name: 'Cypress Tests - Chrome'
        uses: cypress-io/github-action@v2
        with:
          # we have already installed all dependencies above
          install: true
          start: npx http-server -p 6006 storybook-static
          wait-on: 'http://localhost:6006'
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: 'Cypress - Chrome'
          spec: cypress/integration/*
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  firefox-tests:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node16.5.0-chrome94-ff93
      options: --user 1001
    needs: install
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: storybook-static
          path: storybook-static
      - name: 'Cypress Tests - Firefox'
        uses: cypress-io/github-action@v2
        with:
          # we have already installed all dependencies above
          install: true
          start: npx http-server -p 6006 storybook-static
          wait-on: 'http://localhost:6006'
          wait-on-timeout: 120
          browser: firefox
          record: true
          parallel: true
          group: 'Cypress - Firefox'
          spec: cypress/integration/*
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

checkout failed workflow: 
- Chrome: https://github.com/DouyinFE/semi-design/runs/5781604130?check_suite_focus=true
- Firefox: https://github.com/DouyinFE/semi-design/runs/5781603869?check_suite_focus=true
