### ISSUE TITLE
Cypress Dashboard - Tests run completed in GitHub action but show continuously running in dashboard and not stop until I cancel it manually.

### ISSUE THREAD

**Issue by KrupalVaghasiya** [cypress-io/cypress#21125]
### Current behavior

I am running my cypress test with GitHub action. The GitHub action test takes a maximum of 6 minutes to complete the run. After the test is completed run in the GitHub action. when I go to my cypress dashboard, it will show a test running. and not stop until I cancel it manually.

### Desired behavior

It should show test run completed if in the GitHub action completed test execution.

### Test code to reproduce

This is my `cypress.yml` file.
```
name: Legrande GitHub Actions
on:
  schedule:
  - cron: "0 0 * * *"

  push:
    branches:
      - 'master'
      
env: 
  CYPRESS_CACHE_FOLDER: cypress/cache
  
jobs:
 cypress-test:
  name: Run on windows
  runs-on: windows-latest
  steps: 
    - uses: actions/checkout@v2

    - name: Cache Node Modules
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}

    - name: Cache Cypress Binary
      id: cache-cypress-binary
      uses: actions/cache@v2
      with:
        path: cypress/cache
        key: cypress-binary-${{ hashFiles('package-lock.json') }}

    - name: Install Dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: |
        npm install
        npm install --dev

    - uses: cypress-io/github-action@v2
      continue-on-error: true
      with:
        record: true
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
```

### Cypress Version

9.5.4

### Other

Here is my Github action page for reference. `https://github.com/KrupalVaghasiya/cypressBug/actions`

Check this video for current behavior.
https://www.loom.com/share/19b84181594e421a8b687c1362db12ef
