### ISSUE TITLE
Issue with self-hosted actions runner and cypress + percy failures when running in parallel

### ISSUE THREAD

**Issue by josh803316** [cypress-io/cypress#21522]
### Current behavior

For some reason, some of the time when I try to run parallel tests in Github actions CI I get this failure. I have pre-installed the latest chrome on my AMI image so the chrome value should be identical across instances. The os, spec names, and version and type are all the same so I'm not sure how to debug this.

```bash
[percy] Downloading Chromium 929511...
[percy] Successfully downloaded Chromium 929511
[percy] Percy has started!
[percy] Running "npx --prefix /tmp/cy_percy cypress run --headless --record --parallel --group Core-Web PreMerge --tag pull_request --config-file /opt/actions-runner/_work/core-web/core-web/cypress/cypress.premerge.json --ci-build-id 42b8d60a3d11aa0ba8542270bc6422563758d9f5-594 --browser chrome"
[19138:0516/190009.386537:ERROR:gpu_init.cc([45](https://github.com/sketchy/core-web/runs/6458357382?check_suite_focus=true#step:7:45)3)] Passthrough is not supported, GL is swiftshader, ANGLE is 
You passed the --parallel flag, but we do not parallelize tests across different environments.

This machine is sending different environment parameters than the first machine that started this parallel run.

The existing run is: https://dashboard.cypress.io/projects/pfwmze/runs

In order to run in parallel mode each machine must send identical environment parameters such as:

 - specs
 - osName
 - osVersion
 - browserName
 - browserVersion (major)

This machine sent the following parameters:

{
  "osName": "linux",
  "osVersion": "Amazon Linux - 2 (Karoo)",
  "browserName": "Chrome",
  "browserVersion": "101.0.4951.64",
  "specs": [
    "cypress/integration/workflows/auth.spec.js",
    "cypress/integration/workflows/check-all-program-dashboards.spec.js",
    "cypress/integration/workflows/create-quiz.spec.js",
    "cypress/integration/workflows/login-via-cognito-sketchy.spec.js",
    "cypress/integration/workflows/navigate-to-lesson.spec.js",
    "cypress/integration/workflows/onboarding.spec.js",
    "cypress/integration/workflows/review-card.spec.js",
    "cypress/integration/workflows/search-to-lesson.spec.js",
    "cypress/integration/workflows/snapshot-all-app-locations.spec.js"
  ]
}

https://on.cypress.io/parallel-group-params-mismatch
[percy] Finalized build #585: https://percy.io/5b725[47](https://github.com/sketchy/core-web/runs/6458357382?check_suite_focus=true#step:7:47)e/Core-Web-App/builds/181131[67](https://github.com/sketchy/core-web/runs/6458357382?check_suite_focus=true#step:7:67)
```

### Desired behavior

The tests should run in parallel as expected.

### Test code to reproduce

It would be very hard for me to setup a reproducible environment for public usage.

### Cypress Version

9.6.1

### Other

Cypress package version: 9.6.1
Cypress binary version: 9.6.1
Electron version: 15.5.1
Bundled Node version: 16.5.0

**Comment by josh803316** [comment]
I believe I have an understanding of why this occurs. Our spot instances (fleet of 5) are running and not being terminated so as to be re-used during working hours. I changed some of the cypress/percy code in one PR branch and the tests ran while someone else had different code running in a separate branch that didn't have my test changes (including some filename changes for the specs).  What I believe happened is that one of the machines executed one set of tests for one of the PR builds and was then re-used for the second set of tests on the other build.... so the second run was using state from the first (we parallelize across 3 machines).

Is there a smart way to clean-up so that the state for the second run is basically brand new?

**Comment by josh803316** [comment]
That value is generated by github actions but should be unique for each run:
```yaml
     - name: Cypress run
        id: cypress-parallel-run
        uses: cypress-io/github-action@v3.0.5
        with:
          ...
          headless: true
          parallel: true
          command-prefix: '--prefix /tmp/cy_percy percy exec --disable-cache -- npx --prefix /tmp/cy_percy'
          tag: ${{ github.event_name }}
          group: 'Core-Web PreMerge'
          ci-build-id: '${{ github.sha }}-${{ github.run_number }}'
```
