### ISSUE TITLE
Intermittent CypressError: cy.click() failed because it requires a DOM element - subject undefined. (CircleCI only)

### ISSUE THREAD

**Issue by justinwhall** [cypress-io/cypress#2199]
### Current behavior:

Tests intermittently fail with the following error when run on Circleci only. Not always the same test, but always error on `cy.get().click()`. Cypress screenshot on failure (and video) show a blank page which obviously explains the absent DOM element. Why this happens only when Circle runs the test, I do not know.

```
     CypressError: cy.click() failed because it requires a DOM element.

The subject received was:

  > undefined

The previous command that ran was:

  > cy.get()
      at Object.cypressErr (https://pr-default-wpgrid.pantheonsite.io/__cypress/runner/cypress_runner.js:68076:11)
      at Object.throwErr (https://pr-default-wpgrid.pantheonsite.io/__cypress/runner/cypress_runner.js:68041:18)
      at Object.throwErrByPath (https://pr-default-wpgrid.pantheonsite.io/__cypress/runner/cypress_runner.js:68068:17)
      at ensureElement (https://pr-default-wpgrid.pantheonsite.io/__cypress/runner/cypress_runner.js:61289:21)
      at validateType (https://pr-default-wpgrid.pantheonsite.io/__cypress/runner/cypress_runner.js:61175:16)
      at Object.ensureSubjectByType (https://pr-default-wpgrid.pantheonsite.io/__cypress/runner/cypress_runner.js:61197:9)
      at pushSubjectAndValidate (https://pr-default-wpgrid.pantheonsite.io/__cypress/runner/cypress_runner.js:63785:15)
      at Context.<anonymous> (https://pr-default-wpgrid.pantheonsite.io/__cypress/runner/cypress_runner.js:63942:18)
      at https://pr-default-wpgrid.pantheonsite.io/__cypress/runner/cypress_runner.js:63656:33
      at tryCatcher (https://pr-default-wpgrid.pantheonsite.io/__cypress/runner/cypress_runner.js:7091:23)
      at Promise._settlePromiseFromHandler (https://pr-default-wpgrid.pantheonsite.io/__cypress/runner/cypress_runner.js:5113:31)
      at Promise._settlePromise (https://pr-default-wpgrid.pantheonsite.io/__cypress/runner/cypress_runner.js:5170:18)
      at Promise._settlePromiseCtx (https://pr-default-wpgrid.pantheonsite.io/__cypress/runner/cypress_runner.js:5207:10)
      at Async._drainQueue (https://pr-default-wpgrid.pantheonsite.io/__cypress/runner/cypress_runner.js:2028:12)
      at Async._drainQueues (https://pr-default-wpgrid.pantheonsite.io/__cypress/runner/cypress_runner.js:2033:10)
      at Async.drainQueues (https://pr-default-wpgrid.pantheonsite.io/__cypress/runner/cypress_runner.js:1907:14)
      at <anonymous>
```

### Example spec that intermittently fails:

```js
const baseUrl = Cypress.env('baseUrl'); // https://mysite.com
const authUrl = Cypress.env('authUrl'); // https://username:pass@mysite.com

// contact squares
context('Contact', () => {
  beforeEach(() => {
    cy.visit(`${authUrl}/contact/`);
  });

  it('Check support tile', () => {
    cy.get('.contact-tile--support').should('have.attr', 'href', 'https://support.mysite.com');
  });

  it('Check high volume tile', () => {
    cy.get('.contact-tile--highvolume').click();
    cy.url().should('eq', `${baseUrl}/contact-us-form/`);
  });

  it('Check pricing tile', () => {
    cy.get('.contact-tile--plans').click();
    cy.url().should('eq', `${baseUrl}/pricing/`);
  });

  it('Check FAQ tile', () => {
    cy.get('.contact-tile--faq').click();
    cy.url().should('eq', `${baseUrl}/resource/faq/`);
  });
});
```
### CircleCI config
```yaml
  #$CYPRESS_TEST_URL === https://mysite.com
  #$CYPRESS_AUTH_URL === https://username:pass@mysite.com
  test:
    docker:
    - image: cypress/base:8

    steps:
      - checkout

      - run:
          name: set env vars
          command: ./.circleci/cypress-setup.sh

      - run:
          name: install node modules
          working_directory: ./web/
          command: npm install --verbose

      - run:
          name: run cypress tests
          working_directory: ./web
          command: node_modules/.bin/cypress run --env baseUrl=$CYPRESS_TEST_URL,authUrl=$CYPRESS_AUTH_URL --record --key my-key-48754875-85787 --spec 'cypress/integration/branch/*'

      - store_test_results:
          path: ./web/cypress/results

      - store_artifacts:
          path: ./web/cypress/videos

      - store_artifacts:
          path: ./web/cypress/screenshots
```
### Things I've tried
- Making the test URL public (no auth require)
- Various cypress/** docker images
- Various different environment urls
- increasing `defaultCommandTimeout` and `pageLoadTimeout` in  #`cypress.json`

### Versions
_Both locally (OSX 10.12.6) and @ Circle_
- Cypress 3.0.2
- Node 8.11
- Electron 59 (headless)
