### ISSUE TITLE
Not found binary in the DroneCI

### ISSUE THREAD

**Issue by williamcosta** [cypress-io/cypress#2249]
### Current behavior:

![screen shot 2018-07-31 at 09 19 26](https://user-images.githubusercontent.com/6557202/43459125-e49f5e74-94a2-11e8-899f-2a5d4c617e9e.png)

The code in DroneCI config

```yml
pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
      - ~/.cache
      - ~/.npm
    volumes:
      - /tmp/cache:/cache
    ttl: 3

  build:
    image: getninjas/nodejs:9-chrome64
    commands:
      - npm ci

  integration-test:
    group: tests
    image: getninjas/nodejs:9-chrome64
    commands:
      - npm run server:test
      - ./node_modules/bin/cypress run
      - npm run clear:pm2
    environment:
      - REDIS_HOST=redis

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
      - ~/.cache
      - ~/.npm
    volumes:
      - /tmp/cache:/cache
```

### Desired behavior:

I ran my test pipeline on DroneCI and before was running version 2.x running smoothly.

I am trying to update the version to 3.0.2 and now Cypress complains that Binary is not being found, I have already tried some ways to solve with ENV variable and mount folder in cache step.

If anyone can help me, thank you.

### Versions

Platform: linux (Debian - 8.10)
Cypress: v3.0.2
DroneCI: v0.5
