### ISSUE TITLE
cypress cache prune does not recognise versions 10.x as being higher than v9.7.0

### ISSUE THREAD

**Issue by dsayerm** [cypress-io/cypress#22832]
### Current behavior

**Issue:**: `npx cypress cache prune` is removing versions 10.x and higher, rather than the version 9.7.0

On CI, I currently have the following versions installed:
- 9.7.0
- 10.2.0
- 10.3.0
As can be seen by the CI output:

```
Run npx cypress cache path
npm WARN exec The following package was not found and will be installed: cypress
C:\actions-runner\cypress-cache
npm WARN exec The following package was not found and will be installed: cypress
┌─────────┬──────────────┬─────────┐
│ version │ last used    │ size    │
├─────────┼──────────────┼─────────┤
│ 10.2.0  │ 14 days ago  │ 500.8MB │
├─────────┼──────────────┼─────────┤
│ 10.3.0  │ 15 hours ago │ 500.8MB │
├─────────┼──────────────┼─────────┤
│ 9.7.0   │ 20 days ago  │ 504.1MB │
└─────────┴──────────────┴─────────┘
```

The next step on CI is to run `npx cypress cache prune` which returns:

```

Run npx cypress cache path
  
npm WARN exec The following package was not found and will be installed: cypress
C:\actions-runner\cypress-cache
npm WARN exec The following package was not found and will be installed: cypress
Deleted all binary caches except for the 9.7.0 binary cache.
```

### Desired behavior

In this situation, the prune command should have removed versions 9.7.0 and 10.2.0.

### Test code to reproduce

**Setup:** Github actions, self-hosted
YAML:
```yml
      - name: Get Cypress Cache List 📋
        run: |
          npx cypress cache path
          & npx cypress cache list --size
      
      - name: Remove old versions of Cypress 🗑️
        run: |
          npx cypress cache path
          & npx cypress cache prune
        env:
          CYPRESS_CACHE_FOLDER: C:\actions-runner\cypress-cache\
```

### Cypress Version

10.3.0

### Other

Current workaround is to log on manually onto the server and delete the outdated versions but this is a bit of a pain.
