### ISSUE TITLE
Cypress/CircleCi - Rerun workflow from failed causes 0 tests to run and 'passes' the circle job

### ISSUE THREAD

**Issue by trevor-bennett** [cypress-io/cypress#23963]
### Current behavior

splitting cypress/install and cypress/run into two different jobs within the circleci config yml will cause 0 tests to actually run when selecting rerun workflow from failed if the failed job within circle is only cypress/run

First failed circleci run:

<img width="957" alt="image" src="https://user-images.githubusercontent.com/53020883/192027225-004bb079-3991-43f6-9422-d29722b9d3e2.png">

After selecting `Rerun workflow from failed`:

<img width="969" alt="image" src="https://user-images.githubusercontent.com/53020883/192027318-25d4b752-a7b3-421f-9ca1-7dea4d17892b.png">

Cypress console logging:

<img width="959" alt="image" src="https://user-images.githubusercontent.com/53020883/192027606-4bacdeb4-403a-4d4a-bf77-72f5f9ac645b.png">

### Desired behavior

When the CircleCI option to `Rerun workflow from failed` step in invoked, the proper tests are ran.

### Test code to reproduce

Prerequisites:
- cypress dashboard (record = true)
- circleci/cypress orb

CircleCi Job Definitions:
```
version: 2.1

orbs:
  cypress: cypress-io/cypress@2.1.0

jobs:
  - cypress/install:
      requires:
        - install
      post-steps:
        - run:
            name: Print machine info
            command: npx cypress info
  - cypress/run:
      start: npm run serve
      wait-on: "http-get://localhost:8000"
      record: true
      parallel: true
      parallelism: 2
      ci-build-id: ${CIRCLE_SHA1:0:8}
      group: "UI Tests - Electron"
      requires:
        - cypress/install
      post-steps:
        - report-cypress-results
```

### Cypress Version

10.3.1

### Node version

12.19.0

### Operating System

Ubuntu 20.04.4 LTS
