### ISSUE TITLE
Launching Webkit via GH Actions against localhost throws Error: read ECONNRESET at TCP.onStreamRead

### ISSUE THREAD

**Issue by bennymeade** [cypress-io/cypress#24704]
### Current behavior

[](url)Running Webkit test against http://localhost:3000/ via **GH Actions** results in the following error:
```
read ECONNRESET
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
Error: The process '/usr/local/bin/yarn' failed with exit code 1
```
Suggesting that webkit cannot reach the localhost site when running via GH Actions.

Running this test locally against localhost works.
The same test passes on a live www site.
The same test passes with Chrome browser against localhost via GH Actions.

![github com_Unilever_unilever-online_actions_runs_3478692570_jobs_5816354990](https://user-images.githubusercontent.com/1033474/202178778-2d6109ca-a843-4da0-a95f-b0c88ab03dcf.png)

### Desired behavior

Webkit can successfully run tests against a localhost site via GH Actions.

### Test code to reproduce

```
- name: Install webkit dependencies
        uses: cypress-io/github-action@v4
        with:
          build: npx playwright install-deps webkit
          runTests: false
          
- name: Run integration tests - device = chrome
        uses: cypress-io/github-action@v4
        with:
          install: false
          working-directory: packages/web/corporate
          start: yarn serve
          wait-on: 'http://localhost:3000'
          command: yarn cypress run --browser chrome --spec 'cypress/e2e/components/test-site.int.test.cy.ts'

- name: Run integration tests - device = webkit
        uses: cypress-io/github-action@v4
        with:
          install: false
          working-directory: packages/web/corporate
          start: yarn serve
          wait-on: 'http://localhost:3000'
          command: yarn cypress run --browser webkit --spec 'cypress/e2e/components/test-site.int.test.cy.ts'
```

### Cypress Version

v11.0.1

### Node version

v16.18.0

### Operating System

Ubuntu   20.04.5   LTS

### Debug Logs

```shell
read ECONNRESET
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
Error: The process '/usr/local/bin/yarn' failed with exit code 1
```
