### ISSUE TITLE
Cypress and DDEV doesn't work on GitHub Action Test with multiple domain

### ISSUE THREAD

**Issue by LorenzoAlu** [cypress-io/cypress#24766]
### Current behavior

Hello, everyone.
I am working on an existing project that already had Cypress tests running via GitHub action.

My problem is as follows:
Due to application updates, currently the same application responds to three different domains. Since this change was introduced, the tests on GitHub have stopped working. 

I have tried logging the output of the tests, and the tests fail because the applications are not loading.

Locally, the tests all work perfectly.

Do you have any advice for me? I've been working on this for quite some time without getting any results.

Translated with www.DeepL.com/Translator (free version)

My stack:
* DDEV 19.0.0
* Symfony 4.4
* php 7.2
* Vue 2
* Cypress 11
* Node 
* v14.19.1

### Desired behavior

I expect tests to pass on GitHub as locally

### Test code to reproduce

DDEV config:

```yaml
APIVersion: v1.19.1
name: host-1
type: php
docroot: public
php_version: "7.2"
webserver_type: apache-fpm
webimage: ddev-webserver:1.19.0
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames:
  - host-2
  - host-3
additional_fqdns: [ ]
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
composer_version: "2"
timezone: ""
omit_containers: [ db, dba ]
web_environment:
  - PHP_IDE_CONFIG=serverName=${DDEV_PROJECT}
webimage_extra_packages: [ wkhtmltopdf ]
host_db_port: "52789"
hooks:
  post-start:
    - exec: 'nvm install && nvm use'
```

GitHub test:

```yaml
name: Tests
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
  workflow_dispatch:

jobs:
  tests:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    services:
      azure:
        image: mcr.microsoft.com/azure-sql-edge
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: P@assword
          MSSQL_PID: Developer
        options: --name=azure --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'P@assword' -Q 'SELECT 1'" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_GITHUB }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2
          extensions: soap

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Install php dependencies
        run: composer install --no-interaction

      - name: Install node dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Run Migration
        run: |
          php bin/console doctrine:database:create || echo "creation failed"
          php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"

      - name: Run tests
        run: ./vendor/bin/phpunit
        env:
          DB_HOST: 127.0.0.1
          WKHTMLTOPDF_PATH: /usr/local/bin/wkhtmltopdf
          WKHTMLTOIMAGE_PATH: /usr/local/bin/wkhtmltoimage
          MAILER_DSN: null://null

      - name: Run frontend unit tests
        run: npm test
      - name: Fix APT dependencies
        run: sudo apt --fix-broken -y install

      - name: Setup ddev
        uses: jonaseberle/github-action-setup-ddev@v1

      - name: Wait for ddev setup completion
        run: sleep 10s
        shell: bash

      - name: Create database in ddev container
        run: ddev exec bin/console doctrine:database:create --no-interaction --env=test

      - name: Migrate database in ddev container
        run: ddev exec bin/console doctrine:migrations:migrate --no-interaction --env=test

      - name: Setup test env for Cypress
        uses: finnp/create-file-action@master
        env:
            FILE_NAME: ".env.local"
            FILE_DATA: "APP_ENV=test"

      - name: Run frontend e2e tests
        run:  |
          npm ci
          npm run test:e2e

```

GitHub test output:
```linux 
host 1  - app load
    1) test
    2) should load the app without expired simulations

  Api errors on load
    3) "after each" hook for "should show error message on error 400"

  API returns expired promotions
    4) should show expired promotions

  Host 2 - app load
    5) test
    6) should load the app without expired simulations

  Api errors on load
    7) "after each" hook for "should show error message on error 400"

  API returns expired promotions
    8) should show expired promotions

  Host 3 - app load
    9) test
    10) should load the app without expired simulations

  Api errors on load
    11) "after each" hook for "should show error message on error 400"

  API returns expired promotions
    12) should show expired promotions

  test no env - app load
    13) test no env

  with correct base url
    14) with correct base url


  0 passing (1m)
  14 failing

  1) Host 1 - app load
       test:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `#stage`, but never found it.
      at Context.eval (webpack:///./cypress/e2e/app_load.spec.js:15:29)

  2) Host 1 - app load
       should load the app without expired simulations:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `#stage`, but never found it.
      at Context.eval (webpack:///./cypress/e2e/app_load.spec.js:20:29)

  3) Api errors on load
       "after each" hook for "should show error message on error 400":
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-cy="generic-error-connectivity-msg"]`, but never found it.

Because this error occurred during a `after each` hook we are skipping the remaining tests in the current suite: `Api errors on load`
      at Context.eval (webpack:///./cypress/e2e/app_load.spec.js:32:15)

  4) API returns expired promotions
       should show expired promotions:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `#stage`, but never found it.
      at Context.eval (webpack:///./cypress/e2e/app_load.spec.js:[97](https://github.com/host -2/actions/runs/3518757918/jobs/5898004866#step:22:98):29)

  5) Host 2 - app load
       test:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `#stage`, but never found it.
      at Context.eval (webpack:///./cypress/e2e/app_load.spec.js:15:29)

  6) Host 2 - app load
       should load the app without expired simulations:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `#stage`, but never found it.
      at Context.eval (webpack:///./cypress/e2e/app_load.spec.js:20:29)

  7) Api errors on load
       "after each" hook for "should show error message on error 400":
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-cy="generic-error-connectivity-msg"]`, but never found it.

Because this error occurred during a `after each` hook we are skipping the remaining tests in the current suite: `Api errors on load`
      at Context.eval (webpack:///./cypress/e2e/app_load.spec.js:32:15)

  8) API returns expired promotions
       should show expired promotions:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `#stage`, but never found it.
      at Context.eval (webpack:///./cypress/e2e/app_load.spec.js:97:29)

  9) Host 3 - app load
       test:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `#stage`, but never found it.
      at Context.eval (webpack:///./cypress/e2e/app_load.spec.js:15:29)

  10) Host 3 - app load
       should load the app without expired simulations:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `#stage`, but never found it.
      at Context.eval (webpack:///./cypress/e2e/app_load.spec.js:20:29)

  11) Api errors on load
       "after each" hook for "should show error message on error 400":
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-cy="generic-error-connectivity-msg"]`, but never found it.

Because this error occurred during a `after each` hook we are skipping the remaining tests in the current suite: `Api errors on load`
      at Context.eval (webpack:///./cypress/e2e/app_load.spec.js:32:15)

  12) API returns expired promotions
       should show expired promotions:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `#stage`, but never found it.
      at Context.eval (webpack:///./cypress/e2e/app_load.spec.js:97:29)

  13) test no env - app load
       test no env:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `#stage`, but never found it.
      at Context.eval (webpack:///./cypress/e2e/app_load.spec.js:[109](https://github.com/host-2/actions/runs/3518757918/jobs/5898004866#step:22:110):25)

  14) with correct base url
       with correct base url:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `#stage`, but never found it.
      at Context.eval (webpack:///./cypress/e2e/app_load.spec.js:[120](https://github.com/host-2/actions/runs/3518757918/jobs/5898004866#step:22:121):25)
```

### Cypress Version

11.0.0

### Node version

v14.19.1

### Operating System

maxOS 12.3.1
