### ISSUE TITLE
How to pass variables from cypress to github actions?

### ISSUE THREAD

**Issue by nitinchalopadho** [cypress-io/cypress#24839]
### Current behavior

I have some tests written in cypress and i'm running them with script like this
`cypress:run-level": "cypress run --spec cypress/e2e/end-to-end/end-to-end.cy.js --env program='lower-level'"`

I want my program variable when running from Github actions and my Github actions workflow file look like this
```
name: Run cypress
on:
  push:
    branches:
      - staging
  workflow_dispatch:
    branches:
      - staging
jobs:
  cypress-run:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: cypress-tests
          ref: dev
          ssh-key: ${{ secrets.CYPRESS_PRIVATE_KEY }}
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npx cypress run --record --key ${{ secrets.CYPRESS_TOKEN }}
        env:
          CYPRESS_program: ${{ secrets.CYPRESS_PROGRAM }}
```

My cypress.config.js is down below. I defined the env inside it as well and set the program value to be empty by default.

I want the program variable value which I'm passing when running the command inside env so that I can use it in my tests.

Any help? @nagash77 @ryanthemanuel @marktnoonan 

### Test code to reproduce

```
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  projectId: "79gg6r",
  video: true,
  viewportHeight: 800,
  viewportWidth: 1500,
  numTestsKeptInMemory: 0,
  defaultCommandTimeout: 10000,
  e2e: {
    // We've imported your old cypress plugins here.
    // You may want to clean this up later by importing these.
    setupNodeEvents(on, config) {
      return require("./cypress/plugins/index.js")(on, config);
    },
    baseUrl: "https://app-staging.assessprep.com/",
    env: {
      program: "",
    },
  },
});
```

### Cypress Version

10.9.0

### Node version

12.16.1

### Operating System

macOs 10.15.7
