### ISSUE TITLE
Losing page styles/js while using cy.session - CI

### ISSUE THREAD

**Issue by DevYimo** [cypress-io/cypress#25405]
### Current behavior

Recently we have updated "our" cypress from v11.2 to 12.3.0 and since then, we are facing weird behaviour in CI tests run.
It seems like, after calling  `cy.session` and than `cy.visit()` page have lost its styles and maybe event its js?
![image](https://user-images.githubusercontent.com/122315075/211403220-08b55293-dfff-45af-a14a-337febfbab0d.png)

As you can see on image, whole layout is destroyed.

Before cypress v12.x everything worked without problem, but now, we are kinda lost. 
 - nothing much was changed after that update only from `Cypress.preserve` deprecation we had to use `cy.session`.
 
The Poblem is, that this happens only in CI. On every locale machine we had tried (macOS, Windows - WLS) it works just fine.

As you can see in login code below, I even tried to make sure that CSS are loaded when creating session. And it seems that is correct (since session is succefully created). But I found out, when reusing session, Cypress has to recreate session because of validation => when `admin page` is loaded, no css is loaded. Weirdly enough, when recreating session, visited page in session part code has everything loaded. Although after cy.visit(), page is again "destroyed" :(

Have to say, this losing behaviour is happaning only when session is involved. Tests without cy.session works fine.

I don't know if it's cypress bug, or just our gitlab issue? But it stopped working after cypress v12.3 with session.
 - I have tried like everything, but can't find the problem.

### Desired behavior

Page should correctly load.

### Test code to reproduce

Login command:
```
cy.session([autoLoginUser, autoLoginPass], () => {
        cy.visit('/auth/login')

        cy.url().then((url) => {
            if (url.includes('/admin')) {
                cy.log('Already logged')
                return
            }
            cy.get('input#email').type(autoLoginUser)
            cy.get('input#password').type(autoLoginPass)
            cy.get('label[data-name="remember"].checkbox').click()
            cy.get('button[type="submit"].button-primary').click()
            cy.url().should('match', /https?:\/\/(?:w{1,3}\.)?[^\s.]+(?:\.[a-z]+)*(?::\d+)?\/admin.*/)
            cy.get('.sidebar').should('have.css', 'background-color', 'rgb(0, 157, 225)')
        })
    }, {
        validate() {
            cy.getCookies().then((cookies) => {
                const rememberWeb = cookies.find(c => c.name.startsWith('remember_web_'))
                expect(rememberWeb.name).to.match(/remember_web_\S+$/)
            })
            cy.visit('/admin')
            cy.url().should('match', /https?:\/\/(?:w{1,3}\.)?[^\s.]+(?:\.[a-z]+)*(?::\d+)?\/admin.*/)
            cy.get('.sidebar').should('have.css', 'background-color', 'rgb(0, 157, 225)')
        },
        cacheAcrossSpecs: true
    })
```

test.cy.js
```
describe('Admin: Create issued invoices', () => {
    beforeEach(() => {
        cy.login()
        cy.visit('/admin/finance/invoices/issued/create')
    })

    it('Create simple invoice for non vat buyer and edit', () => {
        assertIssuedDueDates(new Date())

        fillCompany()
        ...
    })
    
    .....
 })
```

gitlab-ci.yml
```
variables:
  TZ: 'Europe/Prague'
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

cache:
  key: ${CI_JOB_NAME}
  paths:
    - vendor/
    - node_modules/
    - cache/Cypress

....

test:
 image: cypress/browsers:node18.12.0-chrome107
 tags:
    - docker
 script:
  - TZ=Europe/Prague AUTO_LOGIN_USER=${AUTO_LOGIN_USER} AUTO_LOGIN_PASSWORD=${AUTO_LOGIN_PASSWORD} CYPRESS_BASE_URL=${APP_URL} ./node_modules/.bin/cypress run --headless --browser chrome --reporter mocha-junit-reporter
```

### Cypress Version

12.3.0

### Node version

18.12.0

### Operating System

Windows 11, MacOS
