### ISSUE TITLE
When running Cypress tests in the GitHub workflow, a 404 error code is returned.

### ISSUE THREAD

**Issue by belwalshubham** [cypress-io/cypress#25407]
### Current behavior

I  get the 404 error when I run Cypress in github.

In package. json I have this code.

```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt build && nuxt preview"
  },
```  

and In YML file 
```
 steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: install npm
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm run dev
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          fail_ci_if_error: true
          verbose: true
 ```
 

If instead of using npm run dev, I run npm run preview, it works fine and Cypress runs successfully, but it does not generate a code coverage report FILE NOT FOUND error will shown after running code coverage in github action . A code coverage report can only be generated when I use npm run dev, but it gives a 404 error.

### Test code to reproduce

The response we received from your web server was:
  > 404: Not Found
  
![cypress error](https://user-images.githubusercontent.com/61574835/211454112-28cc3a92-75ae-4dce-b23a-145d623c2d04.PNG)

### Cypress Version

"cypress": "^10.8.0"

### Node version

v16.17.0

### Operating System

Windows 10.0.19044.1889
