### ISSUE TITLE
Cypresserror: Timed out after waiting 60000 ms for remote page to load

### ISSUE THREAD

**Issue by ShaktiMandal** [cypress-io/cypress#25423]
### Current behavior

I am working on a client's project, based on a requirement, we have to introduce cypress test in the workflow. After making necessary changes, cypress works fine in local [ dev machine ]. However, whenever it runs on github, encountered below error.

Cypresserror: Timed out after waiting 60000 ms for remote page to load.

please note, increasing the time limit does not help.

Please find below details. It would be really helpful if someone can suggest anything as I am stuck with this for days.

**Details :**
Framework: vue3
Bundler: Vite

**Workflow (only cypress part):**

```yaml
 - name: install cypress and dependencies
      env:
        CI: 1
      run: |
        npm ci
        npx cypress verify
        npx cypress info
        npx cypress version
    - name: cypress.io
      uses: cypress-io/github-action@v5.0.4
      with:
        working-directory: <dir>
        headed: true
        record: true
        start: npm run serve
      env:
        CYPRESS_username: <user_name>
        CYPRESS_password: ${{ secrets.<passcode> }}
```

**Cypress config:**
```js
import { defineConfig } from 'cypress';
export default defineConfig({
    e2e:{
        baseUrl: 'http://localhost:9000',
        supportFile: 'e2e/test/support/index.js',
        specPattern: 'e2e/test/specs/**/*.cy.{js, jsx, ts, tsx}'
    }
})
```

**cypress.env.json:** 
```
{
"username": <user_name>,
"password": <password>
baseUrl: "http://localhost:9000"
}
```

### Desired behavior

It should run the test.

### Test code to reproduce

NA

### Cypress Version

10.11.0

### Node version

16

### Operating System

macOS

### Debug Logs

```shell
NA
```
