### ISSUE TITLE
Cypress does not detect dependencies with Yarn 3 PNP

### ISSUE THREAD

**Issue by wopian** [cypress-io/cypress#25733]
### Current behavior

Shows a warning that `vite@4`, `react@18` and `react-dom@18` (or `vue@3` in Vue repositories) dependencies are not found when running component tests interactively with Yarn 3 PNP

<img width="626" alt="Screenshot 2023-02-07 at 10 49 10" src="https://user-images.githubusercontent.com/3440094/217224724-d9c6f637-b7ea-43c5-867e-391cc6b6bf87.png">

### Desired behavior

No warnings when `vite@4`, `react@18` and `react-dom@18` are all installed and listed as dependencies in package.json

### Test code to reproduce

Barebones React 18 and Vite 4 reproduction with Yarn 3: https://github.com/wopian/cypress-test-tiny

CircleCI has been changed to use Yarn commands.

### Cypress Version

12.5.0

### Node version

19.6.0

### Operating System

macOS 13.0

### Other

Yarn 3 with Plug 'n' Play.

`.yarnrc.yml`
```yaml
cloneConcurrency: 8
defaultSemverRangePrefix: '~'
enableScripts: false
enableTelemetry: false
httpRetry: 3
httpTimeout: 60000
nmMode: hardlinks-global
nodeLinker: pnp
yarnPath: .yarn/releases/yarn-3.3.1.cjs
```
