### ISSUE TITLE
Is there a way to remove the "What's new in Cypress" message?

### ISSUE THREAD

**Issue by AtofStryker** [cypress-io/cypress#26196]
@troccoli commented on [Wed Mar 15 2023](https://github.com/cypress-io/cypress-docker-images/issues/857)

I'm running Cypress using a docker-compose with the following configuration

```yaml
cypress:
  image: 'cypress/included:12.8.0'
  profiles:
    - on-demand-only
  volumes:
    - '.:/e2e'
    - '/tmp/.X11-unix:/tmp/.X11-unix'
  working_dir: /e2e
  environment:
    - CYPRESS_baseUrl=http://laravel.test
    - CYPRESS_VIDEO=false
    - DISPLAY=host.docker.internal:0
  networks:
    - sail
  depends_on:
    - laravel.test
  entrypoint: cypress
```

and with the following command

```shell
docker run -it -rm cypress open --project .
```

The first thing I see is the "What's new in Cypress" message and I have to click on the button to go on.

![Screenshot 2023-03-15 at 19 10 22](https://user-images.githubusercontent.com/11234160/225417735-db484eb9-3200-4e41-a567-cd4b226c0b4c.png)

Is there any way I can disable it? 

---

@AtofStryker commented on [Thu Mar 16 2023](https://github.com/cypress-io/cypress-docker-images/issues/857#issuecomment-1472304725)

Hi @troccoli. Thank you for opening an issue. I don't think we currently have a way to pass user preferences into the app via config or the CLI, but I am asking the team to be sure. This issue might make more sense in https://github.com/cypress-io/cypress as the binary itself would be the place this message is dismissed. Would you mind opening an issue over there and closing this one?

---

@troccoli commented on [Thu Mar 16 2023](https://github.com/cypress-io/cypress-docker-images/issues/857#issuecomment-1472497175)

Thanks @AtofStryker
