### ISSUE TITLE
Environment variables are undefined in github pipeline

### ISSUE THREAD

**Issue by Sebastian-Sole** [cypress-io/cypress#26304]
### Current behavior

I am using Cypress with Auth0 authentication, and everything works locally. However, when the tests are run in github CI, my environment variables are undefined. The test failing is failing on cy.request(), where I attempt to login to Auth0.

Here is the custom cypress functino that fails to run in the test in the pipeline. The `domain` variable is undefined, causing the rest of the test to fail, since cy.request() then has an invalid url:
```js
/// <reference types="cypress" />

/*
 *
 * Huge thanks to user `rnnyrk` for most of the code contained in this file ❤️ . Without it, it would not be possible
 * to properly end-to-end test the next-auth-auth0 adapter. The code below is a slightly modified version 🔥
 *
 * Source: https://community.auth0.com/t/next-auth-auth0-e2e-with-cypress-test-not-working-on-host-but-redirecting-to-universal-flow/86683
 */

import hkdf from '@panva/hkdf'
import { EncryptJWT, JWTPayload, decodeJwt } from 'jose'
import type { Profile } from 'next-auth'

/**
 * getDerivedEncryptionKey - Derive an encryption key from the NextAuth secret
 *
 */
async function getDerivedEncryptionKey() {
  const secret = process.env.NEXTAUTH_SECRET as string
  return await hkdf('sha256', secret, '', 'NextAuth.js Generated Encryption Key', 32)
}

/**
 * encode - Encrypt a JWT token based on an encrypted key using Direct AES Encryption (dir)
 * and AES GCM (A256GCM) for content encryption
 *
 * @param {JWTPayload} token
 * @returns {Promise<string>}
 */
export async function encode(token: JWTPayload): Promise<string> {
  const maxAge = 30 * 24 * 60 * 60 // 30 days
  const encryptionSecret = await getDerivedEncryptionKey()
  return await new EncryptJWT(token)
    .setProtectedHeader({ alg: 'dir', enc: 'A256GCM' })
    .setExpirationTime(Math.round(Date.now() / 1000 + maxAge))
    .encrypt(encryptionSecret)
}

type LoginAs = 'tenant' | 'propertyManager'
type LoginDetails = {
  username: string
  password: string
  client_id: string
  client_secret: string
  audience: string
  scope: string
  domain: string
}

const loginDetails: Record<LoginAs, LoginDetails> = {
  tenant: {
    username: process.env.TENANT_EMAIL as string,
    password: process.env.TENANT_PASSWORD as string,
    domain: process.env.AUTH0_TENANT_ISSUER_BASE_URL as string,
    audience: process.env.AUTH0_TENANT_AUDIENCE_URL as string,
    client_id: process.env.AUTH0_TENANT_CLIENT_ID as string,
    client_secret: process.env.AUTH0_TENANT_CLIENT_SECRET as string,
    scope: 'openid profile email'
  },
  propertyManager: {
    username: process.env.PROPERTY_MANAGER_EMAIL as string,
    password: process.env.PROPERTY_MANAGER_PASSWORD as string,
    audience: process.env.AUTH0_AUDIENCE_URL as string,
    domain: process.env.AUTH0_ISSUER_BASE_URL as string,
    client_id: process.env.AUTH0_CLIENT_ID as string,
    client_secret: process.env.AUTH0_CLIENT_SECRET as string,
    scope: 'openid profile email'
  }
}

Cypress.Commands.add('loginToAuth0', (loginAs: LoginAs) => {
  if (!Object.keys(loginDetails).includes(loginAs)) {
    throw new Error(
      `Invalid loginAs parameter '${loginAs}'. Valid values are ${Object.keys(loginDetails).join(
        ', '
      )}`
    )
  }

// This is where domain is undefined (this is from the .env variables). It works locally, not in github pipeline
  const { username, password, client_id, client_secret, audience, scope, domain } =
    loginDetails[loginAs as keyof typeof loginDetails]

  const log = Cypress.log({
    displayName: 'AUTH0 LOGIN',
    message: [`🔐 Authenticating | ${username}`],
    autoEnd: false
  })

  log.snapshot(`Logging in as ${username}`)

  log.snapshot('before')

  /**
   * session - Create a session to store the user's access and id token
   * for reuse throughout the application
   *
   * @param {}
   */
  cy.session('next-auth-session', () => {
    /**
     * request - Make a request to the Auth0 API to retrieve the user's access and id token
     * using the username and password provided, audience, scope, client id and client secret.
     * This is in essence, a login.
     *
     * @param {}
     */
    cy.request({
      method: 'POST',
      url: `${domain}/oauth/token`,
      body: {
        grant_type: 'password',
        username,
        password,
        audience,
        scope,
        client_id,
        client_secret
      }
    }).then(async ({ body }) => {
      const { id_token, access_token } = body
      const user: Profile = decodeJwt(id_token)

      const profile = {
        accessToken: access_token,
        idToken: id_token,
        sub: user.sub,
        picture: user.name,
        email: user.email,
        profile: {
          ...user
        }
      }

      // Generate and set a valid cookie that next-auth can decrypt
      const encryptedToken = await encode(profile)
      cy.setCookie('next-auth.session-token', encryptedToken)

      log.snapshot('after')
      log.end()
    })
  })
})

declare global {
  namespace Cypress {
    interface Chainable {
      loginToAuth0(loginAs: LoginAs): Chainable<void>
    }
  }
}

export {}

```

Here is my workflow:
```
# Environment variables are set earlier, and are correct
e2e:
    name: 🖥 - E2E tests
    runs-on: ubuntu-latest
    needs: [test]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: 🧰 - Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: 📦 - Install dependencies
        run: pnpm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2

        with:
          # we have already installed all dependencies above
          install: false
          command: pnpm dlx cypress run
          start: pnpm --dir . dev
          wait-on: 'http://localhost:3000'
```

Here is an image of the error message in the github pipeline:
<img width="1196" alt="Screen Shot 2023-03-30 at 13 38 43" src="https://user-images.githubusercontent.com/71325332/228824710-eaf97f2b-8c52-4045-aa67-ee7529b48797.png">

As you can see, the url is `http://localhost:3000/undefined/oauth/token`. This happens because if there isn't a valid url, it uses the baseUrl (localhost:3000). Whereas if domain was not undefined, the it would be `${domain}/oauth/token`. 

### Desired behavior

I expect for the tests to pass, and for domain to be defined. The tests pass locally, but not in the github pipeline. 

### Test code to reproduce

I'm not sure what to put here, you would need an Auth0 tenant to connect to, and I can't give you access to mine due to security reasons. However, the functionality is logging in via Auth0 in a Cypress test, which I know already has its bugs.

### Cypress Version

12.7.0

### Node version

16.13.1

### Operating System

macOS 12.5

**Comment by MikeMcC399** [comment]
@Sebastian-Sole 

cypress-io/github-action@v2 is quite an old version. We're now on cypress-io/github-action@v5.

I can't say if this will influence your issue. I just wanted to draw your attention to it!

**Comment by Sebastian-Sole** [comment]
> 

I updated it, but still no difference. Thanks for pointing that out though!

**Comment by emilyrohrbough** [comment]
@Sebastian-Sole Thank you so much for the detailed information on your issue. This is super helpful for understanding your setup and the problem. Looking at your github actions workflow setup, you stated `# Environment variables are set earlier, and are correct`. Can you confirm you are:
1. [Setting these envs for the entire workflow](https://docs.github.com/en/actions/learn-github-actions/variables#defining-environment-variables-for-a-single-workflow)?
2. Have prefixed these ENVs with `CYPRESS_`? Env prefixed with `CYPRESS_` will [automatically be passed to the Cypress process](https://docs.cypress.io/guides/guides/environment-variables#Option-3-CYPRESS_) and to your tests.

Here is an [example](https://github.com/cypress-io/github-action#env) for reference of passing the envs directly to the `cypress-io/github-action` step.

**Comment by Sebastian-Sole** [comment]
> @Sebastian-Sole Thank you so much for the detailed information on your issue. This is super helpful for understanding your setup and the problem. Looking at your github actions workflow setup, you stated `# Environment variables are set earlier, and are correct`. Can you confirm you are:
> 
> 1. [Setting these envs for the entire workflow](https://docs.github.com/en/actions/learn-github-actions/variables#defining-environment-variables-for-a-single-workflow)?
> 2. Have prefixed these ENVs with `CYPRESS_`? Env prefixed with `CYPRESS_` will [automatically be passed to the Cypress process](https://docs.cypress.io/guides/guides/environment-variables#Option-3-CYPRESS_) and to your tests.
> 
> Here is an [example](https://github.com/cypress-io/github-action#env) for reference of passing the envs directly to the `cypress-io/github-action` step.

Thank you for the answer. I can confirm that I am setting up the .env variables in the way specified in the example. I have tried setting them as global variables and local variables for the job. For reference, here is how that looks:


```
name: Next Test & Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ...
  CYPRESS_PROPERTY_MANAGER_EMAIL: ${{secrets.PROPERTY_MANAGER_EMAIL}}
  ...

jobs:
  e2e:
    name: 🖥 - E2E tests
    runs-on: ubuntu-latest
    needs: [test]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: 🧰 - Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: 📦 - Install dependencies
        run: pnpm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5

        with:
          # we have already installed all dependencies above
          install: false
          command: pnpm dlx cypress run
          start: pnpm --dir . dev
          wait-on: 'http://localhost:3000'
       ...

```

I have also tried defining the .env variables in the test, and both in the test and globally.

**Comment by MikeMcC399** [comment]
@Sebastian-Sole 

You might want to consider using

```
env:
  DEBUG: '@cypress/github-action, cypress:*'
```

in your workflow to gain more insight into what is happening. For test purposes I would try to avoid using secrets because the log files redact them.

**Comment by emilyrohrbough** [comment]
@Sebastian-Sole Looking at the CI setup and the single ENV you provided and looking at the code you provided, I'm surprised this is working locally. The test will execute in the browser's context and I would not expect the use of `process.env` but the of `Cypress.env()` to pull out env passed from the node process into the browser process.

Using `process.env` would work in your project configuration if passed to the `config.env` object. 

Can you share the full env setup locally and in CI? You can omit the actual values with `xx` to preserve their integrity.

**Comment by Sebastian-Sole** [comment]
I apologize, you are correct, my .env variables are misconfigured. I have fixed this error and it works. I'm sorry for wasting your time, thank you for the help though

**Comment by emilyrohrbough** [comment]
@Sebastian-Sole I am glad you were able to get this working!

**Comment by benoitgrasset-cliq** [comment]
I am experiencing the same issue as @Sebastian-Sole, but I have not been able to resolve it.

All my API calls are defined in environment files (e.g., `.env.XXXX`). Locally, everything works perfectly. However, when I run my end-to-end Cypress tests on CI (using GitHub Actions), all the environment variables from `.env` files are undefined (e.g., `NEXT_PUBLIC_API_CONFIG_ENDPOINT`).

**My setup**

**CI Job Definition:**

```yaml
  cypress-run:
    runs-on: ubuntu-latest
    needs: [tests]
    env:
      CYPRESS_NEXT_PUBLIC_API_CONFIG_ENDPOINT: https://xxxxxxxxxxxxxxxxxxxxxx
      CYPRESS_NEXT_PUBLIC_API_STATS_ENDPOINT: ${{ secrets.NEXT_PUBLIC_API_STATS_ENDPOINT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: yarn build
          start: yarn dev
```

**Cypress Configuration:**

```javascript
import { defineConfig } from 'cypress';

export default defineConfig({
  projectId: 'cliq-analytics',
  e2e: {
    specPattern: 'cypress/e2e/**/*.cy.{ts,js,tsx,jsx}',
    baseUrl: 'http://localhost:3000',
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
    retries: {
      runMode: 2,
    },
  },
});
```


**Environment Variables in `.env:`**

```env
NEXT_PUBLIC_API_CONFIG_ENDPOINT = https://xxxxxxxxxxxxxxxxxxxxxx
NEXT_PUBLIC_API_ANALYSIS_ENDPOINT = https://xxxxxxxxxxxxxxxxxxxxxx
NEXT_PUBLIC_API_STATS_ENDPOINT = https://xxxxxxxxxxxxxxxxxxxxxx
NEXT_PUBLIC_API_TRACKING_ENDPOINT = https://xxxxxxxxxxxxxxxxxxxxxx
NEXT_PUBLIC_API_TRACKING_LINK_ENDPOINT = https://xxxxxxxxxxxxxxxxxxxxxx
NEXT_PUBLIC_API_GATEWAY_ENDPOINT = https://xxxxxxxxxxxxxxxxxxxxxx
NEXT_PUBLIC_API_CUSTOMER_ENDPOINT = https://xxxxxxxxxxxxxxxxxxxxxx
```

**The Problem**
On CI, the `process.env` variables (e.g., `NEXT_PUBLIC_API_CONFIG_ENDPOINT`) are undefined when running Cypress tests. This issue prevents my tests from running properly as they depend on the environment variables.

**Expected Behavior**
I want to be able to use `process.env` variables in my Next.js application and make them accessible during Cypress tests on CI.
