### ISSUE TITLE
Bitbucket commit information not available in dashboard 12.9.0

### ISSUE THREAD

**Issue by zaq42** [cypress-io/cypress#26301]
### Current behavior

![image](https://user-images.githubusercontent.com/24503523/228789299-771b28d3-b79e-405c-9838-c9e429146906.png)

Since the release of 12.9.0, the Dashboard shows "No commit message available" for runs triggered within BitBucket pipelines.

Rolling back the version running the tests to cypress/included:12.8.1 did not restore the behaviour

### Desired behavior

Until 12.9.0, git commit information was visible in dashboard and in messages to Slack.

### Test code to reproduce

Behaviour is reproducible in BitBucket pipelines.

### Cypress Version

12.9.0

### Node version

cypress/included:12.9.0

### Operating System

cypress/included:12.9.0

**Comment by zaq42** [comment]
It seems that running cypress 12.9.0 inside the docker image cypress/included:12.8.1 works.

To be clear, package.json specifies `"cypress": "^12.9.0",` 

The step in bitbucket pipelines is (summary):
```
    steps:
    - step: &smoke-test
        name: Smoke test
        image: cypress/included:12.8.1
        script:
        - yarn install && yarn run cypress run --record ...
```

This config does not exhibit the bug... git commit info is available in Dashboard.

Changing to `image: cypress/included:12.9.0` does not have git commit info in Dashboard.
