### ISSUE TITLE
Docker cypress factory M1 Cypress failed to start

### ISSUE THREAD

**Issue by romankhomitskyi** [cypress-io/cypress#26561]
### Current behavior

I'm not able to start  cypress in docker container 
I am getting the following error when running yarn cypress verify

![Screenshot 2023-04-21 at 17 46 36](https://user-images.githubusercontent.com/57874507/233666041-d1b00fc0-c80f-4ea8-a7de-ba5581fadf39.png)

### Desired behavior

Cypress should start

### Test code to reproduce

Docker file

```
ARG NODE_VERSION='18.13.0'
ARG CHROME_VERSION='110.0.5481.177-1'
ARG FIREFOX_VERSION='110.0.1'
ARG YARN_VERSION='1.22.19'


FROM cypress/factory

ENV TZ=Etc/UTC

WORKDIR /app/tests/Cypress
```

docker-compose 

  ```
cypress:
    image: registry.gitlab.com/cypress:1.0.0
    env_file:
      - .env
    environment:
      СYPRESS_numTestsKeptInMemory: 0
      CYPRESS_VERIFY_TIMEOUT: 100000
      CYPRESS_CACHE_FOLDER: "/app/tests/Cypress/.cache/Cypress"
    volumes:
      - app:/app
```

### Cypress Version

12.5.0

### Node version

18.13.0

### Operating System

M1 docker
