### ISSUE TITLE
Webkit browser( 1280x720) additional arguments needed to run cypress tests in Saucelabs 

### ISSUE THREAD

**Issue by rajenderbeeram** [cypress-io/cypress#27046]
### Current behavior

currently webkit browser opening with a static resolution of  1280x720 which is not a valid VM resolution . due to this our tests are not running with Sauce labs , we are seeing issues page distortion and page not loading properly. Sauce labs confirmed due to cypress limitation this issue is occurring. Saucelabs confirmed if cypress provides an additional arguments for webkit browser like chrome then this issue will be resolved . 

The static resolution value that Webkit is started in is not a supported resolution by Sauce Mac VMs
Webkit is opened with a default size of 1280x720, which is not a valid VM resolution, with no exposed function to modify the frame's size.

Currently we are running our cypress tests with help of saucelabs for webkit browser,chrome browser , mobile safari browser etc , we are depend on saucelabs for cross browser testing .

Find the attached image which shows page distorting and images not loading on page .

![Screenshot 2023-05-26 221546](https://github.com/cypress-io/cypress/assets/16860906/d9b67788-3b4b-4ca1-bf11-b0c0b10713c0)

### Desired behavior

We want to run cypress tests on webkit browser with Sauce labs , so if we have additional arguments for webkit then issue will be resolved .  as of not webkit browser is opening with static resolution of 1280x720 , can you please confirm  when we can expect additional arguements for webkit browser . 

for chrome browser cypress tests are working fine with Saucelabs but when we run for webkit browser then we are seeing page distortion issue .

### Test code to reproduce

```
apiVersion: v1
kind: cypress
defaults: {}
showConsoleLog: false
sauce:
  region: us-west-1
  concurrency: 30
  sauceignore: .sauceignore
cypress:
  configFile: cypress.config.js
  version: 12.6.0
  record: false
  key: ""
  reporters: []
suites:
- name: cypress - webkit safari
  browser: webkit
  platformName: macOS 12
  screenResolution: 1280x960
  browserVersion: '16'

  config:
    testingType: e2e
    specPattern:
    - 'cypress/e2e/*.*'
- name: cypress - Chrome
  browser: chrome
  platformName: Windows 10
  # screenResolution: 2048x1536
  # browserVersion: '16'

  config:
    testingType: e2e
    specPattern:
    - 'cypress/e2e/*.*'
    # config:
    #   specPattern: [ "cypress/e2e/*.*" ]
  # mode: sauce
# - name: cypress - mobile browser
#   browser: webkit
#   platformName: macOS 12
#   config:
#     testingType: e2e
#     specPattern:
    - 'cypress/e2e/*.*'
#     # config:
#     #   specPattern: [ "cypress/e2e/*.*" ]
#   mode: sauce
rootDir: .
artifacts:
  download:
    match:
    - '*'
    when: always
    directory: ./artifacts
```

### Cypress Version

12.10.0

### Node version

v20.1.0

### Operating System

Sauce labs mac OS 12
