### ISSUE TITLE
"Cypress verify" fails within kubernetes

### ISSUE THREAD

**Issue by luischre** [cypress-io/cypress#27209]
### Current behavior

I am currently trying to migrate our cypress pipeline from version 9.2.1 to 12.13.0. We deploy 10 cypress pods within kubernetes that execute our tests in parallel.
For version 9.2.1 we created a custom cypress docker image based on the included image we only needed to adjust the browsers and hence had to customize it a bit.
For version 12.13.0 I used the cypress/factory image with the following arguments:

> ARG CHROME_VERSION='114.0.5735.106-1'
> ARG FIREFOX_VERSION='102.12.0esr'
> ARG NODE_VERSION='18.16.1'
> ARG CYPRESS_VERSION='12.13.0'
> 
> FROM cypress/factory

Our pods are started within a jenkins pipeline with the following pod yaml:

```
kind: Pod
metadata:
  name: cypress-k8s
  labels:
    cypress: e2e
  annotations:
    fluentbit.io/exclude: "true"
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: cypress
              operator: In
              values:
              - e2e
          topologyKey: kubernetes.io/hostname
  securityContext:
    runAsUser: 0
  containers:
  - name: cypress-k8s
    securityContext:
      privileged: true
    image: ${params.CYPRESS_DOCKER_IMAGE}
    imagePullPolicy: Always
    command: ['cat']
    tty: true
    workingDir: /home/jenkins/agent/
    resources:
      requests:
        memory: "4Gi"
      limits:
        memory: "8Gi"
```

With version 9.2.1 we had the pipeline running without problems, with 12.13.0 however I can't get it to work properly. Some pods already encounter issue at the first start up of cypress with:

> Cypress failed to start.
> 
> This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies
> 
> Please refer to the error below for more details.
> 
> Command was killed with SIGTRAP (Debugger breakpoint): /root/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=334

Others start up fine but then later during test execution when picking up a new test suite encounter the same issue.

I took the following steps so far to narrow down the error:
- In order to discard the possibility that the test setup/configuration is wrong I now removed the test execution from the pipeline and am only starting the pod via the pipeline, once the pod is started I access the pod and execute `cypress/verify` --> same error
- In order to discard the possibility that my created docker image is the problem I tested the the cypress/included:12.13.0 image --> same error
- I've tested the same with a multitude of different images: 
    - our old custom 9.2.1 image, cypress/included:9.2.1, 9.5.0 and 9.5.1 could execute cypress verify successfully
    - 9.5.2, 9.5.3, 9.5.4, 9.6.0, 9.7.0, 10.0.0, 10.11.0, 12.13.0 failed during cypress verify with a multitude of different errors:

> ----------
> 
> Command was killed with SIGILL (Invalid machine instruction): /root/.cache/Cypress/10.11.0/Cypress/Cypress --no-sandbox --smoke-test --ping=147
> 
> ----------
> 
> Platform: linux-x64 (Debian - 11.4)
> Cypress Version: 10.11.0

> ----------
> 
> [127:0705/104615.520011:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [127:0705/104615.520120:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [127:0705/104615.521461:ERROR:bus.cc(397)] Failed to connect to the bus: Address does not contain a colon
> [127:0705/104615.521486:ERROR:bus.cc(397)] Failed to connect to the bus: Address does not contain a colon
> [127:0705/104615.534526:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
> libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
> [304:0705/104615.547230:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
> [304:0705/104615.554706:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
> 
> ----------
> 
> Platform: linux-x64 (Debian - 11.3)
> Cypress Version: 10.0.0

> ----------
> 
> [554:0705/140830.219953:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such f
> ile or directory
> [554:0705/140830.221181:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
> [554:0705/140830.221235:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
> [733:0705/140830.230876:WARNING:vaapi_wrapper.cc(586)] VAAPI video acceleration not available for swiftshader
> [733:0705/140830.231001:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is
> 
> ----------
> 
> Platform: linux-x64 (Debian - 11.3)
> Cypress Version: 9.5.3

The weird thing is that cypress verify does not always fail within those pods. The first execution most likely will fail with one of those errors, afterwards it will sometimes succeed and sometimes it will fail.

From the versions I tested it seems that after version 9.5.1 our setup breaks somehow but I can't explain why.

I found a couple of similar issues within github and tested whatever solutions were given but nothing has worked for me so far:
- Our pods are run as root, so these two although they sound pretty similar don't seem to apply: https://github.com/cypress-io/cypress/issues/22570 and https://github.com/cypress-io/cypress-docker-images/issues/847
- Tried all proposed solutions from here: https://github.com/cypress-io/cypress/issues/4624 but unfortunately nothing helped (clear cache, reinstall cypress...)

I am running out of ideas why after 9.5.1 it no longer works with our setup, if anyone spots anything within the setup, any help would be greatly appreciated.

### Desired behavior

Cypress verify should execute successfully within a kubernetes pod.

### Test code to reproduce

See above pod configuration which is used within a jenkins pipeline

### Cypress Version

12.13.0

### Node version

18.16.0

### Operating System

Linux 3.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
