### ISSUE TITLE
 cypress/included images "text file busy" with node 20

### ISSUE THREAD

**Issue by esetnik** [cypress-io/cypress#27707]
### Current behavior

Cypress crashes with  Command failed with exit code 126 "Text file busy" error

### Desired behavior

Same behavior as v12.17.3. The tests run correctly when using the cypress/included image.

### Test code to reproduce

Unable to provide at this time

### Cypress Version

v12.17.4

### Node version

v20.5.0

### Operating System

docker

### Debug Logs

```shell
cypress-1     | /usr/bin/env: 'node': Text file busy
cypress-1     | error Command failed with exit code 126.
cypress-1     | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Other

Seems to be related to

https://github.com/nodejs/docker-node/issues/1912#issuecomment-1699376950

**Comment by AtofStryker** [comment]
Hi @esetnik . Thank you for opening an issue. How are you invoking the docker image? Would you be able to provide a small reproduction for us to reproduce the issue on our end? I ran some of the included images this morning and they worked OK so I am wondering if it is something specific to your project.

**Comment by esetnik** [comment]
I am using the following custom image based on `cypress/included`:

```dockerfile
FROM cypress/included:12.17.4@sha256:102b34b9e4cb9895c44a74293c6931e7282535775045dd8b1c7608667a34c4b6

# renovate: datasource=repology depName=aur/msodbcsql versioning=loose
ARG MSODBCSQL_VERSION="18.1.2.1-1"

# renovate: datasource=repology depName=aur/mssql-tools versioning=loose
ARG MSSQL_TOOLS_VERSION="18.0.1.1-1"

ENV CI=1

RUN apt-get update && \
  apt-get install -y \
  git \
  gnupg \
  lsb-release && \
  wget -O - https://packages.microsoft.com/keys/microsoft.asc | apt-key add -  && \
  wget -O /etc/apt/sources.list.d/mssql-release.list https://packages.microsoft.com/config/debian/$(lsb_release -rs)/prod.list  && \
  apt-get update && \
  ACCEPT_EULA=Y apt-get install -y --no-install-recommends \
  msodbcsql18=${MSODBCSQL_VERSION} \
  mssql-tools18=${MSSQL_TOOLS_VERSION} \
  locales && \
  echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
  locale-gen && \
  rm -r /var/lib/apt/lists/* && \
  ln -s /opt/mssql-tools18/bin/sqlcmd /usr/bin/sqlcmd


RUN mkdir -p /e2e
RUN git config --global --add safe.directory /e2e

WORKDIR /e2e

COPY package.json yarn.lock .npmrc ./
COPY patches ./patches

RUN yarn install --frozen-lockfile --unsafe-perm=true --allow-root

RUN npx cypress verify

COPY . .
```

Then in my docker compose:
```yml
  cypress:
    # image: (the image built in previous step)
    environment:
      PERCY_TOKEN: ${PERCY_TOKEN}
      PERCY_BRANCH: ${PERCY_BRANCH}
      PERCY_PULL_REQUEST: ${PERCY_PULL_REQUEST}
      PERCY_PARALLEL_TOTAL: ${CIRCLE_NODE_TOTAL}
      PERCY_PARALLEL_NONCE: ${CIRCLE_BUILD_NUM}
      NO_COLOR: 1
    command: >
      npx percy exec --verbose --parallel -- cypress run
        --record
        --key redacted
        --ci-build-id ${CIRCLE_BUILD_NUM}
        --parallel
        --group circleci-chrome
        --browser chrome
```

The above works on v12.17.3 and below but stops working on v12.17.4 and v13.0.0
