### ISSUE TITLE
Github containers executes same feature files for BDD framework

### ISSUE THREAD

**Issue by sait-yamdu** [cypress-io/cypress#27776]
### Current behavior

I have two different problem. 

1.As you can see from the screenshot I have 2 containers. When I execute on Github actions with Cypress Dashboard, I can see that two different machines running at the same time. Here is the screenshot of two different machines in Cypress Dashboard after I started on Github.
![image](https://github.com/cypress-io/cypress/assets/143401052/aa1b39d9-caaa-47d3-a513-5e79c72b8ea7)

2. My second problem is that, both the machines are trying to execute same feature file -- in my case **employeesAndStaff.**
Here is the screenshot of one machine -- which is passed for EmployessAndStaff test.
![image](https://github.com/cypress-io/cypress/assets/143401052/d8ba0032-ce32-452b-a5e9-e19824df10e1)
Here is the another screenshot of second machine -- which is getting fail for EmployeesAndStaff test. That means both of the machines are trying to execute same feature file.
![image](https://github.com/cypress-io/cypress/assets/143401052/42ce490a-1de3-439d-93c5-77fa2b5c1dc0)

In addition here is the screenshot of my yaml file and my current project tree for cypress.
![yamlFile](https://github.com/cypress-io/cypress/assets/143401052/04f678c5-9cb5-4b4f-9d40-f13dc90708aa)

### Desired behavior

1. For the first one, I need exactly what Gleb Bahmutov is did on his Youtube channel. I need to see only one run in Cypress Dashboard.
![image](https://github.com/cypress-io/cypress/assets/143401052/b0820c51-a85e-49ff-bd43-68568f099691)

2. For the second one, as you already thought, every container should run separate feature file... it's really does not important the sequence of feature files. I just need to reduce end-to-end testing time. That's all.

### Test code to reproduce

Repo with reprodiction ---> https://github.com/saittalhabakir/BDD-Parallel

### Cypress Version

12.17.4

### Node version

v16.14.0

### Operating System

Windows 22621.2215

**Comment by MikeMcC399** [comment]
@sait-yamdu 

This issue was also discussed in https://discord.com/channels/755913899261296641/1149339980179718244.

The reason that all specs are run twice is that there are two containers defined in [.github/workflows/main.yaml](https://github.com/saittalhabakir/BDD-Parallel/blob/main/.github/workflows/main.yaml), however Cypress is being run without the necessary [cypress run --parallel](https://docs.cypress.io/guides/guides/command-line#cypress-run-parallel) flag, so the Cypress Cloud does no load balancing.

The workflow [.github/workflows/main.yaml](https://github.com/saittalhabakir/BDD-Parallel/blob/main/.github/workflows/main.yaml) uses a [Custom test command](https://github.com/cypress-io/github-action#custom-test-command) parameter `command: npm run cy-run-e2e` which resolves through [package.json](https://github.com/saittalhabakir/BDD-Parallel/blob/main/package.json) to 

`"cy-run-e2e": "set SCOPE=e2e && npx cypress run --record --key ede2d07f-3d79-4288-a677-9c7a724ac503"`. 

There is no `--parallel` option in the script definition `cy-run-e2e`.

The workflow parameter `parallel: true` has no effect. It is ignored. This is mentioned in the [README > Custom test command](https://github.com/cypress-io/github-action#custom-test-command) caution notice which says:

> Caution: using the action parameter command causes multiple other parameters to be ignored including: auto-cancel-after-failures, browser, ci-build-id, command-prefix, component, config, config-file, env, group, headed, parallel, project, publish-summary, quiet, record, spec and tag.

Current workflow [.github/workflows/main.yaml](https://github.com/saittalhabakir/BDD-Parallel/blob/main/.github/workflows/main.yaml):

```yml
name: e2e-tests
on: [workflow_dispatch]
jobs:
  cypress-run:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1,2]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy-run-e2e
          headed: true
          record: true
          parallel: true
          config-file: Yamdu-Automation\cypress.config.js
          wait-on: 'https://scotty.yamdu.com'
        env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            SPLIT: true
```

Possible partial replacement for the `Cypress run` step:

```yaml
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          headed: true
          record: true
          parallel: true
        env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            SCOPE: e2e
```

- `cypress-io/github-action@v6` already causes `npx cypress run` to be called (provided there is no `command` parameter set)
- `set SCOPE=e2e` can be moved to `env: / SCOPE: e2e`
- There was no file `Yamdu-Automation\cypress.config.js` in the repo. Possibly this line can be deleted.
- There is no need for `wait-on: 'https://scotty.yamdu.com'` since https://scotty.yamdu.com is online already. This parameter is only useful if a dev server is being started and Cypress needs to wait for it to finish starting up
- Providing that `CYPRESS_RECORD_KEY` is set to `ede2d07f-3d79-4288-a677-9c7a724ac503` then there is no need to pass it explicitly in a command line
- It's not clear what the purpose of `SPLIT: true` is supposed to be. It does not seem to be used anywhere.
