### ISSUE TITLE
Introduce non case sensitive matching for cy.contains()

### ISSUE THREAD

**Issue by James-E-Adams** [cypress-io/cypress#2785]
### Current behavior:
`cy.contains('Capital Sentence')` does not match

`<span class="capitalize"> capital sentence </span>`

where:
```css
.capitalize {
   text-transform: capitalize;
}
```

Is this expected? 

### Desired behavior:

I assumed it would match because that's what the user sees. However the underlying text in the DOM is indeed `capital sentence`.

### Versions

Cypress: 3.0.1
Chrome, Mac OS Mojave
