### ISSUE TITLE
Github actions - npm install flags

### ISSUE THREAD

**Issue by Multinite** [cypress-io/cypress#28647]
### What would you like?

Currently, within my project, to install packages, I must include the `--force` flag to ensure NPM installs despite some of my dependencies having version compatibility issues. By adding a new key within the cypress step called `install_flags`, you could allow users to enter any flags to go along with the npm install.

Example:
```yml
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          flags: 
             - "--force"
          browser: chrome
```

### Why is this needed?

This is useful for my project and potentially many others because some larger projects may contain version dependency errors, and in our case, our app works perfectly fine despite those conflics.
We plan to include Cypress testing within Github actions, but every time the test starts, it fails simply because it fails to install all the required NPM packages within the project.

Image of error occurring in Github actions:
![image](https://github.com/cypress-io/cypress/assets/145994855/5568c3cd-ac97-45f0-8873-2ef1b8e66233)
