### ISSUE TITLE
Missing browserCriClient in connectToNewSpec

### ISSUE THREAD

**Issue by karolis-kimtys** [cypress-io/cypress#28909]
### Current behavior

SvelteKit project runs tests inside GitLab CICD and in some occasions it fails with "Missing browserCriClient in connectToNewSpec" message after running all Cypress tests.

### Desired behavior

Cypress tests should run and pass inside CICD pipeline without any failures. 

### Test code to reproduce

Possibly setting up a basic SvelteKit project and trying to run Cypress tests inside GitLab CICD.
---- .gitlab-ci.yml
```yml
.tests-setup:
  stage: runtests
  image: cypress/browsers:latest
  script:
    - npm install
    - npm run sync
    - npm run build
    - npm run preview &
    - npx wait-on https://localhost:5173
    - npx cypress run --record --browser chrome
  ```
----

### Cypress Version

v13.5.0

### Node version

18-alpine

### Operating System

GitLab Runner saas-linux-small-amd64 

### Debug Logs

```shell
Timed out waiting for the browser to connect. Retrying...
Missing browserCriClient in connectToNewSpec
Error: Missing browserCriClient in connectToNewSpec
    at Object.connectToNewSpec (<embedded>:4438:48137)
    at Object.connectToNewSpec (<embedded>:4438:27043)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async v.relaunchBrowser (<embedded>:4504:37530)
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```
