### ISSUE TITLE
Cypress sets :focus and :focus-visible after .click()

### ISSUE THREAD

**Issue by ghost** [cypress-io/cypress#29388]
### Current behavior

Cypress sets :focus and :focus-visible after .click().

Here are the styles of the button:

```css
outline: red none 3px;

&:focus {
  outline-style: dotted;
}

&:focus-visible {
  outline-width: 10px;
}
```

when the button with such styles is clicked in Cypress, the outline is visible and has dotted style with 10px size.

### Desired behavior

During clicking the button gets only :focus in real browser (Chrome v124)

### Test code to reproduce

```js
cy.get('[data-testid=btn]').click()
```

### Cypress Version

13.6.4

### Node version

v18.16.1

### Operating System

macOS 14.4.1
