### ISSUE TITLE
baseUrl in cypress.config.ts won't get overwritten by setting CYPRESS_baseUrl or CYPRESS_BASE_URL 

### ISSUE THREAD

**Issue by Baluditor** [cypress-io/cypress#29556]
### Current behavior

I have the following `cypress.config.ts`:
```ts
import { defineConfig } from 'cypress';

export default defineConfig({
  e2e: {
    experimentalModifyObstructiveThirdPartyCode: true,
    baseUrl: 'http://localhost:3000',
  },

  component: {
    devServer: {
      framework: 'react',
      bundler: 'vite',
    },
  },

  env: {
    baseUrl: 'http://localhost:3000',
    authUrl: 'https://localhost:4013',
    ... 
  },
});
```

and my `test.yml` file:
```yml
name: Run tests
on: [pull_request]

jobs:
  cypress-e2e-run:
    name: Cypress E2E tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: add deployment configuration for main branch
        run: |
          cat testing.env.conf >> $GITHUB_ENV

      - name: Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
        env:
          CYPRESS_userName: ${{ secrets.CYPRESS_USER_NAME_TESTING }}
          CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD_TESTING }}
          # I tried with CYPRESS_AUTH_URL and CYPRESS_BASE_URL, same result
          CYPRESS_authUrl: ${{ env.VITE_APP_AZURE_B2C_AUTHORITY }}
          CYPRESS_baseUrl: ${{ env.swa_preview_hostname_first_part }}-${{ github.event.pull_request.number }}.${{ env.swa_preview_hostname_second_part }}
```

My issue is that the `baseUrl` will be `http://localhost:3000` no matter what I do. 
I see that the env vars are set in Github Workflow:
![image](https://github.com/cypress-io/cypress/assets/34071416/208ff67b-8970-4fb4-bc7b-d1a5527dd4d7)

According to the docs this should work.

### Desired behavior

My expectations is that baseUrl overwritten.

### Test code to reproduce

N/A

### Cypress Version

Cypress package version: 13.8.1

### Node version

Node version: 18.17.1

### Operating System

ubuntu-22.04

**Comment by Baluditor** [comment]
I've done some more testing and I found the following:
```yml
 # Base URL overwrite is somewhat working. Withouth it, the test would run agains the localhost. Setting it solves that issue, but accessing it with cypress.env('baseUrl') will still returns 'localhost'.
CYPRESS_baseUrl: ${{ env.swa_preview_hostname_first_part }}-${{ github.event.pull_request.number }}.${{ env.swa_preview_hostname_second_part }}
 # But baseUrl still can't be used in the tests, thus setting a hostUrl variable which will have the correct value.
CYPRESS_hostUrl: ${{ env.swa_preview_hostname_first_part }}-${{ github.event.pull_request.number }}.${{ env.swa_preview_hostname_second_part }}
```

So basically, I had the assumption that overwriting the baseUrl would affect the `e2e baseUrl` too, but this dosen't seem to work.
