### ISSUE TITLE
GitHub Actions ( Cypress Runs) || Getting "Run finished" immediately when "Run Starts"

### ISSUE THREAD

**Issue by janavi-p** [cypress-io/cypress#29811]
### Current behavior

![image](https://github.com/cypress-io/cypress/assets/132589418/adf3655e-1ecc-40f6-9ced-439015d4095e)

### Desired behavior

GitHub action should initiate test execution and run it completely without any deviations

### Test code to reproduce
```yml
jobs:
  cypress-run:
    name: 'Cypress Test on Ubuntu'
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1] # Uses 1 parallel instance
        
    steps:
      - name: 'Checkout the repository'
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: 'git branch info'
        run: | 
          git branch

      - name: 'Building web application to be tested'
        run: yarn
        
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          config-file: cypress.config.js
          spec: "cypress/e2e/specs/regression-specs/staging/**/*.cy.js"
          group: 'UI-Electron'
          record: true
          parallel: true
        
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
```
### Cypress Version

13.13.0

### Node version

v20.13.1

### Operating System

macOS 14.5

### Other

Found an existing bug With Cypress : https://github.com/cypress-io/github-action/issues/147
This seems to have been fixed in v2.2
I am already using v6
