### ISSUE TITLE
Tests always failling in GitHub Actions

### ISSUE THREAD

**Issue by fabu1985** [cypress-io/cypress#30183]
### Current behavior

  This is my job :
  ```yml
  cypres_test:
    runs-on: ubuntu-22.04
    name: Cypress Tests
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # Setup Yarn Berry
      - name: Set up Yarn
        run: |
          npm install -g yarn@berry
          yarn set version berry
          yarn --version

      # Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_SEA_0E6F37A10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          app_build_command: "yarn build:mocked" # Comando de build personalizado
          skip_app_build: false
          skip_api_build: true
  
      # Run Cypress tests
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        env: 
          EEO_AUTOMATION_BASE_URL: https://calm-sea-0e6f37a10-139.centralus.3.azurestaticapps.net
        with:
          config: 'baseUrl=https://calm-sea-0e6f37a10-139.centralus.3.azurestaticapps.net'
          command: yarn automation:e2e
          wait-on: 'https://calm-sea-0e6f37a10-139.centralus.3.azurestaticapps.net'
          wait-on-timeout: 110
```

So, the result is always the same

```
AssertionError: Timed out retrying after 0ms: Expected to find element: `[data-testid^="welcomeHeader"]`, but never found it.
```

### Test code to reproduce

https://github.com/fabu1985/algo/actions/runs/10704642103/job/29678128833?pr=12

### Cypress Version

13.14.1

### Node version

20.14.0

### Operating System

ubuntu

### Other

I check it running a simple test against Google page, and worked ok. It´s means the latest versions for cypress and libraries updated, are not the problem, aparently.
I harcoded the baseurl and the problem still happening.

I´ll appreciatte u any idea o suggestion... thanks!!!
