### ISSUE TITLE
Browser doesn't open due to Warning:Cypress could not verify that the server set as your 'baseUrl' is running: http://localhost:3000 

### ISSUE THREAD

**Issue by pkamath123** [cypress-io/cypress#3122]

**Comment by jennifer-shehane** [comment]
Hey @pkamath123, I think the warning is likely unrelated to Chrome not being able to open. 

When opening cypress, could you try to run Cypress in [debug mode](https://docs.cypress.io/guides/guides/debugging.html#Debug-the-Command-Line) to print some extra logs to post here? 

Also, just to narrow down the possible causes, could you just run Cypress in a brand new project to see if Chrome opens in there? So:

```
mkdir my-project
cd my-project
npm init -f
npm install --save-dev cypress
./node_modules/.bin/cypress open
```

Try and run one of the examples we scaffolded there.

**Comment by jennifer-shehane** [comment]
Could you possibly provide a screenshot / video / gif of what is happening when you click. I'd like to see what you mean by 'buffering'. 

Also, could you run Cypress in [debug mode](https://docs.cypress.io/guides/guides/debugging.html#Debug-the-Command-Line) mode and print the logs here?

**Comment by pkamath123** [comment]
When i use the DEBUG=cypress:* cypress open command , i get the error : -bash: cypress: command not found. Please see the screenshot for the . issue where the chrome doesnt open
![screen shot 2019-01-30 at 9 35 59 am](https://user-images.githubusercontent.com/46544250/51996768-a84cfc00-2472-11e9-9096-394e5fd3f58f.png)

screenshot for chrome not opening is below.
![screen shot 2019-01-30 at 9 35 59 am](https://user-images.githubusercontent.com/46544250/51997026-28736180-2473-11e9-9736-8b4106d0a018.png)

**Comment by jennifer-shehane** [comment]
Hey @pkamath123, try running the command below:

```
DEBUG=cypress:* ./node_modules/.bin/cypress open
```

**Comment by pkamath123** [comment]
Hi @jennifer-shehane , 
Thank you for helping me so far with debugging this issue, i really appreciate your continuous help, I have attached the cypresslog file after i ran the debug command. 
[cypressLog.txt](https://github.com/cypress-io/cypress/files/2818255/cypressLog.txt)

when i use yarn to update to latest version of cypress i get the  error saying there is no version 3.1.5
Please see the attached image for the update . 
![screen shot 2019-01-31 at 10 00 30 am](https://user-images.githubusercontent.com/46544250/52071288-e19f6d80-253f-11e9-837f-874a620d9504.png)
Thank you once again.

**Comment by saas2813** [comment]
I got the "Cypress failed to verify that your server is running." problem and solved it when I realised that the /etc/hosts file did not include a line:
127.0.0.1       localhost
Adding info here for Googlers, took me way too long to find it.

**Comment by GettinDatFoShow** [comment]
> I got the "Cypress failed to verify that your server is running:" problem and solved it when I realised that the /etc/hosts file did not include a line:
> 127.0.0.1 localhost
> Adding info here for Googlers, took me way too long to find it.

what file is this exactly? i was unable to locate it.

**Comment by saas2813** [comment]
@GettinDatFoShow On Mac OS X and Unix/Linux there are system configuration files that describes the computers network environment. The most basic one is the file "hosts" in the directory "/etc" it contains locally defined mappings of names for network resources. The corresponding file on Windows seems to be (if Google is my friend...) c:\windows\system32\drivers\etc\hosts but I would be surprised if it was causing problems on a windows machine, unless someone already had edited it. You will need to be administrator to be able to write to it.

**Comment by GettinDatFoShow** [comment]
> @GettinDatFoShow On Mac OS X and Unix/Linux there are system configuration files that describes the computers network environment. The most basic one is the file "hosts" in the directory "/etc" it contains locally defined mappings of names for network resources. The corresponding file on Windows seems to be (if Google is my friend...) c:\windows\system32\drivers\etc\hosts but I would be surprised if it was causing problems on a windows machine, unless someone already had edited it. You will need to be administrator to be able to write to it.

thanks, and i am using bash on windows so i am not sure if that is an issue but also in the cicd linux is being used. im curious if there is a way to make sure thats set before the cypress code runs.

**Comment by s-gbz** [comment]
Just encountered the same error when using GitHub Action.
The solution is to wait for the server to start.
Use the `wait-on` parameter.
I'm not sure if `start` is mandatory, but it's listed in the [examples](https://github.com/cypress-io/github-action#wait-on) so..

```
      - name: Run cypress e2e tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run e2e
          browser: chrome
          headless: true
          wait-on: 'http://localhost:4200'
```

Here's the complete workflow file for running the whole Angular test suite:

```
name: run-tests

on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js 12.14
        uses: actions/setup-node@v1
        with:
          node-version: 12.14
          
      - name: Install dependencies
        run: npm install

      - name: Run headless unit tests
        run: npm run test-headless

      - name: Run cypress e2e tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run e2e
          browser: chrome
          headless: true
          wait-on: 'http://localhost:4200'
```
