### ISSUE TITLE
Tests fail on circleci but success locally

### ISSUE THREAD

**Issue by mi-mazouz** [cypress-io/cypress#3201]
### Current behavior:

- circle-ci config:

```yml
version: 2
orbs:
  cypress: cypress-io/cypress@1.0.0
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: phoenix-deploy
jobs:
  build:
    docker:
      - image: cypress/browsers:chrome67
    working_directory: ~/admin
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Tests
          command: yarn run test:all
```

- package.json's scripts:
```json
  "scripts": {
    "start": "react-scripts start",
    "cypress:run": "cypress run --browser chrome",
    "test:all": "yarn run test:unit && yarn run test:end2end",
    "test:unit": "REACT_APP_ENV=test react-scripts test --env=jsdom",
    "test:end2end": "start-server-and-test start http://localhost:3000 cypress:run",
    "eject": "react-scripts eject"
  }
```

- test:
![screen shot 2019-01-23 at 18 51 38](https://user-images.githubusercontent.com/24244248/51626532-085a1480-1f40-11e9-9c2f-18d74eaaa545.png)

- circle-ci error:
![screen shot 2019-01-23 at 18 52 00](https://user-images.githubusercontent.com/24244248/51626553-1445d680-1f40-11e9-99cb-c3ce7a1f08b5.png)

### Versions

![screen shot 2019-01-23 at 18 53 19](https://user-images.githubusercontent.com/24244248/51626634-41928480-1f40-11e9-8d0e-08087bf1b87a.png)

Any ideas? It works well locally.
Maybe I didn't understand something but I followed this documentation:

https://on.cypress.io/continuous-integration#Solutions
