### ISSUE TITLE
Server is running but 404s on visit to application during cypress run

### ISSUE THREAD

**Issue by TanvirAlam** [cypress-io/cypress#3245]
### Current behavior:

Circle config.yml:

```yml
frontend-test:
    <<: *defaults
    docker:
      - image: cypress/base:8
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test:cypress
```

Package.json:

```json
{
    "cypress:run": "cypress run",
    "start": "webpack-dev-server --config ./webpack.config.js --mode development",
    "test:cypress": "start-server-and-test start http://localhost:8080 cypress",
    "cypress": "cypress run",
}
```

cypress:json:

```json
{
    "baseUrl": "http://localhost:8080/",
    "fixturesFolder": "cypress/fixtures",
    "integrationFolder": "cypress/integration",
    "pluginsFile": "cypress/plugins",
    "screenshotsFolder": "cypress/screenshots",
    "supportFile": "cypress/support",
    "videosFolder": "cypress/videos"
}
```

webpack.config.js:

```js
module.exports = {
    entry: "./public/js/app.js"
}
```

### GETTING ERROR:

![circlecieror](https://user-images.githubusercontent.com/3250040/51928387-1c958a00-23f6-11e9-80f8-2ed8f2a6c760.gif)

### Desired behavior:

it says:

```
CypressError: cy.visit() failed trying to load:

http://localhost:8080/login

The response we received from your web server was:

  > 404: Not Found

```

I have been trying this past 4 days, I don't know what is wrong, please help

The front-end is vuejs, hence the login page is `login.vue` which is loading `vue-router`
