### ISSUE TITLE
error while loading shared libraries: libffmpeg.so — gitlab, cypress/base:10

### ISSUE THREAD

**Issue by a-x-** [cypress-io/cypress#3473]
### Current behavior:

`error while loading shared libraries: libffmpeg.so: cannot open shared object file: No such file or directory`

### Steps to reproduce: (app code and test code)

```yml
...

cache:
  paths:
    - ~/.npm
    - ~/.cache

...

e2e-tests:
  image: cypress/base:10
  scripts:
    - npm run ci:mocks # faked backend background process
    - npm run ci:start # dev static server background process
    - npm ci && cypress verify && cypress run
```
### Versions

- "cypress": "3.1.0",
- latest enterprise gitlab
- cypress/base:10
