### ISSUE TITLE
Text only visible for screenreader is considered "visible"

### ISSUE THREAD

**Issue by plehnen** [cypress-io/cypress#3624]
### Current behavior:

For a11y reasons some elements have the following css class:

```css
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  margin: -1px;
  padding: 0;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  border: 0;
}
```

Those are not visible in the browser.
Still cypress result `true` if I check for `should('be.visible')`.

### Desired behavior:

I want to be able to use cypress to check if a text is really visible.

### Steps to reproduce: (app code and test code)

Add the mentioned css class to any element and check for it's visibility.
It is not visible, but will be found as visible.

### Versions

3.1.5, Windows 10, Chrome
