### ISSUE TITLE
Cypress docker gitlab example failing in test stage

### ISSUE THREAD

**Issue by vctormb** [cypress-io/cypress#3906]
### Current behavior:
I'm trying to add Cypress to the pipeline on Gitlab using this example [cypress-example-docker-gitlab](https://gitlab.com/cypress-io/cypress-example-docker-gitlab). When it goes to the ``cypress-e2e`` or ``cypress-e2e-chrome`` job it fails.  

The error message says: ``ERROR: No files to upload ``

![image](https://user-images.githubusercontent.com/13953703/55688698-cc84f780-5951-11e9-9c89-1c9c74f535fe.png)

### Desired behavior:

It should run the job correctly.

### Steps to reproduce: (app code and test code)

```yaml
# .gitlab-ci.yml
# I'm using yarn

stages:
  - build
  - test

variables:
  npm_config_cache: /builds/vctormb/testing-cypress/.npm
  CYPRESS_CACHE_FOLDER: /builds/vctormb/testing-cypress/cache/Cypress

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.cache

install:
  image: cypress/base:10
  stage: build

  script:
    - yarn install --frozen-lockfile
    - $(yarn bin)/cypress verify

cypress-e2e:
  image: cypress/base:10
  stage: test
  script:
    - $(yarn bin)/cypress run
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - cypress/screenshots
      - cypress/videos

cypress-e2e-chrome:
  image: cypress/browsers:chrome67
  stage: test
  script:
    - $(yarn bin)/cypress run --browser chrome
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - cypress/screenshots
      - cypress/videos
```

### Versions
"cypress": "3.2.0"

**Comment by bahmutov** [comment]
Try not using chrome browser option - because video generation only is possible when using the built in Electron browser

**Comment by vctormb** [comment]
@bahmutov I deleted the ``cypress-e2e-chrome`` job and I still see the same error. Don't know what to do.

**Comment by MarS919** [comment]
What's the result of the `install` job (especially the output of `$(yarn bin)/cypress verify`)? It seems it can't find the cypress binary at all.

**Comment by vctormb** [comment]
I noticed that when the `build` stage finishes and it goes to the `test` stage the node_modules doesn't exist. So if I put yarn install in the test stage it will work. Any tips?

```yaml 
cypress-e2e:
  image: cypress/base:10
  stage: test
  script:
    - yarn install    
    - $(yarn bin)/cypress run  
```
