### ISSUE TITLE
Integration with Solano CI

### ISSUE THREAD

**Issue by radicalsauce** [cypress-io/cypress#397]
Any chance for documentation on setting up/running Cypress on Solano?

**Comment by brian-mann** [comment]
Should be the same as all other CI providers.

https://docs.cypress.io/docs/continuous-integration

**Comment by jennifer-mann** [comment]
An example of a `solano.yml` config file that should run tests:

```yml
nodejs:
  version: '5.10.1'
hooks:
  pre_setup: npm install cypress-cli
test_pattern:
  - cypress/integration/*_spec.js
tests:
  - cypress ci
```
