### ISSUE TITLE
Parallel CI: Rerunning 1 machine with failed tests reruns ALL spec files instead of only previously failed spec files assigned to that machine.

### ISSUE THREAD

**Issue by garyluu** [cypress-io/cypress#3995]
### Current behavior:
After running parallel tests on 3 machines/jobs on Travis CI; If for whatever reason we wanted to restart a Travis CI machine/job, it will re-run all the Cypress tests on that one Travis CI machine/job

### Desired behavior:

Restarting a single Travis CI machine/job would only re-run the Cypress tests that previous ran on that machine/job

### Versions

Cypress 3.2.0

**Comment by jennifer-shehane** [comment]
This shouldn't happen.

Can you provide more information about your Travis setup. A link to the Travis project would be most ideal (feel free to email support@cypress.io)

But, if you can provide the Travis yml file you run / how you run the cypress commands. Thanks!

**Comment by garyluu** [comment]
https://travis-ci.org/dockstore/dockstore-ui2/builds/523057315

Each machine took about 21 mins (as expected).  I restarted the 2nd job fairly soon after it failed and now at the time of writing it's surpassed 21 mins and expected to time out at 50 mins.

Relevant code snippets:
.travis.yml
```
jobs:
  include:
    - stage: integration test
      name: "Parallel Cypress Tests"
      script:
        - ./scripts/run-travis-script.sh

    - stage: integration test
      name: "Parallel Cypress Tests"
      script:
        - ./scripts/run-travis-script.sh

    - stage: integration test
      name: "Parallel Cypress Tests"
      script:
- ./scripts/run-travis-script.sh
```
where ./scripts/run-travis-script.sh is

```#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset
set -o xtrace

npm run webservice
npm run build
npm run start &
./scripts/wait-for.sh
cypress run --record --config defaultCommandTimeout=10000 --parallel --group 3x-electron

```
