### ISSUE TITLE
Post install script fails in Google Cloud Build

### ISSUE THREAD

**Issue by znat** [cypress-io/cypress#4806]
I run tests in a `docker-compose` setup inspired by this example: https://github.com/cypress-io/cypress-example-docker-compose

It works perfectly locally, but when running in on Google Cloud Build I get this cryptic error

### Current behavior:

```
e2e_1       | wait-for-it.sh: botfront:3000 is available after 3 seconds
e2e_1       | internal/modules/cjs/loader.js:582
e2e_1       |     throw err;
e2e_1       |     ^
e2e_1       | 
e2e_1       | Error: Cannot find module '/root/.npm/_npx/1/lib/node_modules/cypress/index.js'
e2e_1       |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
e2e_1       |     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
e2e_1       |     at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
e2e_1       |     at startup (internal/bootstrap/node.js:285:19)
e2e_1       |     at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
e2e_1       | npm ERR! code ELIFECYCLE
e2e_1       | npm ERR! errno 1
e2e_1       | npm ERR! cypress@3.4.0 postinstall: `node index.js --exec install`
e2e_1       | npm ERR! Exit status 1
e2e_1       | npm ERR! 
e2e_1       | npm ERR! Failed at the cypress@3.4.0 postinstall script.
...
```
Files are located here: https://github.com/botfront/botfront/tree/ci/github-check/botfront/cypress

Cypress Dockerfile (here):

```
FROM cypress/base:10
WORKDIR /app

# dependencies will be installed only if the package files change
COPY package.json .
COPY package-lock.json .

# by setting CI environment variable we switch the Cypress install messages
# to small "started / finished" and avoid 1000s of lines of progress messages
# https://github.com/cypress-io/cypress/issues/1243
ENV CI=1
RUN npm ci
# verify that Cypress has been installed correctly.
# running this command separately from "cypress run" will also cache its result
# to avoid verifying again when running the tests
RUN npx cypress verify
RUN mkdir /scripts
COPY  ./wait-for-it.sh /scripts/
RUN chmod +x /scripts/wait-for-it.sh 
ENV WAIT_FOR_TIMEOUT=90
ENTRYPOINT ["/bin/bash"]
CMD ["-c", "/scripts/wait-for-it.sh $BOTFRONT_HOST -s -t $WAIT_FOR_TIMEOUT -- npx cypress run"]
```
Docker compose
```
version: '3.7'
services:
  e2e:
    image: gcr.io/botfront-project/cypress-runner:3.4.0
    volumes:
      - ../:/app
    depends_on: 
      - botfront
    env_file:
      - .env.cypress

  botfront:
    image: gcr.io/botfront-project/botfront:e2e
    container_name: botfront-app
    restart: always
    ports:
      - '8888:3000'
    depends_on:
      - mongo
    env_file:
      - .env.cypress
    environment:
      PORT: 3000
 
  mongo:
    image: 'mongo:latest'
    container_name: botfront-mongo
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - .env.cypress
```
cloubuild.yaml

```
steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  dir: /workspace/botfront/cypress
  args:
  - --destination=gcr.io/$PROJECT_ID/cypress-runner:3.4.0
  - --cache=true
  - --cache-ttl=24h
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/botfront:e2e
  - --cache=true
  - --cache-ttl=12h
- name: 'gcr.io/cloud-builders/docker'
  args: [ "build", "-t", "gcr.io/$PROJECT_ID/botfront:e2e", "."]
- name: gcr.io/$PROJECT_ID/docker-compose
  dir: /workspace/botfront/cypress
  args:
    - up
    - --abort-on-container-exit
    - --exit-code-from
    - e2e
timeout: 2700s
images:
   - gcr.io/$PROJECT_ID/botfront:e2e
   - gcr.io/$PROJECT_ID/cypress-runner:3.4.0
```
### Desired behavior:

Tests should run

### Steps to reproduce: (app code and test code)

1. Clone https://github.com/botfront/botfront and checkout the `ci/github-check` branch.
2. Create a project on GCP and enable Cloud Build
3. Install `gcloud` and set it up with `gcloud init``
4. gcloud builds submit --config cloudbuild.yaml
