### ISSUE TITLE
CSS keyframe animations are re-run when hovering over steps in the cypress UI

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress#5348]
### Current behavior:

When you hover over a step in the "timetravel" history (which is a very cool feature, BTW), if you have CSS keyframe animations, they will re-run, which is odd and potentially misleading.

### Desired behavior:

The DOM history should look exactly like it did at that point in time.

### Steps to reproduce: (app code and test code)

I have an error panel that comes down from the top of the screen when it is placed in the DOM. This is accomplished via CSS:

```css
    #error-panel {
      animation: flash-error 200ms ease-in-out;
    }

    @keyframes flash-error {
      0% {
        transform: translateY(-100%);
      }
      100% {
        transform: translateY(0%);
      }
    }
```

When I hover the mouse over a previous step in the Cypress UI, the panel animates down every time.

Here's a repo that shows this issue:  https://github.com/fr0/cypress-snapshot-hover

### Versions

Cypress 3.4.1
Mac OS
