### ISSUE TITLE
Do not truncate cy.log() in Command Log

### ISSUE THREAD

**Issue by pitgrap** [cypress-io/cypress#5625]
This is a feature request.

### Current behavior:

Long messages in `cy.log()` gets truncated to a single line. On screenshots the panel of cyress is always very narrow, so the log is almost never readable.

![screenshot_165](https://user-images.githubusercontent.com/227391/68385575-61570a00-015a-11ea-93c4-78ce020e50b4.png)

### Desired behavior:

It would be great to *not* truncate or at least support a flag to disable the truncation in `cy.log()`. Especially URLs and other import informations should be displayed.

![screenshot_166](https://user-images.githubusercontent.com/227391/68385589-6916ae80-015a-11ea-849c-c208f6ccfef3.png)

### Steps to reproduce: (app code and test code)

```js
  it("example", () => {
    cy.log("Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et");
    cy.log("https://docs.cypress.io/api/commands/log.html#Syntax");
  });
```

### Versions

3.4.1 to 3.6.0
chrome78

### Details

The following CSS rule is responsible for all message-types (`cypress_runner.css:4016`):

```css
.reporter .command-message {
  white-space: nowrap;
   ...
}
```

Maybe add a style just for the log (or all entries like URLs in cy.request()?):

```css
.reporter .command-name-log .command-message {
  white-space: initial;
  word-break: break-word;
}
```
