### ISSUE TITLE
While using docker, getting ESOCKETTIMEDOUT in Gitlab Ci pipeline job.

### ISSUE THREAD

**Issue by FilipePintoReis** [cypress-io/cypress#5975]
### Current behavior:

Our tests all pass locally, but when ran in the Gitlab CI pipeline (shared runner) the first two tests, which are in the same suite, fail with `ESOCKETTIMEDOUT`. The first one in the `beforeEach` hook and the second in the `afterEach` hook. The following tests pass.

We are using docker to run cypress (with the `cypress/included:3.2.0`) starting up both the backend and frontend services before running cypress

### Desired behavior:

For the tests to pass as they would locally

### Steps to reproduce: (app code and test code)

- Create a gitlab repository and add the following code to the `gitlab-ci.yml`

```
cypress-test:  
  stage: test  
  image: tiangolo/docker-with-compose  
  services:  
    - docker:dind  
  only:  
    - master  
    - branches  
  script:  
    - ./scripts/cypress-test.sh --build
```

- Install cypress in docker with the following [dockerfile](https://pastebin.com/ywc4WpRW) 

- Create several dummy tests, each visiting a localhost page. The first ones should fail

### Cypress, operating system, browser 

I'm using Docker, included:3.2.0 and Electron
