### ISSUE TITLE
Intermitten SIGABRT failure after successful test run

### ISSUE THREAD

**Issue by baconjulie** [cypress-io/cypress#6131]
### Current behavior:
Over the past month we intermittently get the following error after a successful test run in circle ci:

```
  ✔  All specs passed!                        02:30       35       35        -        -        -  

The Test Runner unexpectedly exited via a exit event with signal SIGABRT

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.
```

Re-triggering the job multiple times sometimes resolves the issue. Sometimes we need to wait a few hours and re-triggering the job resolves the issue. There is no clear error about what exactly is failing and if it is something we are doing wrong or an issue under the hood with `cypress run` in Circle.

### Desired behavior:
Successful test suites are able to complete in circle ci after the tests have passed. A more descriptive error message is displayed to help troubleshoot the SIGABRT.

### Test code to reproduce
- Running our cypress testing suite in circle ci:

.circle/config.yml
```
...
jobs:
  e2e:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          npm install && npm install cypress
          node -v && npm run start-server-and-cypress
```

package.json
```
...
"scripts": {
    "init-db": "cp ./fixtures/canonical_db.tar.gz ./data/my-database.tar.gz",
    "start-app": _command for starting rendering engine_,
    "start-server-and-cypress": "npm run init-db && start-server-and-test start-app http://localhost/my-page cypress run"
}
```

### Versions
Platform: linux (Ubuntu Linux - 14.04)
Cypress Version: 3.8.1
