### ISSUE TITLE
Cypress Timeout with no output

### ISSUE THREAD

**Issue by digitaldavenyc** [cypress-io/cypress#648]
- Operating System: Ubuntu 16.
- Cypress Version: latest: `0.20.0`
- Browser Version: Chrome

### Is this a Feature or Bug?
Bug

### Current behavior:

No tests run no output, I think having a verbose flag would be helpful but that is a separate issue.

### Desired behavior:
 Tests run

### How to reproduce:

`cypress run`

```
Cypress was not found: Installing a fresh copy.

  - Downloading Cypress [] 0% 0.0s  - Downloading Cypress [] 3% 0.0s  - Downloading Cypress [] 8% 1.1s  - Downloading Cypress [] 14% 1.2s  - Downloading Cypress [] 19% 1.3s  - Downloading Cypress [] 24% 1.3s  - Downloading Cypress [] 31% 1.1s  - Downloading Cypress [] 34% 1.2s  - Downloading Cypress [] 39% 1.1s  - Downloading Cypress [] 46% 0.9s  - Downloading Cypress [] 54% 0.8s  - Downloading Cypress [] 56% 0.8s  - Downloading Cypress [] 60% 0.7s  - Downloading Cypress [] 67% 0.6s  - Downloading Cypress [] 73% 0.5s  - Downloading Cypress [] 80% 0.4s  - Downloading Cypress [] 86% 0.2s  - Downloading Cypress [] 94% 0.1s  - Downloading Cypress [] 100% 0.0s
  - Unzipping Cypress   [] 2% 0.0s  - Unzipping Cypress   [] 4% 14.6s  - Unzipping Cypress   [] 6% 18.8s  - Unzipping Cypress   [] 9% 22.3s  - Unzipping Cypress   [] 11% 24.3s  - Unzipping Cypress   [] 13% 24.5s  - Unzipping Cypress   [] 15% 24.7s  - Unzipping Cypress   [] 17% 24.7s  - Unzipping Cypress   [] 19% 24.8s  - Unzipping Cypress   [] 21% 23.9s  - Unzipping Cypress   [] 23% 23.1s  - Unzipping Cypress   [] 26% 21.8s  - Unzipping Cypress   [] 28% 20.6s  - Unzipping Cypress   [] 30% 19.5s  - Unzipping Cypress   [] 32% 18.5s  - Unzipping Cypress   [] 34% 17.6s  - Unzipping Cypress   [] 36% 16.7s  - Unzipping Cypress   [] 38% 15.9s  - Unzipping Cypress   [] 40% 16.2s  - Unzipping Cypress   [] 43% 15.3s  - Unzipping Cypress   [] 45% 14.5s  - Unzipping Cypress   [] 47% 13.7s  - Unzipping Cypress   [] 49% 12.9s  - Unzipping Cypress   [] 51% 12.2s  - Unzipping Cypress   [] 53% 11.5s  - Unzipping Cypress   [] 55% 10.9s  - Unzipping Cypress   [] 57% 10.3s  - Unzipping Cypress   [] 60% 9.7s  - Unzipping Cypress   [] 62% 9.1s  - Unzipping Cypress   [] 64% 8.5s  - Unzipping Cypress   [] 66% 7.9s  - Unzipping Cypress   [] 68% 7.4s  - Unzipping Cypress   [] 70% 6.8s  - Unzipping Cypress   [] 72% 6.3s  - Unzipping Cypress   [] 74% 5.8s  - Unzipping Cypress   [] 77% 5.3s  - Unzipping Cypress   [] 79% 4.8s  - Unzipping Cypress   [] 81% 4.2s  - Unzipping Cypress   [] 83% 3.8s  - Unzipping Cypress   [] 85% 3.3s  - Unzipping Cypress   [] 87% 2.8s  - Unzipping Cypress   [] 89% 2.3s  - Unzipping Cypress   [] 91% 1.8s  - Unzipping Cypress   [] 94% 1.4s  - Unzipping Cypress   [] 96% 0.9s  - Unzipping Cypress   [] 98% 0.5s  - Unzipping Cypress   [] 100% 0.0s
  - Finished Installing /home/ubuntu/.cypress/Cypress (version: 0.20.0)

command cypress run took more than 10 minutes since last output
```

### Additional Info (images, stack traces, etc)

`cypress.json`

```
{
  "projectId": "xxxxx",
  "environmentVariables": {
    "FEATURE": "staging"
  }
}
```

`circle.yml`

```
machine:
  node:
    version: 6.10.0
  python:
    version: 2.7.11
  pre:
    - sudo curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0
    - sudo chmod 0755 /usr/bin/docker
    - pip install docker-compose==1.13.0 docker==2.3.0
  services:
    - docker

dependencies:
  cache_directories:
    - /home/ubuntu/nvm/versions/node/v6.10.0/bin/cypress
    - /home/ubuntu/nvm/versions/node/v6.10.0/lib/node_modules/cypress-cli
    - /home/ubuntu/.cypress/Cypress

dependencies:
  post:
    - npm install -g cypress-cli

test:
  pre:
    - ./bin/docker/build
    - ./bin/docker/seed
    - cypress run
    - npm run lint
```
