### ISSUE TITLE
CI jobs freezing in Gitlab but running perfectly on local Mac

### ISSUE THREAD

**Issue by abryant710** [cypress-io/cypress#6857]
### Current behavior:

I have some Cypress scripts that run to completion every time on my local Mac environment in both headed and headless Chrome. Cypress is working perfectly as expected locally. The problem I am having is adding this to our CI process in Gitlab. I have quoted the `.gitlab-ci.yml` file below. 

The process just hangs once it reaches the testing phase and times out after the 60 minute limit. We are getting the desired behaviour of the 3 tests scripts running in parallel on separate instances but all of them hang and timeout. Even as a single thread on once instance we see the same hanging behaviour. 

I suspect there are some missing dependencies for running Cypress on this OS? The build itself runs without errors (with quiet flags removed) and the processes freezes as shown in the screenshot.

<img width="783" alt="Screenshot 2020-03-26 at 14 35 30" src="https://user-images.githubusercontent.com/21152436/77659159-9c25d700-6f6f-11ea-88c8-5385fc562c62.png">

### Desired behavior:

Tests should run to completion in our Gitlab CI step and should complete without an error code to indicate that the push is acceptable.

### Test code to reproduce

```yml
image: node:10.4.1-stretch

stages:
  - test

before_script:
  - echo "deb http://mirrors.kernel.org/ubuntu/ xenial main" | tee -a /etc/apt/sources.list
  - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
  - apt-get -qq update && apt-get install -y --no-install-recommends apt-utils > /dev/null
  - apt-get -qq install -y --allow-unauthenticated libpng12-0 > /dev/null
  - apt-get -qq install -y python-pip python-dev > /dev/null
  - pip install -q --upgrade awscli
  - npm install --quiet

cache:
  untracked: true
  key: global
  paths:
    - node_modules
    - .npm

.cypress_build_script: &cypress_build_script |
  apt-get -qq install -y libgtk2.0-0 libnotify4 libgtk-3-0 libnotify-dev libgconf2-4 libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb > /dev/null
  wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb 
  apt -qq install -y --allow-unauthenticated ./google-chrome-stable_current_amd64.deb > /dev/null
  npm install -g --quiet wait-on
  npx cypress cache path
  npx cypress cache list
  PROXY=true npm run setup:development
  npm run build:dll
  npm start & wait-on http://localhost:4000

cypress_test_mdlu:
  stage: test
  script:  
    - *cypress_build_script
    - npm run cypress:run -- --spec \"cypress/integration/Smoke Tests/MDLU/*.spec.js\" --headless --browser chrome

cypress_test_dlu:
  stage: test
  script:  
    - *cypress_build_script
    - npm run cypress:run -- --spec \"cypress/integration/Smoke Tests/DLU/*.spec.js\" --headless --browser chrome

cypress_test_slu:
  stage: test
  script:  
    - *cypress_build_script
    - npm run cypress:run -- --spec \"cypress/integration/Smoke Tests/SLU/*.spec.js\" --headless --browser chrome
```

### Versions

Cypress:    4.2.0 
Browser:    Chrome 80 (headless)  
OS: Debian 9

**Comment by jennifer-shehane** [comment]
- Does it timeout on the same test each time?
- Does it timeout reliably every time?
- Could you run Cypress in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the entire set of logs here?

**Comment by abryant710** [comment]
Hi Jennifer,

- Does it timeout on the same test each time?

Yes it does seem to stall on the first or second test in the first spec file for each of the three concurrently running instances.

Does it timeout reliably every time?

Yes always the same behavior.

Could you run Cypress in debug mode mode and print the entire set of logs here?

I have added this into each spec file.

```
Cypress.on('fail', (error, runnable) => {
  debugger;

  // we now have access to the err instance
  // and the mocha runnable this failed on

  throw error; // throw error to have test still fail
});
```

Here is the log of the tests running to completion on my local environment. You can see that they all pass fine:

[cypress_headless_20200327105409.log](https://github.com/cypress-io/cypress/files/4393194/cypress_headless_20200327105409.log)

Here is an excerpt from one of the CI instances:

[cypress-ci-log.log](https://github.com/cypress-io/cypress/files/4393196/cypress-ci-log.log)

Here are some of the config params in cypress.json:

```
  "baseUrl": "http://localhost:4000",
  "watchForFileChanges": false,
  "viewportWidth": 1000,
  "viewportHeight": 660,
  "defaultCommandTimeout": 20000,
  "requestTimeout": 20000,
  "responseTimeout": 20000,
  "ignoreTestFiles": "*_template.spec.js",
  "video": false,
  "numTestsKeptInMemory": 0,
```

**Comment by Niceplace** [comment]
Hi @abryant710, have you considered using official cypress docker images and run your tests against them ? I don't mean to dismiss your issue entirely but from past experiences, making chrome/chromium work inside docker containers can be a bit of a pain and using pre-built images saved me lots of unwanted debugging.

I have no significant experience with Gitlab CI, only Jenkins and Github actions but looking at the YAML file you supplied it seems that you can run your workflow using a base docker image right ? What do you think ?

Here is the link to the repo for Cypress docker images: https://github.com/cypress-io/cypress-docker-images.
Note: the default values for the images is a few versions back, but if you specify it explicitely you can have the latest one (4.2.0 at the moment)

**Comment by abryant710** [comment]
@Niceplace thanks for the advice. I have tried using `cypress/browsers:node13.6.0-chrome80-ff72` but the testing script doesn't move much further on and it still grinds to a halt. 

```
stages:
  - test

before_script:
  - wget http://se.archive.ubuntu.com/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb
  - dpkg -i libpng12-0_1.2.54-1ubuntu1_amd64.deb
  - apt-get -qq install -y python-pip python-dev > /dev/null
  - pip install -q --upgrade awscli

cache:
  untracked: true
  key: global
  paths:
    - node_modules
    - .npm

.cypress_build_script: &cypress_build_script |
  npm install -g n wait-on
  n 10.4.1
  node -v
  npm install --quiet
  npx cypress cache path
  npx cypress cache list
  PROXY=true npm run setup:development
  npm run build:dll
  npm start & wait-on http://localhost:4000

cypress_test_mdlu:
  stage: test
  image: cypress/browsers:node13.6.0-chrome80-ff72
  script:  
    - *cypress_build_script
    - npm run cypress:smoke_tests:headless:mdlu

cypress_test_dlu:
  stage: test
  image: cypress/browsers:node13.6.0-chrome80-ff72
  script:  
    - *cypress_build_script
    - npm run cypress:smoke_tests:headless:dlu

cypress_test_slu:
  stage: test
  image: cypress/browsers:node13.6.0-chrome80-ff72
  script:  
    - *cypress_build_script
    - npm run cypress:smoke_tests:headless:slu
```
