### ISSUE TITLE
cypress-orb not running on circle-ci

### ISSUE THREAD

**Issue by Bbooth4** [cypress-io/cypress#7113]
### Current behavior:

App will get to the point where it compiles successfully in the circle-ci pipeline and then none of the tests would pass.

The first test returns

```
  1) Login successfully loads:
     Uncaught TypeError: Object(...) is not a function
```
which is just `it('successfully loads', () => cy.visit('/'));`

My circle-ci setup is as follows:

```yml
orbs:
  slack: circleci/slack@3.4.1
  cypress: cypress-io/cypress@1.19.2
workflows:
  version: 2.1
  commit:
    jobs:
      - cypress/install:
          install-command: 'npm install --no-optional --unsafe-perm'

      - cypress/run:
          requires:
            - cypress/install
          record: true
          command: 'npm run cy:pipeline'
```

That command is as follows:

```
"cy:pipeline": "start-server-and-test up http-get://localhost:8080 cy:run"
"cy:run": "cypress run --headless --record"
"up": "lerna run start --parallel"
```

One of the confusing parts is that `start-server-and-test` will not run cypress until the specified url is found, which it must have been because it ran. The only test was one that tries to visit that url. So the web-server must be closed shortly after it successfully compiles.

Should note that the site does use `webpack-dev-server`.

### Desired behavior:

`it('successfully loads', () => cy.visit('/'));` should succeed in the circle-ci pipeline.

### Versions

Cypress 4.4.0

**Comment by jennifer-shehane** [comment]
It looks like one of your test files, support files or plugin files may be throwing an error:

```
Uncaught TypeError: Object(...) is not a function
```

We changed some things about Cypress in order [to support TypeScript](https://github.com/cypress-io/cypress/issues/1859), could you try running on Cypress version 4.3.0 to see if this error is still present there?

**Comment by Bbooth4** [comment]
Thanks for replying, I finally found the issue.
```
workflows:
  version: 2.1
  commit:
    jobs:
      - cypress/install:

      - cypress/run:
          requires:
            - cypress/install
          record: true
          install-command: 'npm install --no-optional --unsafe-perm'
          command: 'npm run cy:pipeline'
```

the install command did solve provide any value in cypress/install and the built-in was insufficient for my app in cypress/run.

Simply moving it over solve the problem.
