### ISSUE TITLE
Communicate over network using Docker

### ISSUE THREAD

**Issue by JPHamlett1993** [cypress-io/cypress#724]
- Operating System: MacOS/Docker
- Cypress Version: 0.20.1
- Browser Version: Not sure, maybe Electron, it's the default on when you run 'cypress run'

### Is this a Feature or Bug?
Bug

### Current behavior:
Get the error:

```
cypress_1  | Started video recording: /cypress/cypress/videos/qbqyq.mp4
cypress_1  | 
cypress_1  |   (Tests Starting)
Unexpected API error for cypressfunctional_cypress_1 (HTTP code 500)
Response body:
dial unix /Users/john.hamlett/Library/Containers/com.docker.docker/Data/00000003.00000948: connect: connection refused
```

When the error occurs all my docker instances on that network crash.

### Desired behavior:
The tests to run

### How to reproduce:

Have Cypress communicate over a docker network, note the code works if I move all the cypress configuration into the same docker-compose file
#### Test code:

docker-compose-cypress

```version: '3'
services:
  cypress:
      build:
        context: .docker/
        dockerfile: CypressIO/Dockerfile
      volumes:
          - ".:/cypress"
      working_dir: /cypress
      privileged: true
      command: ["/bin/bash", "./run_cypress.sh", "app", "8080"]
      networks:
        - docker_bcp-net
networks:
  docker_bcp-net:
    external: true
```

docker-compose-app

```
version: '3'
services:
  app:
    image: openjdk:8
    ipc: host
    ports:
      - "8080:8080"
    volumes:
      - "../../:/bcp"
      - ${GRADLE_USER_HOME}:/gradle_mount
    working_dir: /bcp
    command: ["./gradlew", "-bbsb-core-web/build.gradle", "--no-daemon", "bootRun"]
    networks:
      - bcp-net
networks:
  bcp-net:
    driver: bridge
```

### Additional Info (images, stack traces, etc)

Dockerfile:

```
FROM cypress/base

RUN apt-get update && apt-get -y install netcat
```

run_cypress.sh
```
#!/usr/bin/env bash

host=$1
port=$2
shift 2
cmd="$@"


count=0
# wait for the application docker to be running
output=""
while [ "$output" != "open" -a $count -lt 1500 ]; do
    output=$(nc </dev/null $host $port && echo "open")
    >&2 echo "Localhost:8080 is unavailable - sleeping; Attempt ${count}"
    ((count++))
    sleep 1
done

if [ "$output" == "open" ]
    then
        npm install cypress wait-on --save-dev
        >&2 echo "Localhost:8080 is up - executing command"
        >&2 echo "curl http://$host:$port 1/2"
        $(npm bin)/wait-on http://$host:$port
        >&2 echo "curl http://$host:$port 2/2"
        $(npm bin)/wait-on http://$host:$port
        $(npm bin)/cypress verify
        $(npm bin)/cypress run --record --key MY_KEY
        exit 0
fi

>&2 echo "Localhost:8080 was unable to start"
```
