### ISSUE TITLE
Error: could not find CRI target (Cypress 4.6.0)

### ISSUE THREAD

**Issue by stevejefferies** [cypress-io/cypress#7450]
### Current behavior:

`cypress run` fails with the following error on Chrome:

```
Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was 26359.

Error details:

Error: could not find CRI target
    at lazyAssLogic (C:\Users\user\AppData\Local\Cypress\Cache\4.6.0\Cypress\resources\app\packages\server\node_modules\lazy-ass\index.js:110:14)
    at Object.lazyAss (C:\Users\user\AppData\Local\Cypress\Cache\4.6.0\Cypress\resources\app\packages\server\node_modules\lazy-ass\index.js:115:28)
    at findStartPage (C:\Users\user\AppData\Local\Cypress\Cache\4.6.0\Cypress\resources\app\packages\server\lib\browsers\protocol.js:56:23)
```

Full log is also attached.

Note that this doesn't appear to be 100% consistent. With the below example I am seeing this maybe 25% of the time.

We had previously observed this before, and upgraded to both 3.8.3 as a result of: https://github.com/cypress-io/cypress/issues/6053

Then more recently, upgraded to 4.6.0 as a result of: https://github.com/cypress-io/cypress/issues/6518

Still observing on 4.6.0 as below though

### Desired behavior:

Execution should not fail in this manner.

### Test code to reproduce

1. Clone https://github.com/stevejefferies/cypress-test-tiny
2. Run `cypress:run` as defined in package.json e.g. `npm run cypress:run`

### Versions

Cypress: 4.6.0
Browser: Chrome 83
OS: Windows 10

### Debug Log
[debug_log.txt](https://github.com/cypress-io/cypress/files/4666528/debug_log.txt)

**Comment by jennifer-shehane** [comment]
Oh, this is sad, we thought the increased timeout would help. Where are you running these tests when this typically happens? Locally? In a CI?

Running Chrome 83 headless

This happens at the very beginning of running the next spec (after the first spec has finished running), which is identical to #6518

**Comment by stevejefferies** [comment]
Unfortunately both observed locally and in a CI environment

**Comment by stevejefferies** [comment]
For reference its more typically observed on running the second (or subsequent) specs. But has been observed on running the first spec on occasion.

**Comment by jareqpl** [comment]
I have observed the same thing today. This started to occur after chrome update from 81 to 83.

**Comment by SonaliAvaya** [comment]
I also found the same error as @stevejefferies found 
What we should do for that? 
It working on cypress open UI but not able to run on the headless browser and not in CI environment

**Comment by diald** [comment]
We are also seeing this issue in CI. Chrome Version 83.0.4103.61 headless with Cypress 3.8.3. We also got same error with latest Cypress 4.6.0. In the meantime, we're using Electron 78 in CI - which is working.

**Comment by mikirobles** [comment]
This is happening in my github actions flow in a very inconsistent basis. Tried with the latest cypress version and also 3.8.3.

Workflow:
```
name: PR - Testing

on: [pull_request]

jobs:
  cypress-run:
    name: Cypress
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - name: Run tests
        uses: cypress-io/github-action@v1
        with:
          install: false
          browser: chrome
          start: npm run start-http
          wait-on: 'http://localhost:3000'
          config: baseUrl=http://localhost:3000,defaultCommandTimeout=10000
```

```
