### ISSUE TITLE
Allow easy testing of a new recipe under development from cypress-example-recipes

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#7584]
Often we develop a feature and create a recipe to show it off / test it in parallel. For example, the shadow dom support is being developed

- in PR https://github.com/cypress-io/cypress/pull/7469
- example recipe in PR https://github.com/cypress-io/cypress-example-recipes/pull/501

It would be great if we could run a test job from the Test Runner PR branch pointing at the example recipe PR

I think this could be done in circle.yml by expanding a few commands we already do to test example recipes. We would need to test example recipes repo with additional parameters:

- pull request number
- folder to run (so we don't run all recipes, but only a specific recipe)

So while working on the shadow dom branch, we would add a test job

```yml
test-binary-shadow-dom:
  <<: *defaults
  filters:
    branches:
      only:
        # once merged we will delete this job
        # and all recipes will run by default
        - shadows-branch
  steps:
    - test-binary-against-repo:
        repo: cypress-example-recipes
        command: npm run test:ci
        pull_request_id: 501
        folder: examples/unit-testing__lit-element
```
