### ISSUE TITLE
Download and install Cypress within GitLab CI

### ISSUE THREAD

**Issue by NeoLovesPython** [cypress-io/cypress#7683]
GitLab CI log is giving me this error output:

```
The cypress npm package is installed, but the Cypress binary is missing.

We expected the binary to be installed here: /root/.cache/Cypress/4.8.0/Cypress/Cypress
Reasons it may be missing:

- You're caching 'node_modules' but are not caching this path: /root/.cache/Cypress
- You ran 'npm install' at an earlier build step but did not persist: /root/.cache/Cypress

Properly caching the binary will fix this error and avoid downloading and unzipping Cypress.

Alternatively, you can run 'cypress install' to download the binary again.
```
This is my GitLab yml file (sharing only the relevant lines):

```yml
compile:
  stage: build
  script:
    - apk add --no-cache py-pip python2-dev python3-dev libffi-dev openssl-dev gcc libc-dev make
    - apk add npm
    - pip install docker-compose
    - docker-compose -f docker-compose-production.yml
```
below you can see my dockerfile (again I'm sharing only the relevant lines):
```yml
RUN npm ci
RUN npm install react-scripts@2.1.8 -g --silent
RUN npm install cypress@4.8.0 --silent
```
this is my package.json file (relevant lines):
```
"react": "^16.13.1",
"react-dom": "^16.13.1",
"react-router-dom": "^5.2.0",
"react-scripts": "^3.4.1"
```

I've tried the suggested solution to run `cypress install` even though it seemed little bit redundant to me but I did run it with no effect on the issue. Official docs recommend using `npm ci` when ran within CI tool so I've followed the recommendation.

Can I please get any feedback on this ? I've noticed Cypress used in any CI tool is quite a topic on the Internet.
