### ISSUE TITLE
Cypress can't verify localhost on specified service and port

### ISSUE THREAD

**Issue by NeoLovesPython** [cypress-io/cypress#7704]
This is my docker-compose file:

```yml
version: '3.7'

services:

  users:
    container_name: flask
    build:
      context: ./services/users
      dockerfile: Dockerfile
    volumes:
      - './services/users:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - SECRET_KEY=my_precious
    depends_on:
      - users-db

  users-db:
    container_name: postgres
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    container_name: react
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - './services/client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      - users

  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - client

  cypress:
    container_name: cypress
    ipc: host
    network_mode: host
    build:
      context: ./services/cypress
      dockerfile: Dockerfile
    depends_on:
      - nginx
```
I've got this in my cypress.json file:
```json
{
  "baseUrl": "http://nginx:80",
  "video": false
}
```
Dockerfile:
```yml
FROM cypress/included:4.8.0

WORKDIR /
COPY cypress.json /cypress.json
```

I've been trying to run tests on nginx as well as client:3007 both resulted in Cypress
not being able to verify that the localhost on the service is running and eventually timed out.
Is this a bug or I just don't know how to use it ?
