### ISSUE TITLE
Cypress on Azure Devops does not work

### ISSUE THREAD

**Issue by Maxime-Aubry-Econocom** [cypress-io/cypress#7865]
Hello.

i try to run a script on devops. It's an Asp.net MVC application.

Here is the package.json file :

```json
{
  "name": "markp.e2e",
  "version": "1.0.0",
  "description": "client testing project for MakP Control",
  "main": "app.js",
  "files": [
    "app",
    "cypress"
  ],
  "scripts": {
    "start:ci:windows": "serve --no-clipboard --listen 8080",
    "print-env": "print-env",
    "cy:verify": "cypress verify",
    "cy:info": "cypress info"
  },
  "author": "Maxime AUBRY",
  "license": "MIT",
  "dependencies": {
    "npm-run-all": "^4.1.2",
    "serve": "11.3.2"
  },
  "devDependencies": {
    "@bahmutov/print-env": "1.2.0",
    "cypress": "^4.9.0"
  },
  "engines": {
    "node": ">=4"
  }
}
```

Here is the azure-ci.yml file :

```yml
# if you want to configure triggers for Azure CI see
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#tags

name: 'Cypress E2E Testing'

trigger:
- origin/develop

schedules:
- cron: "0 6 * * *"
  displayName: Each morning at 6am
  branches:
    include:
    - origin/develop

variables:
# - group: develop
- name: npm_config_cache
  value: $(Pipeline.Workspace)/.npm
- name: cypress_cache_folder
  value: $(Pipeline.Workspace)/.cache/Cypress

stages:
- stage: e2e_testing_stage_edge
  displayName: 'Edge E2E Testing'
  dependsOn: []
  jobs:  
  - job: e2e_testing_job_edge
    displayName: 'Run E2E in Edge'
    pool:
      vmImage: windows-latest
    steps:
      - template: devops/e2e.testing.yml
        parameters:
          browserType: edge
          
- stage: e2e_testing_stage_electron
  displayName: 'Electron E2E Testing'
  dependsOn: []
  jobs:  
  - job: e2e_testing_job_electron
    displayName: 'Run E2E in Electron'
    pool:
      vmImage: windows-latest
    steps:
      - template: devops/e2e.testing.yml
        parameters:
          browserType: electron

- stage: e2e_testing_stage_chrome
  displayName: 'Chrome E2E Testing'
  jobs:
  - job: e2e_testing_job_chrome
    displayName: 'Run E2E in Chrome'
    pool:
      vmImage: windows-latest
    steps:
      - template: devops/e2e.testing.yml
        parameters:
          browserType: chrome

- stage: e2e_testing_stage_firefox
  displayName: 'Firefox E2E Testing'
  dependsOn: []
  jobs:
  - job: e2e_testing_job_firefox
    displayName: 'Run E2E in Firefox'
    pool:
      vmImage: windows-latest
    steps:
      - template: devops/e2e.testing.yml
        parameters:
          browserType: firefox
```

Here is the e2e.testing.yml file :

```yml
steps:
  - task: NodeTool@0
    displayName: 'Use Node 12.x'
    inputs:
      versionSpec: 12.x

  - task: CacheBeta@1
    displayName: Cache NPM packages
    inputs:
      key: npm | $(Agent.OS) | package-lock.json
      path: $(npm_config_cache)
      restoreKeys: npm | $(Agent.OS) | package-lock.json

  - task: CacheBeta@1
    displayName: Cache Cypress binary
    inputs:
      key: cypress | $(Agent.OS) | package-lock.json
      path: $(cypress_cache_folder)
      restoreKeys: cypress | $(Agent.OS) | package-lock.json
    
  # - task: Cache@2
  #   displayName: 'Cache npm'
  #   inputs:
  #     key: 'npm | "$(Agent.OS)" | package-lock.json'
  #     restoreKeys: |
  #       npm | "$(Agent.OS)"
  #       npm
  #     path: $(npm_config_cache)

  - script: npm ci
    displayName: 'Install NPM dependencies'

  - script: npm run cy:verify
    displayName: 'Cypress verify'

  - script: npm run cy:info
    displayName: 'Cypress info'

  - bash: |
      eval "npx print-env AGENT"
      eval "npx print-env BUILD"
      eval "npx print-env SYSTEM"
      eval "npm run start:ci:windows & npx cypress run --group ${{ parameters.browserType }} --browser ${{ parameters.browserType }} --record --parallel --key 5c38b32e-7e24-45b4-8955-e7216ec80cca --ci-build-id $BUILDID"
    displayName: 'Run the cypress tests'
    env:
      TERM: xterm
      BUILDID: $(Build.BuildId)
  
  - task: PublishTestResults@2
    displayName: 'Publish the test reports'
    inputs:
      testResultsFiles: '**/reports/junit.*.xml'
    condition: succeededOrFailed()
    continueOnError: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish screenshots when there were issues'
    inputs:
      pathtoPublish: 'cypress/screenshots'
      artifactName: screenshots-${{ parameters.browserType }}
    condition: failed()
    continueOnError: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish videos'
    inputs:
      pathtoPublish: 'cypress/videos'
      artifactName: videos-${{ parameters.browserType }}
    condition: succeededOrFailed()
    continueOnError: true
```

When devops starts tests with the first web browser, tests are run. It's ok.
devops uploads the report and videos, and then there is a **first error message** :

```
The STDIO streams did not close within 10 seconds of the exit event from process 'C:\Program Files\Git\bin\bash.exe'. This may indicate a child process inherited the STDIO streams and has not yet exited.
##[error]Bash exited with code '8'.
```

Then, other test with next web browsers are started.
And I get this new error message :

```
The run you are attempting to access is already complete and will not accept new groups.

The existing run is: https://dashboard.cypress.io/projects/eopr5n/runs/20

When a run finishes all of its groups, it waits for a configurable set of time before finally completing. You must add more groups during that time period.

The --tag flag you passed was: 
The --group flag you passed was: electron
The --parallel flag you passed was: true
The --ciBuildId flag you passed was: 18997

https://on.cypress.io/already-complete
The STDIO streams did not close within 10 seconds of the exit event from process 'C:\Program Files\Git\bin\bash.exe'. This may indicate a child process inherited the STDIO streams and has not yet exited.
##[error]Bash exited with code '1'.
```

I use **cypress v4.9.0** and **DevOps**.
