### ISSUE TITLE
Experimental fetch polyfill at GH actions fails

### ISSUE THREAD

**Issue by Wozniaxos** [cypress-io/cypress#7889]
Hey, I am using `"experimentalFetchPolyfill": true` on my project. Tests passes locally nicely but on the GH actions pipeline they fail, I cleaned cache locally to reproduce pipeline steps at the same way but the tests also passed successfully. I use Cypress `4.9.0`

I added `"experimentalFetchPolyfill": true` flag in `cypress.json`

This is how I mock requests: 
```js
 it('should call proper BE endpoint with proper params', () => {
    cy.server();
    cy.route({
      method: 'POST',
      url: 'api/v1/users/sign_in',
      response: {
        token: dummyToken,
      },
    }).as('login');
    cy.visit('sign-in/users');

    cy.get('[data-testid=login-input]').type('user');
    cy.get('[data-testid=password-input]').type('password');
    cy.get('[data-testid=login-submit]').click();

    cy.wait('@login')
      .its('requestBody')
      .should('deep.equal', {
        user: {
          username: 'user',
          password: 'password',
        },
      });

    cy.get('@login').should('have.property', 'url', 'http://localhost:4000/api/v1/users/sign_in');
  });
```

this is my `workflow.yaml`

```yaml
frontend:
    name: Frontend
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: test
        run: npm test -- --coverage

      - name: app running
        run: npm run setup-server-for-e2e
        
      - name: cypress run
        run: npm run test:cypress
```
`setup-server-for-e2e` i just  `npm start & wait-on http://localhost:3000`
I haven't attached log from cypress cause this is meaningless info that it can't wait for particular element (cause fetch request failed on that particular tests) - I had that exact same problem with same tests before adding experimental fetch polyfill - it helped - but only locally - that is why i assume that problem is there.

GH actions failing tests are only tests which depends on fetch requests. Do you have any idea what might be the cause of this?

**Comment by jennifer-shehane** [comment]
I would suggest following on recommendations on troubleshooting why tests are fail in CI but pass locally: https://on.cypress.io/using-cypress-faq#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI

Maybe these tests always fail in Electron for example (which is the default browser during `cypress run` as opposed to `cypress open`)? 

Let us know the results.

**Comment by Wozniaxos** [comment]
I doubt that this is it.

This is information from running it locally:
![image](https://user-images.githubusercontent.com/26778061/86745089-64ccc900-c03a-11ea-84b2-014e7ea88173.png)

This is when running on CI
![image](https://user-images.githubusercontent.com/26778061/86745141-6e563100-c03a-11ea-981b-3a722cf0d681.png)

**Comment by jennifer-shehane** [comment]
@bahmutov Any thoughts on why this might fail in GH actions?

**Comment by Wozniaxos** [comment]
I tried also doing it like descrived here -> https://www.cypress.io/blog/2020/06/29/experimental-fetch-polyfill/ i mean i did:
```js
  it('should authorize users after correct BE response', () => {
    cy.server();

    cy.visit('/users/auth?code=somecode', {
      onBeforeLoad (win) {
        cy.stub(win, 'fetch').withArgs('http://localhost:4000/api/v1/users/oauth2_callback')
          .resolves({
            ok: true,
            json: () => ({
              token: dummyToken,
            }),
          });
      },
    });

    cy.get('[data-testid=user-app]').should('exist');
  });
```

And result is the same, locally it works but on CI it crushes, no matter if running through `cypress open` or `cypress run` from console, it always works locally and tests are passing.

**Comment by Wozniaxos** [comment]
@jennifer-shehane  So maybe it is not related specifically to fetch polyfill but something else? I tried also instead of just running `cypress run` at CI running it through -> https://www.cypress.io/blog/2019/11/20/drastically-simplify-your-testing-with-cypress-github-action/

Then my workflow is:

```yaml
name: Pipeline
on: [push,pull_request]
jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: test
        run: npm test -- --coverage
        
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:3000

```

and the result is still the same
