### ISSUE TITLE
Tests run fine locally but hang in Drone build

### ISSUE THREAD

**Issue by jackgilbertx** [cypress-io/cypress#8042]
### Current behavior:
When running tests locally, everything works fine.  However, when I run the tests through in CI using Drone, the tests hang and will not run.  We use a custom image for running cypress but the issue persists when using just the cypress base image like so: 

```yml
## .drone.yml
---
pipeline:

  cypress_run:
    image: cypress/browsers:node13.8.0-chrome81-ff75
    commands:
      - npm install
      - ./node_modules/.bin/cypress run --headless --browser chrome --spec 'cypress/integration/UI/**/*spec*.js'
```
```json
## package.json
"author": "DIP Team",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.9.6",
    "@babel/preset-env": "^7.9.6",
    "@cypress/schema-tools": "^4.7.4",
    "@cypress/skip-test": "^2.5.0",
    "@cypress/webpack-preprocessor": "^5.4.1",
    "cypress-image-snapshot": "^3.1.1",
    "babel-loader": "^8.1.0",
    "cypress": "^4.10.0",
    "cypress-multi-reporters": "^1.4.0",
    "cypress-terminal-report": "^1.2.1",
    "eslint": "^7.0.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-cypress": "^2.10.3",
    "eslint-plugin-prettier": "^3.1.3",
    "jwt-decode": "^2.2.0",
    "mocha": "^8.0.1",
    "mochawesome": "^6.1.1",
    "mochawesome-merge": "^4.1.0",
    "mochawesome-report-generator": "^5.1.0",
    "prettier": "^2.0.5",
    "query-string": "^6.12.1",
    "webpack": "^4.43.0"
  },
  "dependencies": {
    "cypress-localstorage-commands": "^1.2.1",
    "jsonexport": "^3.0.1",
    "loglevel": "^1.6.8"
  }
```
I have tried using a few different versions of Cypress with the same result. 

### Desired behavior:
The desired behavior is that the tests execute as they do when running on my machine locally.

### Test code to reproduce
A really large suite (every spec file we currently have) is run so it would be hard to provide everything but I can provide some DEBUG logs for now:
![image](https://user-images.githubusercontent.com/30162499/87983321-cc086580-ca9d-11ea-9bae-058616f552be.png)

See the `FATAL - out of memory error` on line 1468, wondering if this is the root cause.

### Versions
browser: chrome
cypress: 4.10.0
