### ISSUE TITLE
Google Cloud Build - Your system is missing the dependency: Xvfb

### ISSUE THREAD

**Issue by elihorne** [cypress-io/cypress#8177]
### Current behavior:

I'm trying to run Cypress with Google Cloud Build, following cy documentation, and reading the [existing](https://github.com/cypress-io/cypress/issues/4920) [issues](https://github.com/cypress-io/cypress/issues/4920) on github. I'm making it through most of the build, until I do `cy:run`, and the build console says: `Your system is missing the dependency: Xvfb`.

### Desired behavior:

Cypress would run successfully.

### Versions

"cypress": "^4.11.0",

### Code

```yml
steps:
#install
- name: 'gcr.io/cloud-builders/npm:node-10.10.0'
  args: ['install']

#test
- name: 'gcr.io/cloud-builders/npm:node-10.10.0'
  args: ['run', 'e2e']

  #deploy
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy', '--project=[project-id]', '--only=hosting']
```

from package.json
```json
"scripts": {
    "start": "firebase serve --project=[project-id]",
    "test": "cypress run",
    "cy:open": "cypress open",
    "cy:run": "cypress run",
    "dev": "start-test 5000 cy:open",
    "e2e": "start-test 5000 cy:run"
```

Output from Google Cloud Build:

```
cypress run
Step #1: 
tep #1: It looks like this is your first time using Cypress: 4.11.0
Step #1: 
Step #1: [02:17:06]  Verifying Cypress can run /builder/home/.cache/Cypress/4.11.0/Cypress [started]
Step #1: [02:17:06]  Verifying Cypress can run /builder/home/.cache/Cypress/4.11.0/Cypress [failed]
Step #1: [02:17:06] → Your system is missing the dependency: Xvfb
Step #1: 
Step #1: Install Xvfb and run Cypress again.
Step #1: 
Step #1: Read our documentation on dependencies for more information:
Step #1: 
Step #1: https://on.cypress.io/required-dependencies
Step #1: 
Step #1: If you are using Docker, we provide containers with all required dependencies installed.
Step #1: 
Step #1: ----------
Step #1: 
Step #1: Error: spawn Xvfb ENOENT
Step #1: 
Step #1: ----------
Step #1: 
Step #1: Platform: linux (Debian - 8.11)
Step #1: Cypress Version: 4.11.0
Step #1: Your system is missing the dependency: Xvfb
Step #1: 
Step #1: Install Xvfb and run Cypress again.
```
