### ISSUE TITLE
Cypress fails to retry job on GitLab CI with --record and --group flags

### ISSUE THREAD

**Issue by damusnet** [cypress-io/cypress#8451]
### Current behavior:
On GitLab CI, when a recorded job with multiple groups fails and is being retried, Cypress errors out with `You passed the --group flag, but this group name has already been used for this run.` for the second group.

### Desired behavior:
Retries should run for all groups.

### Test code to reproduce
In our particular case we run two groups:

```yml
// .gitlab-ci.yml

cypress:
  stage: test
  image: cypress/browsers:node14.7.0-chrome84
  before_script:
    - cd cypress
    - npm ci
  script:
    - npm run cli -- --browser chrome --headless --record --group Backend --spec 'integration/backend/**/*'
    - npm run cli -- --browser chrome --headless --record --group Frontend --spec 'integration/frontend/**/*'
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day
```

The first run fails for whatever reason. The second run (retry) starts, executes the first group (`Backend`) without issue, and fails on the second group (`Frontend`).

**Second run, first group:**

![image](https://user-images.githubusercontent.com/433409/91747413-61a61300-eb7b-11ea-9c11-a6a7ba52351c.png)

**Second run, second group:** Here you can see `Recorded Run: https://dashboard.cypress.io/projects/khj9rq/runs/16` for the first group, followed by `You passed the --group flag, but this group name has already been used for this run.` for the second group:

![image](https://user-images.githubusercontent.com/433409/91747493-839f9580-eb7b-11ea-8751-3cf7ff7d4bef.png)

Adding a new commit to the branch "fixes" it and lets the tests pass again.

On the Dashboard it translates to incomplete or mismatched reporting:

**Incomplete run 16 from above logs:**
![image](https://user-images.githubusercontent.com/433409/91748087-9bc3e480-eb7c-11ea-9900-a383fa8dd5fa.png)

**Incomplete previous run 15:**
![image](https://user-images.githubusercontent.com/433409/91748150-bb5b0d00-eb7c-11ea-87b8-b6cfda028798.png)

**Successful next run 17:**
![image](https://user-images.githubusercontent.com/433409/91748225-e180ad00-eb7c-11ea-95c2-e3aa1d659fa2.png)

### Versions
* "cypress": "5.0.0"
* gitlab-runner 13.0.0
